package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.c */
public final class C11796c implements C11857oc {

    /* renamed from: a */
    private static final Map f37149a = new HashMap();

    /* renamed from: b */
    private static final Map f37150b = new HashMap();

    /* renamed from: c */
    private static final Map f37151c = new HashMap();

    public C11796c() {
        f37149a.put(C11761Rb.AGREE_AND_PAY, "Concordar e pagar");
        f37149a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "- somado a:");
        f37149a.put(C11761Rb.AUTHENTICATING, "Autenticando");
        f37149a.put(C11761Rb.BACK_BUTTON, "Voltar");
        f37149a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Reserva");
        f37149a.put(C11761Rb.CANCEL, "Cancelar");
        f37149a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37149a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37149a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37149a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37149a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37149a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37149a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37149a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37149a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37149a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37149a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37149a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37149a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37149a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37149a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Cartão Aurora");
        f37149a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37149a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Alterar meio de pagamento");
        f37149a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Conta corrente");
        f37149a.put(C11761Rb.CHECKING_DEVICE, "Verificando dispositivo…");
        f37149a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Apagar informações do cartão");
        f37149a.put(C11761Rb.CONFIRM, "Confirmar");
        f37149a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Deseja mesmo apagar as informações do seu cartão?");
        f37149a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Cobrar cartão");
        f37149a.put(C11761Rb.CONFIRM_LOG_OUT, "Tem certeza de que deseja sair do PayPal?");
        f37149a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Pagar");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Acordo");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data de criação da conta");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Status da conta");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo de conta");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Endereço");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Faixa etária");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data de nascimento");
        String str = "E-mail";
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, str);
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nome completo");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sexo");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Idioma");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Idioma");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefone");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Fuso horário");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Compartilhar: %s.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Usar Checkout contínuo.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s pede que você:");
        String str2 = "Compartilhar os <a href='%1$s'>meios de pagamento</a> adicionados à sua conta do PayPal.";
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, str2);
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Ativar a exibição de seus meios de pagamento para escolher com qual pagar.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorizar cobranças</a> para compras futuras com PayPal no parceiro %2$s. Você autoriza o PayPal a pagar todos os valores solicitados por %3$s.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Permite adicionar e gerenciar os cartões fidelidade à sua carteira do PayPal.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Concorde com a <a href='%2$s'>Política de Privacidade</a> e o <a href='%3$s'>Contrato do Usuário</a> do parceiro %1$s.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Autorize a <a href='%1$s'>solicitação de pagamentos</a> em seu nome até você cancelar o consentimento.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Autorize o <a href='%1$s'>envio de pagamentos</a> em seu nome até você cancelar o consentimento.");
        f37149a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Permissão");
        f37149a.put(C11761Rb.EMAIL, str);
        f37149a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Dados fictícios");
        f37149a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37149a.put(C11761Rb.EXPIRES_ON_DATE, "Vencimento");
        f37149a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Meios de pagamento</strong></h1><p>O PayPal compartilha apenas os meios de pagamento que estão disponíveis para uso.</p>");
        f37149a.put(C11761Rb.FORGOT_PASSWORD, "Esqueceu a senha?");
        f37149a.put(C11761Rb.FROM_ACCOUNT, "De");
        f37149a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Como gostaria de pagar %1$s nas próximas compras?");
        f37149a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>O meio de pagamento padrão será usado para pagar as compras futuras com PayPal feitas neste vendedor.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Minhas configurações</strong> &gt; <strong>Acesso com o PayPal</strong> e remova esse vendedor da lista.</p><p>A seção Pagamentos Recorrentes do <a href='%s'>Contrato do Usuário do PayPal</a> será aplicada.</p><p>Para confirmar se é possível enviar e receber pagamentos com sua conta do PayPal, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de recursos.</p>");
        f37149a.put(C11761Rb.INTERNAL_ERROR, "Erro interno");
        f37149a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ao clicar no botão a seguir, eu concordo com os termos do <a href='%1$s'>Contrato do Usuário do PayPal</a> e declaro estar em conformidade com as leis e as normas japonesas, inclusive as sanções contra pagamentos à Coreia do Norte e ao Irã definidas na lei de câmbio internacional e comércio exterior (<a href='%2$s'>Foreign Exchange and Foreign Trade Act</a>), para concluir a transação.</p>");
        f37149a.put(C11761Rb.LOG_IN, "Acessar conta");
        f37149a.put(C11761Rb.LOG_IN_TO_PAYPAL, "Acesso com PayPal");
        f37149a.put(C11761Rb.LOG_OUT_BUTTON, "Sair");
        f37149a.put(C11761Rb.LOG_OUT, "Sair");
        f37149a.put(C11761Rb.OK, "OK");
        f37149a.put(C11761Rb.PASSWORD, "Senha");
        f37149a.put(C11761Rb.PAY_AFTER_DELIVERY, "Pagar depois da entrega");
        f37149a.put(C11761Rb.PAY_WITH, "Pagar com");
        f37149a.put(C11761Rb.PAY_WITH_CARD, "Pagar com cartão");
        f37149a.put(C11761Rb.PAYPAL_BALANCE, "Saldo do PayPal");
        f37149a.put(C11761Rb.PAYPAL_CREDIT, "Crédito do PayPal");
        f37149a.put(C11761Rb.PHONE, "Telefone");
        f37149a.put(C11761Rb.PIN, "Senha de cel.");
        f37149a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Meio pref. de pagto");
        f37149a.put(C11761Rb.PRIVACY, "O PayPal protege sua <a href='%s'>privacidade</a> e suas informações financeiras.");
        f37149a.put(C11761Rb.PROCESSING, "Processando");
        f37149a.put(C11761Rb.REMEMBER_CARD, "Lembrar cartão");
        f37149a.put(C11761Rb.REQUEST_MONEY, "Solicitar pagamento");
        f37149a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.com e vá para a opção <strong>Log in com PayPal</strong> nas configurações do <strong>Perfil</strong> e remova esse vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do parceiro.</p>");
        f37149a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Conta poupança");
        f37149a.put(C11761Rb.SEND_MONEY, "Enviar pagamentos");
        f37149a.put(C11761Rb.SERVER_PROBLEM, "Problema na comunicação com os servidores do PayPal. Tente novamente.");
        f37149a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Acesse sua conta do PayPal novamente.");
        f37149a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sessão expirada");
        f37149a.put(C11761Rb.SHIPPING_ADDRESS, "Endereço de entrega");
        f37149a.put(C11761Rb.SIGN_UP, "Novo no PayPal? Inscreva-se");
        f37149a.put(C11761Rb.STAY_LOGGED_IN, "Permanecer conectado");
        f37149a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Erro do sistema (%s). Tente novamente mais tarde.");
        f37149a.put(C11761Rb.TRY_AGAIN, "Tentar novamente");
        f37149a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Não é possível acessar sua conta porque o recurso de autenticação em duas etapas está ativado para esta conta.");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Código de segurança");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Envie uma mensagem de texto para o seu telefone. O código de 6 dígitos é válido por 5 minutos.");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Enviando texto");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Informe o código de segurança de 6 dígitos");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Seu número de celular");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Enviar texto");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Enviar texto novamente");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Não é possível acessar sua conta porque o recurso de autenticação em duas etapas está ativado para esta conta. Visite o site do PayPal para ativar sua chave de segurança.");
        f37149a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Pagamentos não permitidos com este dispositivo.");
        f37149a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo não autorizado");
        f37149a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Não é permitido enviar pagamentos a este vendedor (ID de cliente inválido).");
        f37149a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Vendedor inválido");
        f37149a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Ocorreu um problema ao processar seu pagamento. Tente novamente.");
        f37149a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Fonte não reconhecida");
        f37149a.put(C11761Rb.WE_ARE_SORRY, "Erro");
        f37149a.put(C11761Rb.YOUR_ORDER, "Seu pedido");
        f37149a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Este dispositivo não pode se comunicar com o PayPal porque esta versão do Android é muito antiga. Por favor, atualize Android ou tente de novo em um dispositivo mais novo.");
        f37149a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Apagar cartão?");
        f37149a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Falha de permissão");
        f37149a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Falha de conexão");
        f37149a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Falha de acesso");
        f37149a.put(C11761Rb.LOGIN_WITH_EMAIL, "Acessar conta com senha");
        f37149a.put(C11761Rb.LOGIN_WITH_PHONE, "Acessar conta com senha de cel.");
        f37149a.put(C11761Rb.ONE_MOMENT, "Aguarde…");
        f37149a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Falha no pagamento");
        f37149a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Digitalizar");
        f37149a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Cód. Seg. incorreto Tente novamente.");
        f37149a.put(C11761Rb.VIA_LABEL, "Via");
        String str3 = "Erro do sistema. Tente novamente mais tarde.";
        f37149a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str3);
        String str4 = "Compartilhar informações sobre os <a href='%1$s'>meios de pagamento</a> adicionados à sua conta do PayPal.";
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str4);
        String str5 = "Compartilhar <a href='%1$s'>meios de pagamento</a> em seu nome até você cancelar o consentimento.";
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Compartilhar informações com eles sobre os <a href='%1$s'>meios de pagamento</a> adicionados à sua conta do PayPal.");
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", str2);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", str2);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str4);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str5);
        f37150b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str5);
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizar cobranças</a> para compras futuras com PayPal no parceiro %2$s. Você autoriza o PayPal a pagar todos os valores solicitados por %3$s.</p><p>Consulte o <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Contrato de Cobrança e Pagamentos Recorrentes do PayPal</a> para mais informações.</p>");
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizar cobranças</a> para compras futuras com PayPal no parceiro %2$s. Você autoriza o PayPal a pagar todos os valores solicitados por %3$s.</p><p>Consulte o <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Contrato de Cobrança e Pagamentos Recorrentes do PayPal</a> para mais informações.</p>");
        String str6 = "<a href='%1$s'>Autorize cobranças</a> para compras futuras com o PayPal. Você autoriza e define o PayPal para pagar todos os valores.";
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37150b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Pré-aprove pagamentos futuros feitos com sua conta do PayPal sem ter que acessar o PayPal toda vez. <a href='%1$s'>Consulte os Termos Adicionais</a>, incluindo meios de pagamento e como cancelar pagamentos futuros.");
        String str7 = "Autorizar %2$s a <a href='%1$s'>solicitar pagamento</a> em seu nome até você cancelar o consentimento.";
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37150b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Autorizar %2$s a <a href='%1$s'>enviar pagamento</a> em seu nome até você cancelar o consentimento.";
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37150b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>Meios de pagamento</strong></h1><p>O PayPal compartilha apenas quais dos seus meios de pagamento estão disponíveis para uso.</p>";
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>Meios de pagamento</strong></h1><p>O PayPal compartilha apenas informações sobre quais dos seus meios de pagamento estão disponíveis para uso.</p>";
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37150b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de recursos.</p><p>Seu meio de pagamento padrão (saldo do PayPal, conta bancária ou cartão de crédito, nessa ordem) será usado para pagar as compras feitas usando o PayPal. Se o seu meio de pagamento padrão não tiver fundos suficientes para cobrir a compra, seu banco ou emissor do cartão poderá cobrar uma tarifa.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> e clique em <strong>Minhas configurações</strong> e <strong>Alterar</strong>, ao lado de “Acesso com o PayPal”.</p>");
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de pagamentos.</p><p>O saldo do PayPal ou o cartão de crédito principal será usado para pagar as compras feitas usando o PayPal.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Minhas configurações</strong> &gt; <strong>Acesso com o PayPal</strong> e remova esse vendedor da lista.</p>");
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de pagamentos.</p><p>Seu meio de pagamento padrão será usado para pagar as compras feitas usando o PayPal.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Configurações</strong> &gt; <strong>Acesso com o PayPal</strong> e remova esse vendedor da lista.</p>");
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>O meio de pagamento padrão será usado para pagar as compras futuras com PayPal feitas neste vendedor.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Minhas configurações</strong> &gt; <strong>Log in com PayPal</strong> e remova esse vendedor da lista.</p><p>A seção Pagamentos Recorrentes do <a href='%s'>Contrato do Usuário do PayPal</a> será aplicada.</p><p>Para confirmar se é possível enviar e receber pagamentos com sua conta do PayPal, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de recursos.</p>");
        String str11 = "<h1><strong>Autorização de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de recursos.</p><p>Seu meio de pagamento preferencial será usado para pagar as compras feitas com PayPal.</p><p>Para cancelar esta autorização, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Configurações da minha conta</strong> &gt; <strong>Log in com PayPal</strong> e remova esse vendedor da lista.</p><p>Consulte a seção “Pagamentos pré-aprovados” do <a href='%s'>Contrato do Usuário do PayPal</a> para mais informações.</p>";
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorização de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de pagamentos.</p><p>Seu meio de pagamento padrão será usado para pagar as compras feitas usando o PayPal.</p><p>Para cancelar esta autorização, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Configurações da minha conta</strong> &gt; <strong>Log in com PayPal</strong> e remova esse vendedor da lista.</p><p>Consulte a seção “Pagamentos pré-aprovados” do <a href='%s'>Contrato do Usuário do PayPal</a> para mais informações.</p>");
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>Para confirmar se sua conta do PayPal poderá ser debitada no futuro, este aplicativo poderá simular uma transação de teste de baixo valor, mas sem transferência de pagamentos.</p><p>O saldo do PayPal ou o cartão de crédito principal será usado para pagar as compras feitas usando o PayPal.</p><p>Para cancelar este contrato, acesse sua conta do PayPal, vá para <strong>Perfil</strong> &gt; <strong>Minhas configurações</strong> &gt; <strong>Acesso com o PayPal</strong> e remova esse vendedor da lista.</p>");
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37150b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Contrato de Pagamentos Futuros</strong></h1><p>O PayPal usará primeiro o saldo do PayPal para pagar sua compra. Caso não haja saldo para cobrir o valor total, a conta bancária, o crédito do PayPal, o cartão de débito, o cartão de crédito e/ou o cheque digital serão usados, nessa ordem.</p><p>Para cancelar este contrato, acesse www.paypal.com.br <strong>Perfil</strong> &gt; <strong>Minhas configurações</strong> &gt; <strong>Acesso com o PayPal</strong> e remova esse vendedor da lista.</p><p>Pode ser necessária a autorização de um pagamento de baixo valor para confirmar se sua conta do PayPal poderá ser debitada no futuro. A autorização será anulada e você não será cobrado.</p>");
        f37150b.put("LOG_IN_TO_PAYPAL|AU", "Log in com PayPal");
        f37150b.put("LOG_IN_TO_PAYPAL|GB", "Log in com PayPal");
        String str12 = "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.com e vá para <strong>Perfil</strong>, <strong>Segurança</strong>, encontre a opção <strong>Log in com PayPal</strong> e remova esse vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do vendedor.</p>";
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o parceiro.</p><p>Para cancelar o consentimento, acesse sua conta do PayPal e clique no ícone de engrenagem. Acesse <strong>Segurança</strong>, selecione <strong>Log in com PayPal</strong> e remova esse parceiro.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do parceiro.</p>";
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.com e vá para a opção <strong>Log in PayPal</strong> nas configurações do <strong>Perfil</strong> e remova esse vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do parceiro.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse sua conta do PayPal e vá para a opção <strong>Log in com PayPal</strong> nas configurações do <strong>Perfil</strong> e remova esse vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do vendedor.</p>";
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse sua conta do PayPal, clique no ícone de engrenagem no canto superior direito, escolha <strong>Central de segurança</strong>, selecione <strong>Log in com PayPal</strong> e remova o vendedor. Se você ainda usa o site clássico, acesse <strong>Meu perfil</strong>, escolha <strong>Minhas configurações da conta</strong>, selecione <strong>Log in com PayPal</strong> e remova o vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do vendedor.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o parceiro.</p><p>Para cancelar o consentimento, acesse sua conta do PayPal e, nas configurações do <strong>Perfil</strong>, vá para <strong>Log in com PayPal</strong> e remova esse parceiro.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do parceiro.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.it e vá para <strong>Perfil</strong>, <strong>Segurança</strong>, encontre a opção <strong>Log in com PayPal</strong> e remova esse vendedor.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do vendedor.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o parceiro.</p><p>Para cancelar o consentimento, acesse o site paypal.ru, clique no ícone de engrenagem no canto superior direito, escolha a guia <strong>Segurança</strong> e, na opção <strong>Log in com PayPal</strong>, remova esse parceiro.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do parceiro.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.com.tr, clique no ícone de engrenagem no canto superior direito, escolha a guia <strong>Segurança</strong> e, na opção <strong>Log in com PayPal</strong>, remova esse parceiro.</p><p>O PayPal não é responsável por nenhuma ação ou erro por parte do vendedor.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Qualquer detalhe relevante da transação será compartilhado com o vendedor.</p><p>Para cancelar o consentimento, acesse o site paypal.com e vá para a opção <strong>Log in com PayPal</strong> nas configurações do <strong>Perfil</strong> e remova esse vendedor.</p>");
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37150b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37151c.put("AMOUNT_MISMATCH", "O valor total dos produtos no carrinho não coincide com o valor da venda.");
        f37151c.put("AUTHORIZATION_ALREADY_COMPLETED", "Esta autorização já foi concluída.");
        f37151c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "O estado da autorização não permite a anulação.");
        f37151c.put("AUTHORIZATION_EXPIRED", "A autorização expirou.");
        f37151c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "O ID de autorização solicitado não existe.");
        f37151c.put("AUTHORIZATION_VOIDED", "A autorização foi anulada.");
        f37151c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Só é possível reautorizar a autorização original, não uma nova autorização.");
        f37151c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Nova autorização não permitida no período de cumprimento.");
        f37151c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "O valor excede o limite permitido.");
        f37151c.put("CARD_TOKEN_PAYER_MISMATCH", "Não é possível acessar as informações salvas do cartão.");
        f37151c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Informações do cartão inválidas. Corrija e envie novamente.");
        f37151c.put("CREDIT_CARD_REFUSED", "Cartão recusado.");
        f37151c.put("CURRENCY_MISMATCH", "A moeda de captura deve ser a mesma que a moeda da autorização.");
        f37151c.put("CURRENCY_NOT_ALLOWED", "O PayPal não aceita esta moeda no momento.");
        f37151c.put("DATA_RETRIEVAL", str3);
        f37151c.put("DUPLICATE_REQUEST_ID", str3);
        f37151c.put("EXPIRED_CREDIT_CARD", "Cartão vencido");
        f37151c.put("EXPIRED_CREDIT_CARD_TOKEN", "As informações desse cartão foram apagadas.\nCadastre-o novamente.");
        f37151c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Não há suporte desse recurso para esse fornecedor.");
        f37151c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Esta transação já foi parcialmente reembolsada.");
        f37151c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Não há suporte do Pagamento imediato para a finalidade transmitida.");
        f37151c.put("INSTRUMENT_DECLINED", "O meio de pagamento selecionado não foi aceito. Escolha outro meio de pagamento.");
        f37151c.put("INSUFFICIENT_FUNDS", "Comprador não pode pagar - fundos insuficientes.");
        f37151c.put("INTERNAL_SERVICE_ERROR", str3);
        f37151c.put("INVALID_ACCOUNT_NUMBER", "Esse número de conta não existe.");
        f37151c.put("INVALID_ARGUMENT", "Transação recusada: argumento inválido");
        f37151c.put("INVALID_CITY_STATE_ZIP", "Combinação de cidade/estado/cep inválida.");
        f37151c.put("INVALID_FACILITATOR_CONFIGURATION", "A transação não pode ser processada porque a configuração de facilitador é inválida.");
        f37151c.put("INVALID_PAYER_ID", "Erro do sistema (ID de pagador inválido). Tente novamente mais tarde.");
        f37151c.put("INVALID_RESOURCE_ID", str3);
        f37151c.put("PAYEE_ACCOUNT_INVALID", "A conta do fornecedor não possui um e-mail confirmado.");
        f37151c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "O fornecedor não pode receber pagamentos agora.");
        f37151c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "A conta do fornecedor não possui um e-mail confirmado.");
        f37151c.put("PAYEE_ACCOUNT_RESTRICTED", "O fornecedor não pode receber pagamentos agora.");
        f37151c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Sua conta foi bloqueada ou fechada.");
        f37151c.put("PAYER_ACCOUNT_RESTRICTED", "Sua conta está restrita.");
        f37151c.put("PAYER_CANNOT_PAY", "Você não pode pagar esta transação com PayPal.");
        f37151c.put("PAYER_EMPTY_BILLING_ADDRESS", "Endereço de cobrança obrigatório para transações com cartão sem PayPal.");
        f37151c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Não é possível acessar as informações salvas do cartão.");
        f37151c.put("PAYMENT_APPROVAL_EXPIRED", "A aprovação do pagamento venceu.");
        f37151c.put("PAYMENT_EXPIRED", "O pagamento venceu.");
        f37151c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "O pagador não aprovou o pagamento.");
        f37151c.put("PAYMENT_REQUEST_ID_INVALID", "A solicitação do PayPal é inválida. Tente novamente mais tarde.");
        f37151c.put("PAYMENT_STATE_INVALID", "Solicitação inválida devido ao status atual do pagamento.");
        f37151c.put("PERMISSION_DENIED", "Sem permissão para a operação solicitada.");
        f37151c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "O reembolso solicitado excede o valor da transação original.");
        f37151c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transação muito antiga para reembolso.");
        f37151c.put("REQUIRED_SCOPE_MISSING", str3);
        f37151c.put("TOO_MANY_REAUTHORIZATIONS", "Nenhuma reautorização permitida para esta autorização.");
        f37151c.put("TRANSACTION_ALREADY_REFUNDED", "Esta transação já foi reembolsada.");
        f37151c.put("TRANSACTION_LIMIT_EXCEEDED", "O valor excede o limite permitido.");
        f37151c.put("TRANSACTION_REFUSED", "A transação foi recusada.");
        f37151c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "A transação foi recusada.");
        f37151c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "As preferências de perfil do vendedor são configuradas para negar automaticamente determinadas transações.");
        f37151c.put("UNKNOWN_ERROR", str3);
        f37151c.put("UNSUPPORTED_PAYEE_COUNTRY", "Não há suporte para o seu país.");
        f37151c.put("VALIDATION_ERROR", "As informações de pagamento são inválidas. Corrija e envie novamente.");
        f37151c.put("ORDER_ALREADY_COMPLETED", "O pedido já foi anulado, venceu ou foi concluído.");
        f37151c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Você atingiu o número máximo de autorizações para o pedido.");
        f37151c.put("ORDER_VOIDED", "O pedido foi anulado.");
        f37151c.put("ORDER_CANNOT_BE_VOIDED", "O status do pedido não permite anulação.");
        f37151c.put("INVALID_EXPERIENCE_PROFILE_ID", str3);
        f37151c.put("UNAUTHORIZED_PAYMENT", "O vendedor não aceita pagamentos deste tipo.");
        f37151c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Moeda sem suporte para o tipo de cartão.");
        f37151c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de cartão não suportado.");
        f37151c.put("ADDRESS_ADDITION_ERROR", "Ocorreu um erro ao adicionar o endereço de entrega na conta do PayPal.");
        f37151c.put("DUPLICATE_TRANSACTION", "Transação duplicada.");
        f37151c.put("INVALID_SHIPPING_ADDRESS", "O endereço de entrega informado não é válido.");
        f37151c.put("PAYMENT_CREATION_ERROR", "Erro ao fazer este pagamento. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Erro ao fazer este pagamento - seu cartão venceu. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Erro ao fazer este pagamento - obrigatório confirmação instantânea, como com cartão de crédito. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Erro ao fazer este pagamento - cartão precisa ser confirmado. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Erro ao fazer este pagamento - este aplicativo exige que a conta inclua um número de telefone. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Erro ao fazer este pagamento - meio de pagamento válido obrigatório, como bando ou cartão. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Erro ao fazer este pagamento - seu saldo está negativo. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Erro ao fazer este pagamento - você atingiu seu limite de envio. Visite o site do PayPal para consultar sua conta.");
        f37151c.put("AUTH_RC_RISK_FAILURE", "Recusado por regra de risco.");
        f37151c.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente não autorizado.");
        f37151c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente não autorizado.");
        f37151c.put("invalid_user", "Nome de usuário/senha incorreto. Tente novamente.");
        f37151c.put("locked_user", "Sua conta do PayPal foi temporariamente bloqueada. Tente novamente mais tarde ou acesse www.paypal.com para desbloquear sua conta do PayPal na hora.");
        f37151c.put("max_attempts_exceeded", "Máximo de tentativas de acesso excedido. Tente novamente mais tarde.");
        f37151c.put("invalid_request", "Ocorreu um erro.");
        String str15 = "Solicitação não autorizada.";
        f37151c.put("unauthorized_client", str15);
        f37151c.put("access_denied", str15);
        f37151c.put("unsupported_response_type", "Ocorreu um erro.");
        f37151c.put("invalid_scope", str15);
        f37151c.put("server_error", str3);
        f37151c.put("temporarily_unavailable", str3);
        f37151c.put("stepup_required", "Você não pode acessar sua conta no momento. Tente novamente mais tarde ou acesse www.paypal.com para solucionar questões de segurança relacionadas à sua conta do PayPal.");
        f37151c.put("account_locked_generate_challenge_limit_exceeded", "Máximo de tentativas de acesso excedido. Tente novamente mais tarde ou entre em contato com o PayPal para obter ajuda.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "pt_BR";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37150b.containsKey(sb2) ? f37150b.get(sb2) : f37149a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37151c.get(str);
    }
}
