package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.Ec */
public final class C11721Ec implements C11857oc {

    /* renamed from: a */
    private static final Map f36656a = new HashMap();

    /* renamed from: b */
    private static final Map f36657b = new HashMap();

    /* renamed from: c */
    private static final Map f36658c = new HashMap();

    public C11721Ec() {
        f36656a.put(C11761Rb.AGREE_AND_PAY, "Godta og betal");
        f36656a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "og andre");
        f36656a.put(C11761Rb.AUTHENTICATING, "Godkjenner");
        f36656a.put(C11761Rb.BACK_BUTTON, "Tilbake");
        f36656a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Reserve");
        f36656a.put(C11761Rb.CANCEL, "Avbryt");
        f36656a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f36656a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f36656a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f36656a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f36656a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f36656a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f36656a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f36656a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f36656a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f36656a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f36656a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f36656a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f36656a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f36656a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f36656a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f36656a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f36656a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Endre betalingsmetode");
        f36656a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Brukskonto");
        f36656a.put(C11761Rb.CHECKING_DEVICE, "Kontrollerer denne enheten …");
        f36656a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Fjern kortopplysningene");
        f36656a.put(C11761Rb.CONFIRM, "Bekreft");
        f36656a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker på at du vil fjerne kortopplysningene dine?");
        f36656a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Belast kortet");
        f36656a.put(C11761Rb.CONFIRM_LOG_OUT, "Er du sikker på at du vil logge av PayPal?");
        f36656a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Betal");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Godta");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Opprettelsesdato for kontoen");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fødselsdato");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadresse");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullt navn");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kjønn");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Språk");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Norsk, Norge");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidssone");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Del følgende: %s.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Bruk sømløs betaling.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s ber om at du:");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Del <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktiver visning av finansieringskilder slik at du kan velge en.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Tillater at de legger til og administrerer et fordelskort i PayPal-lommeboken din.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Godtar %1$s sine <a href='%2$s'>retningslinjer for personvern</a> og <a href='%3$s'>brukeravtale</a>.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        f36656a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Godta");
        f36656a.put(C11761Rb.EMAIL, "E-postadresse");
        f36656a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Eksempeldata");
        f36656a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f36656a.put(C11761Rb.EXPIRES_ON_DATE, "Utløper");
        f36656a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingsmetodene dine som er tilgjengelige for bruk.</p>");
        f36656a.put(C11761Rb.FORGOT_PASSWORD, "Har du glemt passordet?");
        f36656a.put(C11761Rb.FROM_ACCOUNT, "Fra");
        f36656a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du finansiere fremtidige betalinger til %1$s er?");
        f36656a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger for denne forhandleren.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        f36656a.put(C11761Rb.INTERNAL_ERROR, "Intern feil");
        f36656a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved å klikke på knappen nedenfor, godtar jeg vilkårene i <a href='%1$s'>PayPals brukeravtale</a> og jeg erklærer samtidig at jeg overholder japanske lover og forskrifter, herunder sanksjonsbestemmelser om betalinger til Nord-Korea og Iran, i tråd med japansk <a href='%2$s'>lovgivning om handel med utenlandske produkter og valuta</a>, for å fullføre transaksjonen.</p>");
        f36656a.put(C11761Rb.LOG_IN, "Logg på");
        String str = "Logg på med PayPal";
        f36656a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f36656a.put(C11761Rb.LOG_OUT_BUTTON, "Logg ut");
        f36656a.put(C11761Rb.LOG_OUT, "Logg ut");
        f36656a.put(C11761Rb.OK, "OK");
        f36656a.put(C11761Rb.PASSWORD, "Passord");
        f36656a.put(C11761Rb.PAY_AFTER_DELIVERY, "Betal etter levering");
        f36656a.put(C11761Rb.PAY_WITH, "Betal med");
        f36656a.put(C11761Rb.PAY_WITH_CARD, "Betal med kort");
        f36656a.put(C11761Rb.PAYPAL_BALANCE, "PayPal-saldo");
        f36656a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f36656a.put(C11761Rb.PHONE, "Telefonnummer");
        f36656a.put(C11761Rb.PIN, "PIN-kode");
        f36656a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Foretrukket betalingsmetode");
        f36656a.put(C11761Rb.PRIVACY, "PayPal beskytter <a href='%s'>personvern</a>-opplysningene dine og den økonomiske informasjonen din.");
        f36656a.put(C11761Rb.PROCESSING, "Behandler");
        f36656a.put(C11761Rb.REMEMBER_CARD, "Husk kortet");
        f36656a.put(C11761Rb.REQUEST_MONEY, "Pengeforespørsel");
        f36656a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f36656a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparekonto");
        f36656a.put(C11761Rb.SEND_MONEY, "Betal/overfør");
        f36656a.put(C11761Rb.SERVER_PROBLEM, "Det var et kommunikasjonsproblem med PayPal-serverne. Prøv på nytt.");
        f36656a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Logg deg på PayPal på nytt.");
        f36656a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Økten er utløpt");
        f36656a.put(C11761Rb.SHIPPING_ADDRESS, "Leveringsadresse");
        f36656a.put(C11761Rb.SIGN_UP, "Ny på PayPal? Opprett konto");
        f36656a.put(C11761Rb.STAY_LOGGED_IN, "Forbli pålogget");
        f36656a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Systemfeil (%s). Prøv på nytt senere.");
        f36656a.put(C11761Rb.TRY_AGAIN, "Prøv på nytt");
        f36656a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer.");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Sikkerhetskode");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Send en tekstmelding til telefonen din. Den 6-sifrede koden du mottar, er gyldig i 5 minutter.");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sender meldingen");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Oppgi den 6-sifrede sikkerhetskoden");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ditt mobilnummer");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Send melding");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send meldingen på nytt");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer. Gå til PayPals nettsted for å aktivere sikkerhetsnøkkelen din.");
        f36656a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Betaling fra denne enheten er ikke tillatt.");
        f36656a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Uautorisert enhet");
        f36656a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalinger til denne forhandleren er ikke tillatt (ugyldig bruker-id).");
        f36656a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig forhandler");
        f36656a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Det oppsto et problem ved behandlingen av betalingen. Prøv på nytt.");
        f36656a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Ukjent betalingsmetode");
        f36656a.put(C11761Rb.WE_ARE_SORRY, "Vi beklager");
        f36656a.put(C11761Rb.YOUR_ORDER, "Din bestilling");
        f36656a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Denne enheten kan ikke kommunisere med PayPal fordi androidversjonen er for gammel. Oppgrader til en nyere androidversjon, eller forsøk med en nyere enhet.");
        f36656a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Vil du fjerne kortet?");
        f36656a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Godkjenningen mislyktes");
        f36656a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Tilkobling mislykket");
        f36656a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Pålogging mislyktes");
        f36656a.put(C11761Rb.LOGIN_WITH_EMAIL, "Logg på med passord");
        f36656a.put(C11761Rb.LOGIN_WITH_PHONE, "Logg på med PIN");
        f36656a.put(C11761Rb.ONE_MOMENT, "Et øyeblikk …");
        f36656a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Betaling mislyktes");
        f36656a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Skann");
        f36656a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Feil sikkerhetskode. Prøv på nytt.");
        f36656a.put(C11761Rb.VIA_LABEL, "via");
        String str2 = "Systemfeil. Prøv på nytt senere.";
        f36656a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.";
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.";
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.";
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del informasjon med dem om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f36657b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        String str6 = "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.";
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f36657b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forhåndsgodkjenn fremtidige betalinger fra PayPal-kontoen din uten å logge på PayPal hver gang. <a href='%1$s'>Se ytterligere vilkår</a>, inkludert betalingsmetoder og hvordan du kan avbryte fremtidige betalinger.");
        String str7 = "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.";
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f36657b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.";
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f36657b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>";
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>";
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f36657b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Din standard betalingsmetode (PayPal-saldo, tilknyttet bankkonto eller betalingskort, i denne rekkefølgen) brukes til å betale for PayPal-kjøp. Vær oppmerksom på at hvis den standard betalingsmetoden din ikke har nok penger til å dekke kjøpet, kan banken eller kortleverandøren belaste deg et gebyr.</p><p>For å avbryte denne avtalen må du logge på PayPal-kontoen din og gå til <strong>Profil</strong>, så klikker du på <strong>Mine innstillinger</strong> og <strong>Endre</strong> ved siden av ‘Logg på med PayPal’.</p>");
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger hos denne forhandleren.</p><p>Hvis du vil avslutte denne avtalen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        String str11 = "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>";
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se «Forhåndsgodkjente betalinger»-delen i <a href='%s'>PayPals brukeravtale</a> for å få mer informasjon.</p>");
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f36657b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Vi forsøker først å betale med PayPal-saldoen din. Hvis det ikke er nok penger på den, forsøker vi å bruke bankkontoen din, PayPal Credit, betalingskort og/eller eCheck, i den viste rekkefølgen.</p><p>Hvis du vil avbryte denne avtalen, går du til www.paypal.com <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Det kan være nødvendig med en liten betalingsgodkjenning for å kontrollere at PayPal-kontoen din kan belastes i fremtiden. Godkjenningen blir avbrutt, og du belastes ikke.</p>");
        f36657b.put("LOG_IN_TO_PAYPAL|AU", str);
        f36657b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>";
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>";
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>";
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        String str15 = "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>";
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str15);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren. Hvis du fortsatt bruker den tidligere versjonen av nettstedet, går du til <strong>Min profil</strong>, velger <strong>Mine kontoinnstillinger</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Profil</strong>-innstillingene, <strong>Logg på med PayPal</strong> og fjerner denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.it, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str15);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.ru, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str15);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.tr, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p>");
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f36657b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f36658c.put("AMOUNT_MISMATCH", "Totalbeløpet for varene i handlekurven samsvarer ikke med kjøpesummen.");
        f36658c.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkjenningen er allerede fullført.");
        f36658c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkjenningen er i et stadium som ikke kan bli annullert.");
        f36658c.put("AUTHORIZATION_EXPIRED", "Godkjenning utløpt.");
        f36658c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Den forespurte godkjennings-IDen finnes ikke.");
        f36658c.put("AUTHORIZATION_VOIDED", "Godkjenningen din er annullert.");
        f36658c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Kan bare godkjenne den opprinnelige godkjenningen, ikke en ny godkjenning.");
        f36658c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ny godkjenning er ikke tillatt innenfor prøveperioden.");
        f36658c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        f36658c.put("CARD_TOKEN_PAYER_MISMATCH", "Får ikke tilgang til lagret kortinformasjonen.");
        f36658c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortopplysningene er ugyldige. Vi ber deg korrigere og sende inn på nytt.");
        f36658c.put("CREDIT_CARD_REFUSED", "Kortet ble avvist.");
        f36658c.put("CURRENCY_MISMATCH", "Valuta for innhentingen må være lik valutaen for godkjenning.");
        f36658c.put("CURRENCY_NOT_ALLOWED", "Denne valutaen støttes for øyeblikket ikke av PayPal.");
        f36658c.put("DATA_RETRIEVAL", str2);
        f36658c.put("DUPLICATE_REQUEST_ID", str2);
        f36658c.put("EXPIRED_CREDIT_CARD", "Kortet er utløpt");
        f36658c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informasjonen for dette kortet er ikke lenger registrert.\nVennligst send på nytt.");
        f36658c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funksjonen støttes ikke for denne forhandleren.");
        f36658c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaksjonen er allerede delvis refundert.");
        f36658c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Øyeblikkelig betaling støttes ikke for den forespurte tjenesten.");
        f36658c.put("INSTRUMENT_DECLINED", "Den betalingsmetoden du valgte ble ikke godtatt. Velg en annen betalingsmetode.");
        f36658c.put("INSUFFICIENT_FUNDS", "Kjøperen kan ikke betale – ikke nok penger.");
        f36658c.put("INTERNAL_SERVICE_ERROR", str2);
        f36658c.put("INVALID_ACCOUNT_NUMBER", "Det kontonummeret finnes ikke.");
        f36658c.put("INVALID_ARGUMENT", "Transaksjon avvist på grunn av et ugyldig parameter");
        f36658c.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombinasjon for poststed/land/postnummerkombinasjon.");
        f36658c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne transaksjonen kan ikke behandles på grunn av en ugyldig systeminnretningskonfigurasjon.");
        f36658c.put("INVALID_PAYER_ID", "Systemfeil (ugyldig betaler-id). Prøv på nytt senere.");
        f36658c.put("INVALID_RESOURCE_ID", str2);
        f36658c.put("PAYEE_ACCOUNT_INVALID", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        f36658c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        f36658c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        f36658c.put("PAYEE_ACCOUNT_RESTRICTED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        f36658c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Kontoen din er låst eller avsluttet.");
        f36658c.put("PAYER_ACCOUNT_RESTRICTED", "Kontoen din er begrenset.");
        f36658c.put("PAYER_CANNOT_PAY", "Du kan ikke betale for denne transaksjonen med PayPal.");
        f36658c.put("PAYER_EMPTY_BILLING_ADDRESS", "Det er nødvendig med en faktureringsadresse ved betalingskorttransaksjoner utenfor PayPal.");
        f36658c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Får ikke tilgang til lagret kortinformasjonen.");
        f36658c.put("PAYMENT_APPROVAL_EXPIRED", "Betalingsgodkjenningen er utløpt.");
        f36658c.put("PAYMENT_EXPIRED", "Betalingen er utløpt.");
        f36658c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godtatt betalingen.");
        f36658c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-forespørselen er ugyldig. Prøv på nytt senere.");
        f36658c.put("PAYMENT_STATE_INVALID", "Denne forespørselen er ugyldig på grunn av gjeldende status for betalingen.");
        f36658c.put("PERMISSION_DENIED", "Ingen tillatelse til den forespurte operasjonen.");
        f36658c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den forespurte refusjonen overskrider beløpet for den opprinnelige transaksjonen.");
        f36658c.put("REFUND_TIME_LIMIT_EXCEEDED", "Denne transaksjonen er for gammel til at den kan refunderes.");
        f36658c.put("REQUIRED_SCOPE_MISSING", str2);
        f36658c.put("TOO_MANY_REAUTHORIZATIONS", "Ingen flere nye godkjenninger er tillatt for denne godkjenningen.");
        f36658c.put("TRANSACTION_ALREADY_REFUNDED", "Denne transaksjonen er allerede refundert.");
        f36658c.put("TRANSACTION_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        f36658c.put("TRANSACTION_REFUSED", "Transaksjonen ble avvist.");
        f36658c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaksjonen ble avvist.");
        f36658c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Forhandlerprofilen er innstilt til å automatisk tilbakevise visse transaksjoner.");
        f36658c.put("UNKNOWN_ERROR", str2);
        f36658c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet støttes ikke.");
        f36658c.put("VALIDATION_ERROR", "Betalingsinformasjonen er ugyldig. Vi ber deg korrigere og sende inn på nytt.");
        f36658c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede annullert, utløpt eller fullført.");
        f36658c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maksimalt antall tillatte godkjenninger for bestillingen er nådd.");
        f36658c.put("ORDER_VOIDED", "Bestillingen er blitt annullert.");
        f36658c.put("ORDER_CANNOT_BE_VOIDED", "Det er ikke mulig å annullere bestillingen i denne delen av prosessen.");
        f36658c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f36658c.put("UNAUTHORIZED_PAYMENT", "Forhandleren godtar ikke betalinger av denne typen.");
        f36658c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta ikke støttet for korttypen.");
        f36658c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen støttes ikke.");
        f36658c.put("ADDRESS_ADDITION_ERROR", "Det oppstod et problem i løpet av prosessen med å legge til en forsendelsesadresse i PayPal-kontoen.");
        f36658c.put("DUPLICATE_TRANSACTION", "Duplikattransaksjon.");
        f36658c.put("INVALID_SHIPPING_ADDRESS", "Den oppgitte leveringsadressen er ikke gyldig.");
        f36658c.put("PAYMENT_CREATION_ERROR", "Det oppsto et problem med opprettelsen av denne betalingen. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet ditt er utløpt. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det oppsto et problem med opprettelsen av denne betalingen – direktebetaling kreves, f.eks. med et kredittkort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet må bekreftes. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det oppsto et problem med opprettelsen av denne betalingen – denne appen krever at kontoen din inneholder et telefonnummer. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det oppsto et problem med opprettelsen av denne betalingen – kontoen må ha en gyldig finansieringskilde, f.eks. en bankkonto eller et betalingskort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det oppsto et problem med opprettelsen av denne betalingen – saldoen din er i minus. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det oppsto et problem med opprettelsen av denne betalingen – sendegrensen din er nådd. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        f36658c.put("AUTH_RC_RISK_FAILURE", "Avvist grunnet risiko.");
        f36658c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkjent.");
        f36658c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkjent.");
        f36658c.put("invalid_user", "Feil brukernavn/passord. Prøv på nytt.");
        f36658c.put("locked_user", "PayPal-kontoen din er midlertidig sperret. Prøv på nytt senere, eller gå til www.paypal.com for å låse opp PayPal-kontoen din med en gang.");
        f36658c.put("max_attempts_exceeded", "For mange mislykkede påloggingsforsøk. Prøv på nytt senere.");
        f36658c.put("invalid_request", "Det har oppstått en feil.");
        f36658c.put("unauthorized_client", "Ikke godkjent forespørsel.");
        f36658c.put("access_denied", "Ikke godkjent forespørsel.");
        f36658c.put("unsupported_response_type", "Det har oppstått en feil.");
        f36658c.put("invalid_scope", "Ikke godkjent forespørsel.");
        f36658c.put("server_error", str2);
        f36658c.put("temporarily_unavailable", str2);
        f36658c.put("stepup_required", "Det er ikke mulig å logge på akkurat nå. Prøv på nytt senere, eller gå til www.paypal.com for å løse eventuelle sikkerhetsproblemer med kontoen din.");
        f36658c.put("account_locked_generate_challenge_limit_exceeded", "For mange påloggingsforsøk. Prøv på nytt senere, eller ta kontakt med PayPal for å få hjelp.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "nb";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f36657b.containsKey(sb2) ? f36657b.get(sb2) : f36656a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f36658c.get(str);
    }
}
