package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.Gc */
public final class C11729Gc implements C11857oc {

    /* renamed from: a */
    private static final Map f36681a = new HashMap();

    /* renamed from: b */
    private static final Map f36682b = new HashMap();

    /* renamed from: c */
    private static final Map f36683c = new HashMap();

    public C11729Gc() {
        f36681a.put(C11761Rb.AGREE_AND_PAY, "Zgadzam się i chcę zapłacić");
        f36681a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "i inne");
        f36681a.put(C11761Rb.AUTHENTICATING, "Uwierzytelnianie");
        f36681a.put(C11761Rb.BACK_BUTTON, "Wstecz");
        f36681a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Rezerwowe");
        f36681a.put(C11761Rb.CANCEL, "Anuluj");
        f36681a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f36681a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f36681a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f36681a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f36681a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f36681a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f36681a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f36681a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f36681a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f36681a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f36681a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f36681a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f36681a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f36681a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f36681a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f36681a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f36681a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Zmień formę płatności");
        f36681a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Rozliczeniowy");
        f36681a.put(C11761Rb.CHECKING_DEVICE, "Sprawdzanie urządzenia…");
        f36681a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Wyczyść informacje o karcie");
        f36681a.put(C11761Rb.CONFIRM, "Potwierdź");
        f36681a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Na pewno chcesz wyczyścić informacje o karcie?");
        f36681a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Obciąż kartę");
        f36681a.put(C11761Rb.CONFIRM_LOG_OUT, "Na pewno chcesz się wylogować z serwisu PayPal?");
        f36681a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Zapłać");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Zgadzam się");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data założenia konta");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Status konta");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Typ rachunku");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adres");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Grupa wiekowa");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data urodzenia");
        String str = "Adres e-mail";
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, str);
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Pełne imię i nazwisko");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Płeć");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Język");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Lokalizacja");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Strefa czasowa");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Udostępnij następujące informacje: %s.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Korzystaj z ekspresowej realizacji transakcji.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s prosi o:");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Udostępnij <a href='%1$s'>formy płatności</a> powiązane z Twoim kontem PayPal.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Włącz wyświetlanie opcji finansowania płatności, aby móc dokonać wyboru.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "zgodę na dodawanie kart lojalnościowych i zarządzanie nimi w Twoim portfelu PayPal.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "akceptację warunków określonych w dokumentach %1$s: <a href='%2$s'>zasadach zachowania poufności</a> i <a href='%3$s'>umowie z użytkownikiem</a>");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Wyraź zgodę na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Wyraź zgodę na <a href='%1$s'>wysłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        f36681a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Zgoda");
        f36681a.put(C11761Rb.EMAIL, str);
        f36681a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Dane próbne");
        f36681a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Centrum testowe");
        f36681a.put(C11761Rb.EXPIRES_ON_DATE, "Wygasa");
        f36681a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje formy płatności są dostępne do użytku.</p>");
        f36681a.put(C11761Rb.FORGOT_PASSWORD, "Nie pamiętasz hasła?");
        f36681a.put(C11761Rb.FROM_ACCOUNT, "Od");
        f36681a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Jak chcesz finansować przyszłe płatności na rzecz %1$s?");
        f36681a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
        f36681a.put(C11761Rb.INTERNAL_ERROR, "Błąd wewnętrzny");
        f36681a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Klikając przycisk poniżej, akceptuję postanowienia <a href='%1$s'>Umowy z Użytkownikiem usługi PayPal</a> i oświadczam, że przestrzegam przepisów prawa japońskiego, w tym przepisów dotyczących zakazu dokonywania płatności do Korei Północnej i Iranu zgodnie z <a href='%2$s'>ustawą Foreign Exchange and Foreign Trade Act (Ustawa o wymianie walut i handlu zagranicznym)</a> na potrzeby realizacji tej transakcji.</p>");
        f36681a.put(C11761Rb.LOG_IN, "Zaloguj się");
        String str2 = "Zaloguj się z PayPal";
        f36681a.put(C11761Rb.LOG_IN_TO_PAYPAL, str2);
        f36681a.put(C11761Rb.LOG_OUT_BUTTON, "Wyloguj się");
        f36681a.put(C11761Rb.LOG_OUT, "Wyloguj się");
        f36681a.put(C11761Rb.OK, "OK");
        f36681a.put(C11761Rb.PASSWORD, "Hasło");
        f36681a.put(C11761Rb.PAY_AFTER_DELIVERY, "Zapłać po dostawie");
        f36681a.put(C11761Rb.PAY_WITH, "Zapłać za pomocą");
        f36681a.put(C11761Rb.PAY_WITH_CARD, "Zapłać kartą");
        f36681a.put(C11761Rb.PAYPAL_BALANCE, "Saldo PayPal");
        f36681a.put(C11761Rb.PAYPAL_CREDIT, "Kredyt PayPal");
        f36681a.put(C11761Rb.PHONE, "Telefon");
        f36681a.put(C11761Rb.PIN, "PIN");
        f36681a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Preferowana forma płatności");
        f36681a.put(C11761Rb.PRIVACY, "Serwis PayPal chroni Twoją <a href='%s'>prywatność</a> i informacje finansowe.");
        f36681a.put(C11761Rb.PROCESSING, "Przetwarzanie");
        f36681a.put(C11761Rb.REMEMBER_CARD, "Zapamiętaj kartę");
        f36681a.put(C11761Rb.REQUEST_MONEY, "Zażądaj zapłaty");
        f36681a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        f36681a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Oszczędnościowy");
        f36681a.put(C11761Rb.SEND_MONEY, "Wyślij pieniądze");
        f36681a.put(C11761Rb.SERVER_PROBLEM, "Wystąpił problem z nawiązaniem połączenia z serwerami PayPal. Spróbuj ponownie.");
        f36681a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Zaloguj się ponownie do systemu PayPal.");
        f36681a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sesja wygasła");
        f36681a.put(C11761Rb.SHIPPING_ADDRESS, "Adres wysyłkowy");
        f36681a.put(C11761Rb.SIGN_UP, "Nowy użytkownik? Załóż konto");
        f36681a.put(C11761Rb.STAY_LOGGED_IN, "Nie wylogowuj się");
        f36681a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Błąd systemu (%s). Spróbuj ponownie później.");
        f36681a.put(C11761Rb.TRY_AGAIN, "Spróbuj ponownie");
        f36681a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe.");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Kod bezpieczeństwa");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Wyślij wiadomość tekstową na swój telefon. Otrzymany 6-cyfrowy kod będzie ważny przez 5 minut.");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Wysyłanie wiadomości tekstowej");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Podaj 6-cyfrowy kod zabezpieczający");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Twój numer telefonu komórkowego");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Wyślij wiadomość tekstową");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Wyślij wiadomość tekstową ponownie");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe. Przejdź do witryny PayPal i uaktywnij klucz bezpieczeństwa.");
        f36681a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Dokonywanie płatności z tego urządzenia jest niedozwolone.");
        f36681a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Nieautoryzowane urządzenie");
        f36681a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Płatności na rzecz tego handlowca nie są dozwolone (nieprawidłowy identyfikator klienta).");
        f36681a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Nieprawidłowy handlowiec");
        f36681a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Wystąpił problem z przetworzeniem płatności. Spróbuj ponownie.");
        f36681a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Nierozpoznane źródło");
        f36681a.put(C11761Rb.WE_ARE_SORRY, "Przepraszamy.");
        f36681a.put(C11761Rb.YOUR_ORDER, "Twoje zamówienie");
        f36681a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Urządzenie nie może skomunikować się z PayPal, ponieważ ta wersja systemu Android jest zbyt stara. Zaktualizuj system Android lub skorzystaj z nowszego urządzenia.");
        f36681a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Usunąć kartę?");
        f36681a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Udzielenie zgody nie powiodło się");
        f36681a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Próba połączenia nieudana");
        f36681a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Logowanie nie powiodło się");
        f36681a.put(C11761Rb.LOGIN_WITH_EMAIL, "Zaloguj się za pomocą hasła");
        f36681a.put(C11761Rb.LOGIN_WITH_PHONE, "Zaloguj się przy użyciu kodu PIN");
        f36681a.put(C11761Rb.ONE_MOMENT, "Chwileczkę…");
        f36681a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Płatność nie powiodła się");
        f36681a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Skanuj");
        f36681a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Nieprawidłowy kod bezpieczeństwa. Spróbuj ponownie.");
        f36681a.put(C11761Rb.VIA_LABEL, "przez");
        String str3 = "Błąd systemu. Spróbuj ponownie później.";
        f36681a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str3);
        String str4 = "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.";
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str4);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str4);
        String str5 = "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.";
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str4);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str4);
        String str6 = "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.";
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str6);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", str4);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str4);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str6);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str4);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str6);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str5);
        f36682b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str5);
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
        String str7 = "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.";
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str7);
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str7);
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str7);
        f36682b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Wstępnie zatwierdzaj dokonywane z Twojego konta PayPal płatności z datą przyszłą bez konieczności każdorazowego logowania się w systemie PayPal. <a href='%1$s'>Zobacz dodatkowe warunki</a> dotyczące m.in. form płatności i sposobu anulowania płatności z datą przyszłą.");
        String str8 = "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.";
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str8);
        f36682b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str8);
        String str9 = "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.";
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str9);
        f36682b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str9);
        String str10 = "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>";
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str10);
        f36682b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str10);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności (w kolejności: konto PayPal, powiązany rachunek bankowy, karta debetowa lub kredytowa). Pamiętaj, że jeśli w ramach swojej domyślnej formy płatności nie masz wystarczających środków do dokonania płatności za zakupy, Twój bank lub wystawca karty może obciążyć Cię opłatą.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong>, <strong>Moje ustawienia</strong> i opcję <strong>Zmień</strong> dostępną obok pozycji Zaloguj się z PayPal.</p>");
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
        String str11 = "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>";
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f36682b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>W celu realizacji zakupu system PayPal w pierwszej kolejności korzysta ze środków na Twoim koncie PayPal. Jeśli środki te są niewystarczające, wykorzystane zostaną kolejno: rachunek bankowy, PayPal Credit, karta debetowa, karta kredytowa lub czek elektroniczny.</p><p>Aby anulować tę umowę, na stronie www.paypal.pl wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Autoryzacja płatności o mniejszej wartości może być wymagana w celu sprawdzenia, czy konto PayPal może być obciążane. Taka autoryzacja zostanie jednak unieważniona, a pobranie opłaty anulowane.</p>");
        f36682b.put("LOG_IN_TO_PAYPAL|AU", str2);
        f36682b.put("LOG_IN_TO_PAYPAL|GB", str2);
        String str12 = "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>";
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>";
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>";
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Centrum bezpieczeństwa</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca. Jeśli korzystasz z klasycznej strony internetowej, wybierz kolejno <strong>Mój profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.it, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.ru, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.com.tr, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p>");
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f36682b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f36683c.put("AMOUNT_MISMATCH", "Suma wszystkich pozycji w koszyku jest niezgodna z kwotą sprzedaży.");
        f36683c.put("AUTHORIZATION_ALREADY_COMPLETED", "Ta autoryzacja została już zakończona.");
        f36683c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autoryzacji w aktualnym stanie nie można unieważnić.");
        f36683c.put("AUTHORIZATION_EXPIRED", "Autoryzacja straciła ważność.");
        f36683c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Numer identyfikacyjny żądanej autoryzacji nie istnieje.");
        f36683c.put("AUTHORIZATION_VOIDED", "Autoryzacja została anulowana.");
        f36683c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Ponownej autoryzacji można dokonać tylko w ramach pierwotnej autoryzacji.");
        f36683c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ponowna autoryzacja nie jest dozwolona w okresie honorowania.");
        f36683c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
        f36683c.put("CARD_TOKEN_PAYER_MISMATCH", "Brak dostępu do zapisanych informacji o karcie.");
        f36683c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Dane karty są nieprawidłowe. Popraw je i prześlij ponownie.");
        f36683c.put("CREDIT_CARD_REFUSED", "Karta została odrzucona.");
        f36683c.put("CURRENCY_MISMATCH", "Waluta pobranych środków musi być jednakowa z walutą autoryzacji.");
        f36683c.put("CURRENCY_NOT_ALLOWED", "Twoja waluta nie jest aktualnie obsługiwana przez system PayPal.");
        f36683c.put("DATA_RETRIEVAL", str3);
        f36683c.put("DUPLICATE_REQUEST_ID", str3);
        f36683c.put("EXPIRED_CREDIT_CARD", "Karta wygasła");
        f36683c.put("EXPIRED_CREDIT_CARD_TOKEN", "W systemie nie ma już zapisanych informacji o tej karcie.\nPrześlij je ponownie.");
        f36683c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funkcja nie jest obsługiwana u tego handlowca.");
        f36683c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Ta transakcja została już częściowo zwrócona.");
        f36683c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Płatność natychmiastowa nie jest obsługiwana w wybranej opcji.");
        f36683c.put("INSTRUMENT_DECLINED", "Wybrana przez Ciebie forma płatności nie została zaakceptowana. Wybierz inną formę płatności.");
        f36683c.put("INSUFFICIENT_FUNDS", "Kupujący nie może zapłacić – niewystarczające środki.");
        f36683c.put("INTERNAL_SERVICE_ERROR", str3);
        f36683c.put("INVALID_ACCOUNT_NUMBER", "Ten numer rachunku nie istnieje.");
        f36683c.put("INVALID_ARGUMENT", "Transakcja odrzucona z powodu nieprawidłowego parametru");
        f36683c.put("INVALID_CITY_STATE_ZIP", "Nieprawidłowa kombinacja miasta/województwa/kodu pocztowego.");
        f36683c.put("INVALID_FACILITATOR_CONFIGURATION", "Nie można przetworzyć transakcji. Podana konfiguracja facylitatora jest nieprawidłowa.");
        f36683c.put("INVALID_PAYER_ID", "Błąd systemu (nieprawidłowy identyfikator płatnika). Spróbuj ponownie później.");
        f36683c.put("INVALID_RESOURCE_ID", str3);
        f36683c.put("PAYEE_ACCOUNT_INVALID", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
        f36683c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Ten dostawca nie może obecnie odbierać płatności.");
        f36683c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
        f36683c.put("PAYEE_ACCOUNT_RESTRICTED", "Ten dostawca nie może obecnie odbierać płatności.");
        f36683c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Twoje konto zostało zablokowane lub zamknięte.");
        f36683c.put("PAYER_ACCOUNT_RESTRICTED", "Dostęp do Twojego konta został ograniczony.");
        f36683c.put("PAYER_CANNOT_PAY", "Nie możesz zapłacić za tę transakcję z PayPal.");
        f36683c.put("PAYER_EMPTY_BILLING_ADDRESS", "W przypadku transakcji kartą kredytową poza systemem PayPal wymagany jest adres rozliczeniowy.");
        f36683c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Brak dostępu do zapisanych informacji o karcie.");
        f36683c.put("PAYMENT_APPROVAL_EXPIRED", "Zatwierdzenie płatności straciło ważność.");
        f36683c.put("PAYMENT_EXPIRED", "Płatność straciła ważność.");
        f36683c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Płatnik nie zatwierdził płatności.");
        f36683c.put("PAYMENT_REQUEST_ID_INVALID", "Identyfikator żądania PayPal jest nieprawidłowy. Spróbuj ponownie później.");
        f36683c.put("PAYMENT_STATE_INVALID", "Żądanie jest nieprawidłowe z uwagi na aktualny status płatności.");
        f36683c.put("PERMISSION_DENIED", "Brak uprawnień do wykonania żądanej operacji.");
        f36683c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Żądana kwota zwrotu pieniędzy przekracza kwotę pierwotnej transakcji.");
        f36683c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transakcja została dokonana zbyt dawno, aby dokonać zwrotu pieniędzy.");
        f36683c.put("REQUIRED_SCOPE_MISSING", str3);
        f36683c.put("TOO_MANY_REAUTHORIZATIONS", "Nie można dokonać więcej ponownych autoryzacji w ramach tej autoryzacji.");
        f36683c.put("TRANSACTION_ALREADY_REFUNDED", "Ta transakcja została już zwrócona.");
        f36683c.put("TRANSACTION_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
        f36683c.put("TRANSACTION_REFUSED", "Transakcja została odrzucona.");
        f36683c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transakcja została odrzucona.");
        f36683c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Preferencje w profilu handlowca ustawione są na automatyczne odrzucanie pewnych transakcji.");
        f36683c.put("UNKNOWN_ERROR", str3);
        f36683c.put("UNSUPPORTED_PAYEE_COUNTRY", "Twój kraj nie jest obsługiwany.");
        f36683c.put("VALIDATION_ERROR", "Informacje o płatności są nieprawidłowe. Popraw je i prześlij ponownie.");
        f36683c.put("ORDER_ALREADY_COMPLETED", "Zamówienie zostało już unieważnione, straciło ważność lub zostało zrealizowane.");
        f36683c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Osiągnięto limit dozwolonych autoryzacji w ramach tego zamówienia.");
        f36683c.put("ORDER_VOIDED", "Zamówienie zostało unieważnione.");
        f36683c.put("ORDER_CANNOT_BE_VOIDED", "Obecny status zamówienia uniemożliwia jego unieważnienie.");
        f36683c.put("INVALID_EXPERIENCE_PROFILE_ID", str3);
        f36683c.put("UNAUTHORIZED_PAYMENT", "Handlowiec nie akceptuje płatności tego typu.");
        f36683c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Waluta nie jest obsługiwana przez ten typ karty.");
        f36683c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Ten typ karty nie jest obsługiwany.");
        f36683c.put("ADDRESS_ADDITION_ERROR", "Podczas dodawania adresu wysyłkowego do konta PayPal wystąpił błąd.");
        f36683c.put("DUPLICATE_TRANSACTION", "Transakcja powielona.");
        f36683c.put("INVALID_SHIPPING_ADDRESS", "Podany adres wysyłkowy jest nieprawidłowy.");
        f36683c.put("PAYMENT_CREATION_ERROR", "Wystąpił problem z utworzeniem tej płatności. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Wystąpił problem z utworzeniem tej płatności – Twoja karta wygasła. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Wystąpił problem z utworzeniem tej płatności – wymagana jest płatność błyskawiczna (na przykład kartą kredytową). Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Wystąpił problem z utworzeniem tej płatności – karta musi zostać potwierdzona. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Wystąpił problem z utworzeniem tej płatności – ta aplikacja wymaga, aby na Twoim koncie podany został numer telefonu. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Wystąpił problem z utworzeniem tej płatności – konto wymaga podania ważnego źródła finansowania płatności, np. rachunku bankowego lub karty płatniczej. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Wystąpił problem z utworzeniem tej płatności – saldo konta jest ujemne. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Wystąpił problem z utworzeniem tej płatności – osiągnięto limit wysyłania. Sprawdź swoje konto w witrynie PayPal.");
        f36683c.put("AUTH_RC_RISK_FAILURE", "Odrzucono z uwagi na ryzyko.");
        f36683c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klient nieautoryzowany.");
        f36683c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klient nieautoryzowany.");
        f36683c.put("invalid_user", "Nieprawidłowa nazwa użytkownika / hasło. Spróbuj ponownie.");
        f36683c.put("locked_user", "Twoje konto PayPal zostało tymczasowo zablokowane. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odblokuj swoje konto PayPal.");
        f36683c.put("max_attempts_exceeded", "Zbyt wiele prób logowania zakończyło się niepowodzeniem. Spróbuj ponownie później.");
        f36683c.put("invalid_request", "Wystąpił błąd.");
        String str15 = "Żądanie nieautoryzowane.";
        f36683c.put("unauthorized_client", str15);
        f36683c.put("access_denied", str15);
        f36683c.put("unsupported_response_type", "Wystąpił błąd.");
        f36683c.put("invalid_scope", str15);
        f36683c.put("server_error", str3);
        f36683c.put("temporarily_unavailable", str3);
        f36683c.put("stepup_required", "W tej chwili nie możesz się zalogować. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odpowiedz na wątpliwości dotyczące bezpieczeństwa Twojego konta PayPal.");
        f36683c.put("account_locked_generate_challenge_limit_exceeded", "Zbyt wiele prób logowania. Spróbuj ponownie później lub skontaktuj się z PayPal, aby uzyskać pomoc.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "pl";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f36682b.containsKey(sb2) ? f36682b.get(sb2) : f36681a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f36683c.get(str);
    }
}
