package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.Ac */
public final class C11705Ac implements C11857oc {

    /* renamed from: a */
    private static final Map f36577a = new HashMap();

    /* renamed from: b */
    private static final Map f36578b = new HashMap();

    /* renamed from: c */
    private static final Map f36579c = new HashMap();

    public C11705Ac() {
        f36577a.put(C11761Rb.AGREE_AND_PAY, "同意して支払う");
        f36577a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "＋その他");
        f36577a.put(C11761Rb.AUTHENTICATING, "認証しています");
        f36577a.put(C11761Rb.BACK_BUTTON, "戻る");
        f36577a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "予備");
        f36577a.put(C11761Rb.CANCEL, "キャンセル");
        f36577a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f36577a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f36577a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f36577a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f36577a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f36577a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f36577a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f36577a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f36577a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f36577a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f36577a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f36577a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f36577a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f36577a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f36577a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f36577a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f36577a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "支払方法の変更");
        f36577a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "当座預金");
        f36577a.put(C11761Rb.CHECKING_DEVICE, "この端末をチェック中…");
        f36577a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "カード情報を消去");
        f36577a.put(C11761Rb.CONFIRM, "確認");
        f36577a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "カード情報を消去してよろしいですか?");
        f36577a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "カードの支払い");
        f36577a.put(C11761Rb.CONFIRM_LOG_OUT, "PayPalからログアウトしてよろしいですか?");
        f36577a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "支払う");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "同意する");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "アカウント作成日");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "アカウントステータス");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "口座の種類");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "住所");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "年齢範囲");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "誕生日");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "メールアドレス");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "氏名");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "性別");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "言語");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "国・地域");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "電話番号");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "タイムゾーン");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "次の情報を共有する: %s。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "シームレスな支払い手続きを使う。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%sをご利用いただくための条件をご確認ください。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "PayPalアカウントに登録された<a href='%1$s'>支払方法</a>を共有します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "支払方法を選択できるように資金源を表示できるようにします。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "今後%2$sでの買い物でPayPalで支払いをした場合の<a href='%1$s'>請求を承認します</a>。お客さまは、%3$sから請求された代金を全額支払うことをPayPalに指示します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "PayPalウォレットでそれぞれのポイントカードを追加および管理することを許可します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "%1$sの<a href='%2$s'>プライバシーポリシー</a>と<a href='%3$s'>ユーザー規約</a>に同意します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "お客さまが同意を取り下げるまで、彼らがお客さまの代理として<a href='%1$s'>請求</a>を行うことを許可します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "お客さまが同意を取り下げるまで、彼らがお客さまの代理として<a href='%1$s'>支払い</a>を行うことを許可します。");
        f36577a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "同意");
        f36577a.put(C11761Rb.EMAIL, "メール");
        f36577a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "モックデータ");
        f36577a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f36577a.put(C11761Rb.EXPIRES_ON_DATE, "有効期限");
        f36577a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>支払方法</strong></h1><p>PayPalが共有するのはお客さまのどの支払方法が使用可能なのかのみです。</p>");
        f36577a.put(C11761Rb.FORGOT_PASSWORD, "パスワードをお忘れですか？");
        f36577a.put(C11761Rb.FROM_ACCOUNT, "入金元 :");
        f36577a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "次回からの%1$sへの支払方法を教えてください。");
        f36577a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のこのお店でのPayPal支払いには、初期設定の資金源が使用されます。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p><p><a href='%s'>PayPalユーザー規約</a>の「定期支払い」の項が適用されます。</p><p>PayPalアカウントで支払いを処理できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p>");
        f36577a.put(C11761Rb.INTERNAL_ERROR, "内部エラー");
        f36577a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>以下のボタンをクリックすることにより、<a href='%1$s'>PayPalのユーザー規約</a>に同意し、この支払いが<a href='%2$s'>外国為替及び外国貿易法に基づく北朝鮮やイランへの資金使途規制</a>を含む日本の法令を遵守していることを宣言したうえで、この支払いを実行します。</p>");
        f36577a.put(C11761Rb.LOG_IN, "ログイン");
        String str = "PayPalでログイン";
        f36577a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f36577a.put(C11761Rb.LOG_OUT_BUTTON, "ログアウト");
        f36577a.put(C11761Rb.LOG_OUT, "ログアウト");
        f36577a.put(C11761Rb.OK, "OK");
        f36577a.put(C11761Rb.PASSWORD, "パスワード");
        f36577a.put(C11761Rb.PAY_AFTER_DELIVERY, "配達後の支払い");
        f36577a.put(C11761Rb.PAY_WITH, "支払う:");
        f36577a.put(C11761Rb.PAY_WITH_CARD, "カードで支払う");
        f36577a.put(C11761Rb.PAYPAL_BALANCE, "PayPal残高");
        f36577a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f36577a.put(C11761Rb.PHONE, "電話番号");
        f36577a.put(C11761Rb.PIN, "暗証番号");
        f36577a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "優先支払方法");
        f36577a.put(C11761Rb.PRIVACY, "PayPalはお客さまの<a href='%s'>プライバシー</a>と財務情報を保護します。");
        f36577a.put(C11761Rb.PROCESSING, "処理中");
        f36577a.put(C11761Rb.REMEMBER_CARD, "カード情報を保存する");
        f36577a.put(C11761Rb.REQUEST_MONEY, "請求");
        f36577a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.comでログインし、[<strong>個人設定</strong>]の[<strong>PayPalでログイン</strong>]オプションからこのお店を削除します。</p><p>パートナー会社側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36577a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "普通預金");
        f36577a.put(C11761Rb.SEND_MONEY, "支払い");
        f36577a.put(C11761Rb.SERVER_PROBLEM, "PayPalサーバーとの通信に問題があります。もう一度お試しください。");
        f36577a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "再度PayPalにログインしてください。");
        f36577a.put(C11761Rb.SESSION_EXPIRED_TITLE, "セッションが切れました");
        f36577a.put(C11761Rb.SHIPPING_ADDRESS, "配送先住所");
        f36577a.put(C11761Rb.SIGN_UP, "PayPalが初めての方 - 新規登録");
        f36577a.put(C11761Rb.STAY_LOGGED_IN, "ログイン状態を保存");
        f36577a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "システムエラーです(%s)。 時間をおいてから再度お試しください。");
        f36577a.put(C11761Rb.TRY_AGAIN, "再度実行してください");
        f36577a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "2要素認証がアカウントで有効になっているため、ログインできません。");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "セキュリティコード");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "端末にSMSを送信します。6桁のコードが届き、このコードは5分間有効です。");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "SMSを送信中");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "6桁のセキュリティコードを入力");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "携帯電話番号");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "SMSを送信");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "SMSを再度送信");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "2要素認証がアカウントで有効になっているため、ログインできません。PayPalの公式サイトにアクセスしてセキュリティキーを有効化してください。");
        f36577a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "この端末からの支払いは許可されていません。");
        f36577a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "未承認の端末");
        f36577a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "このマーチャントへの支払いは許可されていません(無効なクライアントID)。");
        f36577a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "無効なマーチャント");
        f36577a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "お客さまの支払い処理に問題がありました。もう一度お試しください。");
        f36577a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "未確認の資金源");
        f36577a.put(C11761Rb.WE_ARE_SORRY, "申し訳ございません");
        f36577a.put(C11761Rb.YOUR_ORDER, "お客さまのご注文");
        f36577a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Androidのバージョンが古いため、この端末でPayPalと通信することができません。Androidをアップグレードするか、新しい端末でお試しください。");
        f36577a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "カードをクリアしますか?");
        f36577a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "同意に失敗しました");
        f36577a.put(C11761Rb.CONNECTION_FAILED_TITLE, "接続できませんでした");
        f36577a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "ログインできませんでした");
        f36577a.put(C11761Rb.LOGIN_WITH_EMAIL, "パスワードでログイン");
        f36577a.put(C11761Rb.LOGIN_WITH_PHONE, "暗証番号でログイン");
        f36577a.put(C11761Rb.ONE_MOMENT, "少々お待ちください…");
        f36577a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "支払いが失敗しました");
        f36577a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "スキャン");
        f36577a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "セキュリティコードが間違っています。もう一度お試しください。");
        f36577a.put(C11761Rb.VIA_LABEL, "経由");
        String str2 = "システムエラーです。のちほどお試しください。";
        f36577a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "PayPalアカウントに登録された<a href='%1$s'>資金源</a>に関する情報を共有します。";
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "お客さまが同意を取り下げるまで、お客さまの代理として<a href='%1$s'>資金源</a>を共有します。";
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "PayPalアカウントに登録された<a href='%1$s'>支払方法</a>に関する情報を共有します。";
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "PayPalアカウントに登録された<a href='%1$s'>資金源</a>に関する情報を彼らと共有します。");
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "PayPalアカウントに登録された<a href='%1$s'>資金源</a>を共有します。");
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "PayPalアカウントに登録された<a href='%1$s'>資金源</a>を共有します。");
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f36578b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>今後%2$sでの買い物でPayPalで支払いをした場合の<a href='%1$s'>請求を承認します</a>。お客さまは、%3$sから請求された代金を全額支払うことをPayPalに指示します。</p><p>詳細については、「<a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal定期支払いと請求処理規約</a>」をご覧ください。</p>");
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>今後%2$sでの買い物でPayPalで支払いをした場合の<a href='%1$s'>請求を承認します</a>。お客さまは、%3$sから請求された代金を全額支払うことをPayPalに指示します。</p><p>詳細については、「<a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal定期支払いと請求処理規約</a>」をご覧ください。</p>");
        String str6 = "今後の買い物でPayPalで支払いをした場合の<a href='%1$s'>請求を承認します</a>。お客さまは、代金を全額支払うことをPayPalに指示し、これを承認します。";
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f36578b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "毎回PayPalにログインすることなく、PayPalアカウントから行われる今後の支払いを事前承認します。支払方法や今後の支払いのキャンセル方法などに関する<a href='%1$s'>その他の条項をご覧ください</a>。");
        String str7 = "お客さまが同意を取り下げるまで、%2$sがお客さまの代理として<a href='%1$s'>請求</a>を行うことを許可します。";
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f36578b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "お客さまが同意を取り下げるまで、%2$sがお客さまの代理として<a href='%1$s'>支払い</a>を行うことを許可します。";
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f36578b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>支払方法</strong></h1><p>PayPalが共有するのはお客さまのどの資金源が使用可能なのかのみです。</p>";
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>支払方法</strong></h1><p>PayPalが共有するのはお客さまのどの資金源が使用可能なのかに関する情報のみです。</p>";
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f36578b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>買い物のPayPal支払いには、初期設定の支払方法(PayPal残高、登録されている銀行口座、デビットカード、クレジットカードの順)が使用されます。初期設定の支払方法で購入代金の全額を支払えない場合は、銀行またはカード発行会社から手数料が請求される可能性がありますのでご注意ください。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>]の[<strong>設定</strong>]に移動して、[PayPalでログイン]の横の[<strong>変更</strong>]をクリックします。</p>");
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>買い物のPayPal支払いには、PayPal残高、メインのクレジットカードまたはデビットカードが使用されます。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p>");
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>PayPalでの支払いには、初期設定の支払方法が使用されます。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p>");
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のこのお店でのPayPal支払いには、初期設定の資金源が使用されます。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p><p><a href='%s'>PayPalユーザー規約</a>の「定期支払い」の項が適用されます。</p><p>PayPalアカウントで支払いを処理できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p>");
        String str11 = "<h1><strong>今後の支払いの承認</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>PayPalでの支払いには、初期設定の支払方法が使用されます。</p><p>この承認をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>アカウント設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p><p>詳細については、<a href='%s'>PayPalのユーザー規約</a>の「事前承認支払い」の項をご覧ください。</p>";
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>今後の支払いの承認</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>PayPalでの支払いには、初期設定の支払方法が使用されます。</p><p>この承認をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p><p>詳細については、<a href='%s'>PayPalユーザー規約</a>の「PayPal事前承認支払い」の項をご覧ください。</p>");
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>今後の支払いに関する規約</strong></h1><p>今後のお支払いでPayPalアカウントに請求できることを確認するため、このアプリでテストとして小額請求が行われる場合がありますが、実際の支払いとしては処理されません。</p><p>買い物のPayPal支払いには、PayPal残高、メインのクレジットカードまたはデビットカードが使用されます。</p><p>この規約をキャンセルするには、PayPalアカウントにログインして、[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p>");
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f36578b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>今後の支払いに関する規約</strong></h1><p>買い物の支払いには、最初にPayPal残高が使用されます。PayPal残高で全額支払いができない場合は、銀行口座、PayPal Credit、デビットカード、クレジットカード、eCheckの順番で使用されます。</p><p>この規約をキャンセルするには、www.paypal.comで[<strong>個人設定</strong>] &gt; [<strong>設定</strong>] &gt; [<strong>PayPalでログイン</strong>]に移動し、このお店をリストから削除します。</p><p>今後お客さまのPayPalアカウントに請求できることを確認するために、小額支払いの承認が要求される場合があります。この承認は無効になり、請求は行われません。</p>");
        f36578b.put("LOG_IN_TO_PAYPAL|AU", str);
        f36578b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.comでログインし、[<strong>個人設定</strong>]の[<strong>セキュリティ</strong>]で[<strong>PayPalでログイン</strong>]からこのお店を削除します。</p><p>お店側の対応または誤りについて、PayPalは責任を負いません。</p>";
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、パートナー会社と共有されます。</p><p>同意を取り下げるには、お使いのPayPalアカウントにログインし、ギアアイコンをクリックします。[<strong>セキュリティ</strong>]にアクセスし、[<strong>PayPalでログイン</strong>]を選択してこのパートナー会社を削除します。</p><p>パートナー会社側の対応または誤りについて、PayPalは責任を負いません。</p>";
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.comでログインし、[<strong>個人設定</strong>]の[<strong>PayPalでログイン</strong>]オプションからこのお店を削除します。</p><p>パートナー会社側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、お使いのPayPalアカウントにログインし、[<strong>個人設定</strong>]の[<strong>PayPalでログイン</strong>]オプションからこのお店を削除します。</p><p>お店側の対応または誤りについて、PayPalは責任を負いません。</p>";
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、お使いのPayPalアカウントにログインし、右上隅のギアアイコンをクリックして[<strong>セキュリティセンター</strong>]を選択し、[<strong>PayPalでログイン</strong>]からこのお店を削除します。クラシック版のサイトをご覧になられている場合は、[<strong>個人設定</strong>]で[<strong>アカウント設定</strong>]を選択し、[<strong>PayPalでログイン</strong>]からこのお店を削除します。</p><p>お店側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、パートナー会社と共有されます。</p><p>同意を取り下げるには、お使いのPayPalアカウントにログインし、[<strong>個人設定</strong>]の[<strong>PayPalでログイン</strong>]からこのパートナー会社を削除します。</p><p>パートナー会社側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.itでログインし、[<strong>個人設定</strong>]の[<strong>セキュリティ</strong>]で[<strong>PayPalでログイン</strong>]からこのお店を削除します。</p><p>お店側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、パートナー会社と共有されます。</p><p>同意を取り下げるには、paypal.ruでログインし、右上隅のギアアイコンをクリックして[<strong>セキュリティ</strong>]タブを選択し、[<strong>PayPalでログイン</strong>]オプションからこのパートナー会社を削除します。</p><p>パートナー会社側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.com.trでログインし、右上隅のギアアイコンをクリックして[<strong>セキュリティ</strong>]タブを選択し、[<strong>PayPalでログイン</strong>]オプションからこのパートナー会社を削除します。</p><p>お店側の対応または誤りについて、PayPalは責任を負いません。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>関連する取引の詳細は、お店と共有されます。</p><p>同意を取り下げるには、paypal.comでログインし、[<strong>個人設定</strong>]の[<strong>PayPalでログイン</strong>]オプションからこのお店を削除します。</p>");
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f36578b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f36579c.put("AMOUNT_MISMATCH", "カートの商品の合計金額が売上額と一致しません。");
        f36579c.put("AUTHORIZATION_ALREADY_COMPLETED", "この承認は、すでに完了しています。");
        f36579c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "承認を取り消しできるステータスではありません。");
        f36579c.put("AUTHORIZATION_EXPIRED", "承認は期限切れです。");
        f36579c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "要求された承認IDは存在しません。");
        f36579c.put("AUTHORIZATION_VOIDED", "承認は無効になりました。");
        f36579c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "再承認は元の承認に対してのみ実行できます。再承認に対する再承認はできません。");
        f36579c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "再承認は支払い猶予期間中には許可されません。");
        f36579c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "金額が取引限度額を超えています。");
        f36579c.put("CARD_TOKEN_PAYER_MISMATCH", "保存したカード情報にアクセスできません。");
        f36579c.put("CREDIT_CARD_CVV_CHECK_FAILED", "カード情報が無効です。修正し、もう一度送信してください。");
        f36579c.put("CREDIT_CARD_REFUSED", "カードが拒否されました。");
        f36579c.put("CURRENCY_MISMATCH", "回収する通貨は承認する通貨と同じでなければなりません。");
        f36579c.put("CURRENCY_NOT_ALLOWED", "この通貨は現在PayPalでサポートされていません。");
        f36579c.put("DATA_RETRIEVAL", str2);
        f36579c.put("DUPLICATE_REQUEST_ID", str2);
        f36579c.put("EXPIRED_CREDIT_CARD", "カードの有効期限が切れています");
        f36579c.put("EXPIRED_CREDIT_CARD_TOKEN", "このカードの情報は、記録に残っていません。\nもう一度送信してください。");
        f36579c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "この支払先に対して機能がサポートされていません。");
        f36579c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "この取引は、すでに一部が返金されています。");
        f36579c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "即時支払いは渡されたインテントに対してサポートされていません。");
        f36579c.put("INSTRUMENT_DECLINED", "選択された支払い方法には対応していませんでした。別の方法を選択してください。");
        f36579c.put("INSUFFICIENT_FUNDS", "買い手はお支払いできません - 資金が不足しています。");
        f36579c.put("INTERNAL_SERVICE_ERROR", str2);
        f36579c.put("INVALID_ACCOUNT_NUMBER", "口座番号が存在しません。");
        f36579c.put("INVALID_ARGUMENT", "引数が無効なため取引が拒否されました");
        f36579c.put("INVALID_CITY_STATE_ZIP", "無効な市区町村/都道府県/郵便番号の組み合わせです。");
        f36579c.put("INVALID_FACILITATOR_CONFIGURATION", "この取引は無効なファシリテーター設定により処理できません。");
        f36579c.put("INVALID_PAYER_ID", "システムエラーです(無効な支払人ID)。時間をおいてから再度お試しください。");
        f36579c.put("INVALID_RESOURCE_ID", str2);
        f36579c.put("PAYEE_ACCOUNT_INVALID", "支払先のアカウントには確認済みのメールアドレスがありません。");
        f36579c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "現時点では、このベンダーは支払いを受け取れません。");
        f36579c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "支払先のアカウントには確認済みのメールアドレスがありません。");
        f36579c.put("PAYEE_ACCOUNT_RESTRICTED", "現時点では、このベンダーは支払いを受け取れません。");
        f36579c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "アカウントがロックされているか解約されています。");
        f36579c.put("PAYER_ACCOUNT_RESTRICTED", "アカウントが制限されています。");
        f36579c.put("PAYER_CANNOT_PAY", "この取引をPayPalで支払うことはできません。");
        f36579c.put("PAYER_EMPTY_BILLING_ADDRESS", "PayPalクレジットカード以外の取引では請求先住所が必要です。");
        f36579c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "保存したカード情報にアクセスできません。");
        f36579c.put("PAYMENT_APPROVAL_EXPIRED", "支払いの承認期限が切れました。");
        f36579c.put("PAYMENT_EXPIRED", "支払いの有効期限が切れました。");
        f36579c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "支払人は支払いを承認していません。");
        f36579c.put("PAYMENT_REQUEST_ID_INVALID", "PayPalリクエストIDは無効です。のちほどお試しください。");
        f36579c.put("PAYMENT_STATE_INVALID", "この依頼は現在の支払いステータスにより無効です。");
        f36579c.put("PERMISSION_DENIED", "要求された操作の権限がありません。");
        f36579c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "要求された返金額が元の取引金額を超えています。");
        f36579c.put("REFUND_TIME_LIMIT_EXCEEDED", "この取引は、古すぎるため返金できません。");
        f36579c.put("REQUIRED_SCOPE_MISSING", str2);
        f36579c.put("TOO_MANY_REAUTHORIZATIONS", "この承認に対する再承認は、これ以上許可されません。");
        f36579c.put("TRANSACTION_ALREADY_REFUNDED", "この取引は、すでに返金されています。");
        f36579c.put("TRANSACTION_LIMIT_EXCEEDED", "金額が取引限度額を超えています。");
        f36579c.put("TRANSACTION_REFUSED", "取引は拒否されました。");
        f36579c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "取引は拒否されました。");
        f36579c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "マーチャント設定で、特定の取引については処理しないよう自動設定されています。");
        f36579c.put("UNKNOWN_ERROR", str2);
        f36579c.put("UNSUPPORTED_PAYEE_COUNTRY", "お住まいの国には対応しておりません。");
        f36579c.put("VALIDATION_ERROR", "この支払い情報は無効です。修正し、もう一度送信してください。");
        f36579c.put("ORDER_ALREADY_COMPLETED", "注文は既に無効となっているか、期限が切れているか、または完了しています。");
        f36579c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "この注文に対して認められている承認数が最大値に達しました。");
        f36579c.put("ORDER_VOIDED", "注文は無効になりました。");
        f36579c.put("ORDER_CANNOT_BE_VOIDED", "注文は、無効にできない状態です。");
        f36579c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f36579c.put("UNAUTHORIZED_PAYMENT", "お店は、このタイプの支払いを受け付けていません。");
        f36579c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "カードタイプでサポートされていない通貨です。");
        f36579c.put("DCC_CC_TYPE_NOT_SUPPORTED", "サポートされていないカードのタイプです。");
        f36579c.put("ADDRESS_ADDITION_ERROR", "PayPalアカウントに配送先住所を追加する際にエラーが発生しました。");
        f36579c.put("DUPLICATE_TRANSACTION", "二重支払いです。");
        f36579c.put("INVALID_SHIPPING_ADDRESS", "提供された配送先住所が有効ではありません。");
        f36579c.put("PAYMENT_CREATION_ERROR", "この支払いの設定に問題がありました。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "この支払いの設定に問題がありました - カードの有効期限切れです。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "この支払いの設定に問題がありました - クレジットカードなどの即時支払いが必要です。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "この支払いの設定に問題がありました - カードの確認手続きが必要です。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "この支払いの設定に問題がありました - このアプリでは、アカウントに電話番号が登録されている必要があります。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "この支払いの設定に問題がありました - アカウントに、銀行や決済カードなどの有効な資金源を登録する必要があります。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "この支払いの設定に問題がありました - 残高がマイナスです。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "この支払いの設定に問題がありました - 支払限度額に達しています。PayPalのページにアクセスしてお使いのアカウントをご確認ください。");
        f36579c.put("AUTH_RC_RISK_FAILURE", "この取引は処理できません。");
        f36579c.put("AUTH_RC_OFAC_BLOCKED_IP", "クライアントが承認されていません。");
        f36579c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "クライアントが承認されていません。");
        f36579c.put("invalid_user", "ユーザー名/パスワードが間違っています。再度お試しください。");
        f36579c.put("locked_user", "お客さまのPayPalアカウントは一時的にロックされています。後でもう一度お試しになるか、www.paypal.comにアクセスしてただちにPayPalアカウントのロックを解除してください。");
        f36579c.put("max_attempts_exceeded", "ログインの失敗が規定回数に達しました。のちほどお試しください。");
        f36579c.put("invalid_request", "エラーが発生しました。");
        String str15 = "リクエストが承認されていません。";
        f36579c.put("unauthorized_client", str15);
        f36579c.put("access_denied", str15);
        f36579c.put("unsupported_response_type", "エラーが発生しました。");
        f36579c.put("invalid_scope", str15);
        f36579c.put("server_error", str2);
        f36579c.put("temporarily_unavailable", str2);
        f36579c.put("stepup_required", "現在ログインを完了できません。あとで再度お試しください。またはwww.paypal.comにアクセスしてPayPalアカウントのセキュリティに関する問題に対応してください。");
        f36579c.put("account_locked_generate_challenge_limit_exceeded", "ログインの試行回数が規定回数を超えました。時間をおいてから再度入力するか、PayPalにお問い合わせください。");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "ja";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f36578b.containsKey(sb2) ? f36578b.get(sb2) : f36577a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f36579c.get(str);
    }
}
