package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.Fc */
public final class C11725Fc implements C11857oc {

    /* renamed from: a */
    private static final Map f36668a = new HashMap();

    /* renamed from: b */
    private static final Map f36669b = new HashMap();

    /* renamed from: c */
    private static final Map f36670c = new HashMap();

    public C11725Fc() {
        f36668a.put(C11761Rb.AGREE_AND_PAY, "Akkoord en betalen");
        f36668a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "& overige");
        f36668a.put(C11761Rb.AUTHENTICATING, "Verificatie");
        f36668a.put(C11761Rb.BACK_BUTTON, "Achterzijde");
        f36668a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Alternatief");
        f36668a.put(C11761Rb.CANCEL, "Annuleren");
        f36668a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f36668a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f36668a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f36668a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f36668a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f36668a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f36668a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f36668a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f36668a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f36668a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f36668a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f36668a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f36668a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f36668a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f36668a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f36668a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f36668a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Betaalmethode wijzigen");
        f36668a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Betaalrekening");
        f36668a.put(C11761Rb.CHECKING_DEVICE, "Dit apparaat wordt gecontroleerd…");
        f36668a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Kaartgegevens wissen");
        f36668a.put(C11761Rb.CONFIRM, "Bevestigen");
        f36668a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Weet je zeker dat je je kaartgegevens wilt wissen?");
        f36668a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Van kaart afschrijven");
        f36668a.put(C11761Rb.CONFIRM_LOG_OUT, "Weet je zeker dat je wilt uitloggen bij PayPal?");
        f36668a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Betalen");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Akkoord");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Rekening gemaakt op");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Rekeningstatus");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Rekeningtype");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adres");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Leeftijdsgroep");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Geboortedatum");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-mailadres");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Volledige naam");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Geslacht");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Taal");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Gebied");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefoon");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tijdzone");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Deel het volgende: %s.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Betaal supersnel.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s vraagt je om:");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Deel de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Betaalopties weergeven zodat je er een kunt kiezen.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die je met PayPal betaalt. Je geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "toestemming te verlenen onze klantenkaart aan je PayPal Wallet toe te voegen en deze te beheren.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Ga akkoord met het <a href='%2$s'>Privacybeleid</a> en de <a href='%3$s'>Gebruikersovereenkomst</a> van %1$s.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Sta toe om namens jou een <a href='%1$s'>betaalverzoek</a> te doen totdat je de toestemming intrekt.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Sta toe om namens jou <a href='%1$s'>geld over te maken</a> totdat je de toestemming intrekt.");
        f36668a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Toestemming");
        f36668a.put(C11761Rb.EMAIL, "E-mail");
        f36668a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Proefgegevens");
        f36668a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f36668a.put(C11761Rb.EXPIRES_ON_DATE, "Vervaldatum");
        f36668a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de betaalmethoden die beschikbaar zijn voor gebruik.</p>");
        f36668a.put(C11761Rb.FORGOT_PASSWORD, "Wachtwoord vergeten?");
        f36668a.put(C11761Rb.FROM_ACCOUNT, "Van");
        f36668a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Welke betaalmethode wil je gebruiken voor toekomstige betalingen aan %1$s?");
        f36668a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Je standaardbetaalbron wordt gebruikt voor toekomstige PayPal-betalingen van deze webwinkel.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening. Ga vervolgens naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijder deze webwinkel uit de lijst.</p><p>Het gedeelte Terugkerende betaling van de <a href='%s'>PayPal Gebruikersovereenkomst</a> is van toepassing.</p><p>Deze app kan een kleine testtransactie simuleren om te controleren of er betalingen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p>");
        f36668a.put(C11761Rb.INTERNAL_ERROR, "Interne fout");
        f36668a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Door op de knop hieronder te klikken, ga ik akkoord met de voorwaarden van de <a href='%1$s'>PayPal Gebruikersovereenkomst</a>·en verklaar ik dat ik voldoe aan de Japanse wetten en voorschriften, inclusief met betrekking tot sancties op betalingen aan Noord-Korea en Iran overeenkomstig de <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a>, bij het voltooien van de transactie.</p>");
        f36668a.put(C11761Rb.LOG_IN, "Inloggen");
        String str = "Inloggen met PayPal";
        f36668a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f36668a.put(C11761Rb.LOG_OUT_BUTTON, "Uitloggen");
        f36668a.put(C11761Rb.LOG_OUT, "Uitloggen");
        f36668a.put(C11761Rb.OK, "OK");
        f36668a.put(C11761Rb.PASSWORD, "Wachtwoord");
        f36668a.put(C11761Rb.PAY_AFTER_DELIVERY, "PayPal Achteraf Betalen");
        f36668a.put(C11761Rb.PAY_WITH, "Betalen met");
        f36668a.put(C11761Rb.PAY_WITH_CARD, "Betalen met creditcard");
        f36668a.put(C11761Rb.PAYPAL_BALANCE, "PayPal-saldo");
        f36668a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f36668a.put(C11761Rb.PHONE, "Telefoon");
        f36668a.put(C11761Rb.PIN, "Pincode");
        f36668a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Voorkeursbetaalmethode");
        f36668a.put(C11761Rb.PRIVACY, "PayPal beschermt je <a href='%s'>privacy</a> en financiële gegevens.");
        f36668a.put(C11761Rb.PROCESSING, "Bezig met verwerking");
        f36668a.put(C11761Rb.REMEMBER_CARD, "Kaart onthouden");
        f36668a.put(C11761Rb.REQUEST_MONEY, "Betaalverzoek");
        f36668a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f36668a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Spaarrekening");
        f36668a.put(C11761Rb.SEND_MONEY, "Geld overmaken");
        f36668a.put(C11761Rb.SERVER_PROBLEM, "Er is een probleem opgetreden bij de communicatie met de PayPal-servers. Probeer het opnieuw.");
        f36668a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Log opnieuw in bij PayPal.");
        f36668a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sessie verlopen");
        f36668a.put(C11761Rb.SHIPPING_ADDRESS, "Verzendadres");
        f36668a.put(C11761Rb.SIGN_UP, "Nieuw bij PayPal? Rekening openen");
        f36668a.put(C11761Rb.STAY_LOGGED_IN, "Ingelogd blijven");
        f36668a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Systeemfout (%s). Probeer het later opnieuw.");
        f36668a.put(C11761Rb.TRY_AGAIN, "Probeer het opnieuw");
        f36668a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Inloggen is niet mogelijk, omdat voor je rekening twee-factor verificatie is ingeschakeld");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Beveiligingscode");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Stuur een sms naar je telefoon. De zescijferige code die je ontvangt is 5 minuten geldig.");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sms wordt gestuurd");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Voer de zescijferige beveiligingscode in");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Je mobiele nummer");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Sms sturen");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Sms opnieuw sturen");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Inloggen is niet mogelijk, omdat voor je rekening twee-factor verificatie is ingeschakeld Ga naar de PayPal-website om je beveiligingssleutel te activeren.");
        f36668a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Betalingen vanaf dit apparaat zijn niet toegestaan.");
        f36668a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Ongeautoriseerd apparaat");
        f36668a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalingen aan deze webwinkel zijn niet toegestaan (ongeldig client-id)");
        f36668a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Ongeldige webwinkel");
        f36668a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Er is een probleem opgetreden bij de verwerking van je betaling. Probeer het opnieuw.");
        f36668a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Niet-herkende bron");
        f36668a.put(C11761Rb.WE_ARE_SORRY, "Onze excuses");
        f36668a.put(C11761Rb.YOUR_ORDER, "Je bestelling");
        f36668a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Dit apparaat kan niet met PayPal communiceren omdat deze versie van Android te oud is. Voer een upgrade van Android uit of probeer het met een nieuwer apparaat.");
        f36668a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Kaart verwijderen?");
        f36668a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Toestemming mislukt");
        f36668a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Verbinding mislukt");
        f36668a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Inloggen mislukt");
        f36668a.put(C11761Rb.LOGIN_WITH_EMAIL, "Inloggen met wachtwoord");
        f36668a.put(C11761Rb.LOGIN_WITH_PHONE, "Inloggen met pincode");
        f36668a.put(C11761Rb.ONE_MOMENT, "Even geduld…");
        f36668a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Betaling mislukt");
        f36668a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Scannen");
        f36668a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Onjuiste beveiligingscode. Probeer het opnieuw.");
        f36668a.put(C11761Rb.VIA_LABEL, "Via");
        String str2 = "Systeemfout. Probeer het later opnieuw.";
        f36668a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "Deel gegevens van de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.";
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "Namens jou de <a href='%1$s'>betaalbronnen</a> delen totdat je de toestemming intrekt.";
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "Deel gegevens van de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalmethoden</a>.";
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Deel gegevens over de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Deel de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Deel de aan je PayPal-rekening gekoppelde <a href='%1$s'>betaalbronnen</a>.");
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f36669b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die je met PayPal betaalt. Je geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.</p><p>Zie de <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal-overeenkomst voor terugkerende betalingen en facturen</a> voor meer informatie.</p>");
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen bij %2$s die je met PayPal betaalt. Je geeft PayPal opdracht alle door %3$s verzochte bedragen te betalen.</p><p>Zie de <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal-overeenkomst voor terugkerende betalingen en facturen</a> voor meer informatie.</p>");
        String str6 = "<a href='%1$s'>Geef toestemming</a> voor toekomstige aankopen die je met PayPal betaalt. Je geeft PayPal toestemming en opdracht alle bedragen te betalen.";
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f36669b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Geef vooraf toestemming voor toekomstige betalingen met je PayPal-rekening zodat je niet steeds hoeft in te loggen. <a href='%1$s'>Zie de aanvullende voorwaarden</a> over onder andere de betaalmethoden en hoe je toekomstige betalingen kunt annuleren.");
        String str7 = "Sta %2$s toe om namens jou een <a href='%1$s'>betaalverzoek</a> te doen totdat je de toestemming intrekt.";
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f36669b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Sta %2$s toe om namens jou <a href='%1$s'>geld over te maken</a> totdat je de toestemming intrekt.";
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f36669b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen je betaalbronnen die beschikbaar zijn voor gebruik.</p>";
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>betaalmethoden</strong></h1><p>PayPal deelt alleen de gegevens over de betaalbronnen die beschikbaar zijn voor gebruik.</p>";
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f36669b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren ter controle dat er in de toekomst bedragen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Je standaardbetaalmethode (PayPal-saldo, gekoppelde bankrekening of creditcard, in die volgorde) wordt gebruikt om voor aankopen met PayPal te betalen. Als het saldo van je standaardbetaalmethode ontoereikend is voor de aankoop, kan je bank of creditcardmaatschappij kosten in rekening brengen.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening, naar <strong>Profiel</strong> te gaan, op <strong>Rekeninginstellingen</strong> te klikken en op <strong>Wijzigen</strong> naast ‘Inloggen met PayPal’ te klikken.</p>");
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>We gebruiken je PayPal-saldo of primaire creditcard om voor aankopen met PayPal te betalen.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren ter controle dat er in de toekomst bedragen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Je standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Je standaardbetaalbron wordt gebruikt voor toekomstige PayPal-betalingen van deze webwinkel.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening. Ga vervolgens naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijder deze webwinkel uit de lijst.</p><p>Het gedeelte Terugkerende betaling van de <a href='%s'>PayPal Gebruikersovereenkomst</a> is van toepassing.</p><p>Deze app kan een kleine testtransactie simuleren om te controleren of er betalingen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p>");
        String str11 = "<h1><strong>Autorisatie voor toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>Je standaardbetaalmethode wordt gebruikt om aankopen met PayPal te betalen.</p><p>Je kunt deze autorisatie annuleren door in te loggen op je PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Zie het gedeelte ‘Vooraf goedgekeurde betalingen’ in de <a href='%s'>PayPal Gebruikersovereenkomst</a> voor meer informatie.</p>";
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>Deze app kan een kleine testtransactie simuleren om te controleren of er in de toekomst bedragen kunnen worden afgeschreven van je PayPal-rekening. Er wordt niet daadwerkelijk geld afgeschreven.</p><p>We gebruiken je PayPal-saldo of primaire creditcard om voor aankopen met PayPal te betalen.</p><p>Je kunt deze overeenkomst annuleren door in te loggen op je PayPal-rekening, naar <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p>");
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f36669b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Overeenkomst toekomstige betalingen</strong></h1><p>PayPal gebruikt eerst je PayPal-saldo om voor je aankoop te betalen. Als je saldo ontoereikend is om voor het totaalbedrag te betalen, worden in volgorde eerst je bankrekening, creditcard en vervolgens een uitgestelde bankbetaling gebruikt.</p><p>Je kunt deze overeenkomst annuleren door naar www.paypal.com <strong>Profiel</strong> &gt; <strong>Rekeninginstellingen</strong> &gt; <strong>Inloggen met PayPal</strong> te gaan en deze webwinkel uit de lijst te halen.</p><p>Het kan zijn dat je een kleine betaling moet autoriseren om het mogelijk te maken dat er in de toekomst bedragen van je PayPal-rekening kunnen worden afgeschreven. De autorisatie wordt geannuleerd en er wordt niets afgeschreven.</p>");
        f36669b.put("LOG_IN_TO_PAYPAL|AU", str);
        f36669b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op paypal.com in te loggen en bij <strong>Profiel</strong>, <strong>Beveiliging</strong>, de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>";
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en op het instellingenicoontje te klikken. Ga naar <strong>Beveiliging</strong>, selecteer <strong>Inloggen met PayPal</strong> en verwijder deze partner.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>";
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> te gaan bij je <strong>Profiel</strong>-instellingen en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>";
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        String str15 = "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>";
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str15);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, de optie <strong>Veilig handelen</strong> te kiezen, <strong>Inloggen met PayPal</strong> te selecteren en de webwinkel te verwijderen. Als je de klassieke website nog gebruikt, ga je naar <strong>Mijn profiel</strong> &gt; <strong>Rekeninggegevens</strong> &gt; <strong>Inloggen met PayPal</strong> en verwijder je de webwinkel.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en via de <strong>Profiel</strong>-instellingen naar <strong>Inloggen met PayPal</strong> te gaan en deze partner te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op paypal.it in te loggen en via <strong>Profiel</strong>, <strong>Beveiliging</strong> naar de optie <strong>Inloggen met PayPal</strong> te zoeken en deze webwinkel te verwijderen.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str15);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de partner gedeeld.</p><p>Je kunt de toestemming intrekken door op paypal.ru in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, het tabblad <strong>Beveiliging</strong> te kiezen en deze partner te verwijderen bij de optie <strong>Inloggen met PayPal</strong>.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de partner.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str15);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op paypal.com.tr in te loggen, in de rechterbovenhoek op het instellingenicoontje te klikken, het tabblad <strong>Beveiliging</strong> te kiezen en deze partner te verwijderen bij de optie <strong>Inloggen met PayPal</strong>.</p><p>PayPal is niet verantwoordelijk voor handelingen of fouten van de webwinkel.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transactiegegevens worden met de webwinkel gedeeld.</p><p>Je kunt de toestemming intrekken door op je PayPal-rekening in te loggen en naar de optie <strong>Inloggen met PayPal</strong> onder <strong>Profiel</strong>-instellingen te gaan en deze webwinkel te verwijderen.</p>");
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f36669b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f36670c.put("AMOUNT_MISMATCH", "Het totaalbedrag van items in het winkelwagentje komt niet overeen met het verkoopbedrag.");
        f36670c.put("AUTHORIZATION_ALREADY_COMPLETED", "Deze autorisatie is al voltooid.");
        f36670c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisatie heeft status die niet ongeldig kan worden gemaakt.");
        f36670c.put("AUTHORIZATION_EXPIRED", "Autorisatie is vervallen.");
        f36670c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "De gevraagde autorisatiereferentie bestaat niet.");
        f36670c.put("AUTHORIZATION_VOIDED", "Autorisatie is ongeldig gemaakt.");
        f36670c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Herautorisatie is alleen mogelijk van de oorspronkelijke autorisatie, niet van een herautorisatie.");
        f36670c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Herautorisatie is niet toegestaan binnen de betaalperiode.");
        f36670c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Het bedrag overschrijdt de toegestane limiet.");
        f36670c.put("CARD_TOKEN_PAYER_MISMATCH", "Toegang tot opgeslagen kaartgegevens mislukt.");
        f36670c.put("CREDIT_CARD_CVV_CHECK_FAILED", "De kaartgegevens zijn ongeldig. Corrigeer ze en verzend ze opnieuw.");
        f36670c.put("CREDIT_CARD_REFUSED", "Kaart afgewezen.");
        f36670c.put("CURRENCY_MISMATCH", "De valuta van de overboeking moet hetzelfde zijn als de autorisatievaluta.");
        f36670c.put("CURRENCY_NOT_ALLOWED", "Deze valuta wordt op dit moment niet door PayPal ondersteund.");
        f36670c.put("DATA_RETRIEVAL", str2);
        f36670c.put("DUPLICATE_REQUEST_ID", str2);
        f36670c.put("EXPIRED_CREDIT_CARD", "Kaart is verlopen");
        f36670c.put("EXPIRED_CREDIT_CARD_TOKEN", "De gegevens van deze kaart staan niet meer bij ons geregistreerd.\nVerzend de opnieuw.");
        f36670c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Functie wordt niet door leverancier ondersteund.");
        f36670c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Deze transactie is al gedeeltelijk terugbetaald.");
        f36670c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Direct betalen wordt niet ondersteund.");
        f36670c.put("INSTRUMENT_DECLINED", "De door jou geselecteerde betaalmethode is niet geaccepteerd. Kies een andere betaalmethode.");
        f36670c.put("INSUFFICIENT_FUNDS", "Koper kan niet betalen - te laag saldo");
        f36670c.put("INTERNAL_SERVICE_ERROR", str2);
        f36670c.put("INVALID_ACCOUNT_NUMBER", "Dat rekeningnummer bestaat niet.");
        f36670c.put("INVALID_ARGUMENT", "Transactie geweigerd vanwege ongeldig argument.");
        f36670c.put("INVALID_CITY_STATE_ZIP", "Combinatie plaats/staat/postcode ongeldig");
        f36670c.put("INVALID_FACILITATOR_CONFIGURATION", "Deze transactie kan niet worden verwerkt vanwege een ongeldige facilitator-configuratie.");
        f36670c.put("INVALID_PAYER_ID", "Systeemfout: (ongeldige betalersreferentie). Probeer het later opnieuw.");
        f36670c.put("INVALID_RESOURCE_ID", str2);
        f36670c.put("PAYEE_ACCOUNT_INVALID", "E-mailadres van rekening leverancier is niet bevestigd.");
        f36670c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Deze leverancier kan op dit moment geen betalingen ontvangen.");
        f36670c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "E-mailadres van rekening leverancier is niet bevestigd.");
        f36670c.put("PAYEE_ACCOUNT_RESTRICTED", "Deze leverancier kan op dit moment geen betalingen ontvangen.");
        f36670c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Je rekening is vergrendeld of gesloten.");
        f36670c.put("PAYER_ACCOUNT_RESTRICTED", "Je rekening is beperkt.");
        f36670c.put("PAYER_CANNOT_PAY", "Deze transactie kun je niet met PayPal betalen.");
        f36670c.put("PAYER_EMPTY_BILLING_ADDRESS", "Voor creditcardtransacties die niet via PayPal verlopen is er een factuuradres nodig.");
        f36670c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Toegang tot opgeslagen kaartgegevens mislukt.");
        f36670c.put("PAYMENT_APPROVAL_EXPIRED", "Betaalgoedkeuring is vervallen.");
        f36670c.put("PAYMENT_EXPIRED", "De betaling is vervallen.");
        f36670c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "De betaler heeft de betaling niet goedgekeurd.");
        f36670c.put("PAYMENT_REQUEST_ID_INVALID", "De referentie voor dit PayPal-verzoek is ongeldig. Probeer het later opnieuw.");
        f36670c.put("PAYMENT_STATE_INVALID", "Dit verzoek is ongeldig ten gevolge van de huidige status van de betaling.");
        f36670c.put("PERMISSION_DENIED", "Geen toestemming voor de gevraagde bewerking.");
        f36670c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "De gevraagde terugbetaling is hoger dan het bedrag van de oorspronkelijke transactie.");
        f36670c.put("REFUND_TIME_LIMIT_EXCEEDED", "Deze transactie is te oud voor terugbetaling.");
        f36670c.put("REQUIRED_SCOPE_MISSING", str2);
        f36670c.put("TOO_MANY_REAUTHORIZATIONS", "Er zijn geen herautorisaties meer toegestaan voor deze autorisatie.");
        f36670c.put("TRANSACTION_ALREADY_REFUNDED", "Deze transactie is al terugbetaald.");
        f36670c.put("TRANSACTION_LIMIT_EXCEEDED", "Het bedrag overschrijdt de toegestane limiet.");
        f36670c.put("TRANSACTION_REFUSED", "De transactie is geweigerd.");
        f36670c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "De transactie is geweigerd.");
        f36670c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Het profiel van de webwinkel is ingesteld om bepaalde transacties automatisch te weigeren.");
        f36670c.put("UNKNOWN_ERROR", str2);
        f36670c.put("UNSUPPORTED_PAYEE_COUNTRY", "Er is geen ondersteuning voor je land.");
        f36670c.put("VALIDATION_ERROR", "De betalingsgegevens zijn ongeldig. Corrigeer ze en verzend ze opnieuw.");
        f36670c.put("ORDER_ALREADY_COMPLETED", "Bestelling is al ongeldig gemaakt, verlopen of voltooid.");
        f36670c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Het maximale aantal toegestane autorisaties voor de bestelling is bereikt.");
        f36670c.put("ORDER_VOIDED", "Je bestelling is ongeldig gemaakt.");
        f36670c.put("ORDER_CANNOT_BE_VOIDED", "De bestelling heeft een status die verhindert dat deze ongeldig kan worden gemaakt.");
        f36670c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f36670c.put("UNAUTHORIZED_PAYMENT", "Deze webwinkel accepteert dit type betalingen niet.");
        f36670c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta niet ondersteund voor type creditcard.");
        f36670c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kaarttype wordt niet ondersteund.");
        f36670c.put("ADDRESS_ADDITION_ERROR", "Er is een fout opgetreden bij het toevoegen van het verzendadres aan de PayPal-rekening.");
        f36670c.put("DUPLICATE_TRANSACTION", "Dubbele transactie.");
        f36670c.put("INVALID_SHIPPING_ADDRESS", "Het verstrekte verzendadres is ongeldig.");
        f36670c.put("PAYMENT_CREATION_ERROR", "Er is een probleem opgetreden bij het instellen van deze betaling. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Er is een probleem opgetreden bij het instellen van deze betaling - je kaart is verlopen. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Er is een probleem opgetreden bij het instellen van deze betaling - er is een directe betaling vereist, zoals met een creditcard. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Er is een probleem opgetreden bij het instellen van deze betaling - de kaart moet worden bevestigd. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Er is een probleem opgetreden bij het instellen van deze betaling - voor deze app is het nodig een telefoon aan je rekening toe te voegen. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Er is een probleem opgetreden bij het instellen van deze betaling - rekening heeft een geldige betaalbron zoals een bank- of betaalkaart nodig. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Er is een probleem opgetreden bij het instellen van deze betaling - je bent je saldo nog een bedrag verschuldigd. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Er is een probleem opgetreden bij het instellen van deze betaling -je hebt je verzendlimiet bereikt. Ga naar de PayPal-website om je rekening te controleren.");
        f36670c.put("AUTH_RC_RISK_FAILURE", "Afgewezen wegens risico");
        f36670c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client niet goedgekeurd.");
        f36670c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client niet goedgekeurd.");
        f36670c.put("invalid_user", "Gebruikersnaam/wachtwoord onjuist Probeer het opnieuw.");
        f36670c.put("locked_user", "Je PayPal-rekening is tijdelijk geblokkeerd. Probeer het later opnieuw of ga naar www.paypal.com om de blokkade direct op te heffen.");
        f36670c.put("max_attempts_exceeded", "Te veel mislukte inlogpogingen. Probeer het later opnieuw.");
        f36670c.put("invalid_request", "Er is een fout opgetreden.");
        f36670c.put("unauthorized_client", "Verzoek niet goedgekeurd");
        f36670c.put("access_denied", "Verzoek niet goedgekeurd");
        f36670c.put("unsupported_response_type", "Er is een fout opgetreden.");
        f36670c.put("invalid_scope", "Verzoek niet goedgekeurd");
        f36670c.put("server_error", str2);
        f36670c.put("temporarily_unavailable", str2);
        f36670c.put("stepup_required", "Je kunt op dit moment niet inloggen. Probeer het later opnieuw of ga naar www.paypal.com om eventuele beveiligingsproblemen met je PayPal-rekening af te handelen.");
        f36670c.put("account_locked_generate_challenge_limit_exceeded", "Te veel inlogpogingen. Probeer het later opnieuw of neem contact op met PayPal voor hulp.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "nl";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f36669b.containsKey(sb2) ? f36669b.get(sb2) : f36668a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f36670c.get(str);
    }
}
