package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.g */
public final class C11822g implements C11857oc {

    /* renamed from: a */
    private static final Map f37211a = new HashMap();

    /* renamed from: b */
    private static final Map f37212b = new HashMap();

    /* renamed from: c */
    private static final Map f37213c = new HashMap();

    public C11822g() {
        f37211a.put(C11761Rb.AGREE_AND_PAY, "Kabul Edin ve Ödeyin");
        f37211a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "ve diğer");
        f37211a.put(C11761Rb.AUTHENTICATING, "Kimlik doğrulaması yapılıyor");
        f37211a.put(C11761Rb.BACK_BUTTON, "Geri");
        f37211a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Yedek");
        f37211a.put(C11761Rb.CANCEL, "İptal");
        f37211a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37211a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37211a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37211a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37211a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37211a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37211a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37211a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37211a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37211a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37211a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37211a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37211a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37211a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37211a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37211a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37211a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Ödeme Yöntemini Değiştir");
        f37211a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Mevduat Hesabı");
        f37211a.put(C11761Rb.CHECKING_DEVICE, "Bu cihaz kontrol ediliyor…");
        f37211a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Kart bilgilerini sil");
        f37211a.put(C11761Rb.CONFIRM, "Onayla");
        f37211a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Kart bilgilerinizi silmek istediğinizden emin misiniz?");
        f37211a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Karttan Çekim Yap");
        f37211a.put(C11761Rb.CONFIRM_LOG_OUT, "PayPal’dan çıkış yapmak istediğinizden emin misiniz?");
        f37211a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Öde");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Kabul Et");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Hesap Oluşturma Tarihi");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Hesap Durumu");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Hesap Türü");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adres");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Yaş Aralığı");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Doğum Tarihi");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-posta adresi");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Tam Adı");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Cinsiyeti");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Dil");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Bölge");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Saat Dilimi");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Şunu paylaşın: %s.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Hızlı Satınalma᾿dan yararlanın.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s şunları yapmanızı istiyor:");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "PayPal hesabınızda tanımlı olan <a href='%1$s'>ödeme yöntemlerini</a> paylaşın.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Tercih yapmanızı sağlayacak şekilde para kaynağı seçeneklerinizin görüntülenmesini etkinleştirin.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "İleride PayPal ile ödemesi yapılacak %2$s alışverişler için <a href='%1$s'>çekim talimatı verin</a>. %3$s tarafından talep edilen tüm tutarların ödenmesi için PayPal’a talimat verirsiniz.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "PayPal e-cüzdanınızda bağlılık kartını ekleyip yönetmesine izin verin.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "%1$s <a href='%2$s'>gizlilik politikasını</a> ve <a href='%3$s'>kullanıcı sözleşmesini</a> kabul edin.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Siz onayınızı geri çekene kadar adınıza <a href='%1$s'>para talep etmesine</a> izin verin.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Siz onayınızı geri çekene kadar adınıza <a href='%1$s'>para göndermesine</a> izin verin.");
        f37211a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Onay");
        f37211a.put(C11761Rb.EMAIL, "E-posta");
        f37211a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Örnek Veriler");
        f37211a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Test Ortamı");
        f37211a.put(C11761Rb.EXPIRES_ON_DATE, "Son kullanma tarihi");
        f37211a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Ödeme Yöntemleri</strong></h1><p>PayPal yalnızca hangi ödeme yönteminizin kullanıma uygun olduğunu paylaşır.</p>");
        f37211a.put(C11761Rb.FORGOT_PASSWORD, "Şifrenizi mi unuttunuz?");
        f37211a.put(C11761Rb.FROM_ACCOUNT, "Kaynak");
        f37211a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "%1$s için sonraki ödemelerinizi nasıl yapmak istersiniz?");
        f37211a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>Varsayılan ödeme kaynağınız bu mağazadan ileri tarihli PayPal ödemelerini yapmak için kullanılacaktır.</p><p>Bu sözleşmeyi iptal etmek için PayPal hesabınıza giriş yapın, <strong>Profil</strong> &gt; <strong>Ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> ve bu mağazayı listeden kaldırın.</p><p><a href='%s'>PayPal Kullanıcı Sözleşmesi</a>’nin Düzenli Ödeme bölümü uygulanacaktır.</p><p>Ödemelerinizin PayPal hesabınızla yapıldığından emin olmak için bu uygulama küçük bir test işlem simüle edebilir ancak para transferi yapılmaz.</p>");
        f37211a.put(C11761Rb.INTERNAL_ERROR, "Dahili Hata");
        f37211a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Aşağıdaki düğmeyi tıklayarak, <a href='%1$s'>PayPal Kullanıcı Sözleşmesinin</a> şartlarını kabul ediyorum ve işlemi tamamlamak üzere <a href='%2$s'>Yabancı Döviz ve Yabancı Ticaret Kanununa</a> istinaden Kuzey Kore ve İran’a yönelik ödemelere karşı uygulanan yaptırımlar dahil Japon kanun ve düzenlemelerine uyduğumu beyan ediyorum.</p>");
        f37211a.put(C11761Rb.LOG_IN, "Giriş Yapın");
        f37211a.put(C11761Rb.LOG_IN_TO_PAYPAL, "PayPal ile Giriş Yapın");
        f37211a.put(C11761Rb.LOG_OUT_BUTTON, "Çıkış");
        f37211a.put(C11761Rb.LOG_OUT, "Çıkış yapın");
        f37211a.put(C11761Rb.OK, "Tamam");
        f37211a.put(C11761Rb.PASSWORD, "Şifre");
        f37211a.put(C11761Rb.PAY_AFTER_DELIVERY, "Teslimattan Sonra Ödeyin");
        f37211a.put(C11761Rb.PAY_WITH, "Şu yolla ödeyin");
        f37211a.put(C11761Rb.PAY_WITH_CARD, "Kartla ödeyin");
        f37211a.put(C11761Rb.PAYPAL_BALANCE, "PayPal Bakiyesi");
        f37211a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Kredisi");
        f37211a.put(C11761Rb.PHONE, "Telefon");
        f37211a.put(C11761Rb.PIN, "PIN");
        f37211a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Tercih Edilen Ödeme Yöntemi");
        f37211a.put(C11761Rb.PRIVACY, "PayPal <a href='%s'>gizli</a> ve finansal bilgilerinizi korur.");
        f37211a.put(C11761Rb.PROCESSING, "İşleniyor");
        f37211a.put(C11761Rb.REMEMBER_CARD, "Kartı hatırla");
        f37211a.put(C11761Rb.REQUEST_MONEY, "Para Talep Et");
        f37211a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.com adresinde giriş yapın ve ardından <strong>Profil</strong> ayarlarındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, iş ortağı tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37211a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Tasarruf");
        f37211a.put(C11761Rb.SEND_MONEY, "Para Gönder");
        f37211a.put(C11761Rb.SERVER_PROBLEM, "PayPal sunucularıyla iletişim kurarken sorun oluştu. Lütfen tekrar deneyin.");
        f37211a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Lütfen PayPal’a tekrar giriş yapın.");
        f37211a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Oturumun Süresi Doldu");
        f37211a.put(C11761Rb.SHIPPING_ADDRESS, "Gönderim Adresi");
        f37211a.put(C11761Rb.SIGN_UP, "PayPal’da yeni misiniz? Hesap Açın");
        f37211a.put(C11761Rb.STAY_LOGGED_IN, "Oturum kapanmasın");
        f37211a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Sistem hatası (%s). Lütfen daha sonra tekrar deneyin.");
        f37211a.put(C11761Rb.TRY_AGAIN, "Tekrar Deneyin");
        f37211a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Hesabınızda iki faktörlü doğrulama etkinleştirildiğinden giriş yapılamıyor.");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Güvenlik Kodu");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Telefonunuza mesaj gönderin. Aldığınız 6-haneli kod 5 dakika geçerli olacaktır.");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Mesaj Gönderiliyor");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "6 haneli güvenlik kodunu girin");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Cep telefonu numaranız");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Mesaj Gönder");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Yeniden Mesaj Gönder");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Hesabınızda iki faktörlü doğrulama etkinleştirildiğinden giriş yapılamıyor. Güvenlik anahtarınızı etkinleştirmek için PayPal web sitesini ziyaret edin.");
        f37211a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Bu cihazdan ödeme yapma izniniz yok.");
        f37211a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Yetkisiz Cihaz");
        f37211a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Bu mağazaya ödeme yapılmasına izin verilmiyor (geçersiz müşteriNo).");
        f37211a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Geçersiz mağaza");
        f37211a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Ödemeniz işlenirken bir sorun oluştu. Lütfen tekrar deneyin.");
        f37211a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Tanınmayan Kaynak");
        f37211a.put(C11761Rb.WE_ARE_SORRY, "Üzgünüz");
        f37211a.put(C11761Rb.YOUR_ORDER, "Siparişiniz");
        f37211a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Bu Android sürümü çok eski olduğundan bu cihazdan PayPal ile iletişim kurulamıyor. Lütfen Android sürümünü yükseltin veya yeni bir cihazdan işlem yapmayı deneyin.");
        f37211a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Kart silinsin mi?");
        f37211a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Onay Başarısız Oldu");
        f37211a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Bağlantı Yapılamadı");
        f37211a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Giriş Yapılamadı.");
        f37211a.put(C11761Rb.LOGIN_WITH_EMAIL, "Şifrenizle giriş yapın");
        f37211a.put(C11761Rb.LOGIN_WITH_PHONE, "PIN’inizle giriş yapın");
        f37211a.put(C11761Rb.ONE_MOMENT, "Bir saniye…");
        f37211a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Ödeme Yapılamadı.");
        f37211a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Tara");
        f37211a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Yanlış Güvenlik Kodu. Lütfen tekrar deneyin.");
        f37211a.put(C11761Rb.VIA_LABEL, "İle");
        String str = "Sistem hatası. Lütfen daha sonra tekrar deneyin.";
        f37211a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str);
        String str2 = "PayPal hesabınızda tanımlı <a href='%1$s'>ödeme kaynakları</a> hakkında bilgileri paylaşın.";
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str2);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str2);
        String str3 = "Onayınızı geri alana kadar adınıza <a href='%1$s'>ödeme kaynaklarını</a> paylaşın.";
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str2);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str2);
        String str4 = "PayPal hesabınızda tanımlı <a href='%1$s'>ödeme yöntemleri</a> hakkında bilgiler paylaşın.";
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str4);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "PayPal hesabınızda tanımlı <a href='%1$s'>ödeme kaynakları</a> hakkında bilgileri onlarla paylaşın.");
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "PayPal hesabınızda tanımlı <a href='%1$s'>ödeme kaynaklarını</a> paylaşın.");
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "PayPal hesabınızda tanımlı <a href='%1$s'>ödeme kaynaklarını</a> paylaşın.");
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str2);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str4);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str2);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str4);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str3);
        f37212b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str3);
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>İleride PayPal ile ödemesi yapılacak %2$s alışverişler için <a href='%1$s'>çekim talimatı verin</a>. %3$s tarafından talep edilen tüm tutarların ödenmesi için PayPal’a talimat verirsiniz.</p><p>Lütfen daha fazla bilgi için bkz. <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal Düzenli Ödemeler ve Fatura Sözleşmesi</a>.</p>");
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>İleride PayPal ile ödemesi yapılacak %2$s alışverişler için <a href='%1$s'>çekim talimatı verin</a>. %3$s tarafından talep edilen tüm tutarların ödenmesi için PayPal’a talimat verirsiniz.</p><p>Lütfen daha fazla bilgi için bkz. <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal Düzenli Ödemeler ve Fatura Sözleşmesi</a>.</p>");
        String str5 = "İleride PayPal ile ödemesi yapılacak alışverişler için <a href='%1$s'>çekim talimatı verin</a>. Tüm tutarların ödenmesi için PayPal’a yetki ve talimat verirsiniz.";
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str5);
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str5);
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str5);
        f37212b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Her seferinde PayPal’a giriş yapmadan PayPal hesabınızdan yapılan talimatlı ödemeleri önceden onaylayın. Ödeme yöntemleri ve talimatlı ödemelerin nasıl iptal edileceği de dahil olmak üzere <a href='%1$s'>ek şartlara bakın</a>.");
        String str6 = "Onayınızı geri çekene kadar %2$s için adınıza <a href='%1$s'>para talep etme</a> izni verin.";
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str6);
        f37212b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str6);
        String str7 = "Onayınızı geri alana kadar %2$s için adınıza <a href='%1$s'>para gönderme</a> izni verin.";
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str7);
        f37212b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str7);
        String str8 = "<h1><strong>Ödeme Yöntemleri</strong></h1><p>PayPal yalnızca hangi ödeme kaynaklarınızın kullanıma uygun olduğunu paylaşır.</p>";
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str8);
        String str9 = "<h1><strong>Ödeme Yöntemleri</strong></h1><p>PayPal yalnızca hangi ödeme kaynaklarınızın kullanıma uygun olduğuna ilişkin bilgileri paylaşır.</p>";
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str9);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str9);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str9);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str8);
        f37212b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str8);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>PayPal hesabınızdan gelecekte çekim yapılabilmesini sağlamak için bu uygulama, küçük bir test işlem simüle edebilir ancak para transferi gerçekleşmeyecektir.</p><p>Varsayılan ödeme yönteminiz (sırasıyla PayPal bakiyeniz, tanımlı banka hesabı, banka veya kredi kartı) PayPal alışverişlerinizin ödemesi için kullanılacaktır. Varsayılan ödeme yönteminizin alışverişi karşılayacak yeterli bakiyeye sahip olmaması durumund bankanız veya kart sağlayıcınız sizden ücret alabilir.</p><p>Bu sözleşmeyi iptal etmek için PayPal hesabınıza giriş yapın ve <strong>Profil</strong>, ardından <strong>Ayarlarım</strong> ve “PayPal ile Giriş Yapın” seçeneğinin yanındaki <strong>Değiştir</strong> seçeneğini tıklayın.</p>");
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>PayPal hesabınızdan gelecekte çekim yapılabilmesini sağlamak için bu uygulama, küçük bir test işlem simüle edebilir ancak para transferi yapılmayacaktır.</p><p>PayPal alışverişleriniz için PayPal bakiyeniz veya birincil kredi veya banka kartınız kullanılacak.</p><p>Bu sözleşmeyi iptal etmek için PayPal hesabınıza giriş yapın, <strong>Profil</strong> &gt; <strong>Ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> ve bu mağazayı listeden çıkarın.</p>");
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>İleride PayPal Hesabınızdan çekim yapılabilmesi için bu uygulama küçük bir test işlemini simüle edecek ancak ödeme transferi yapılmayacaktır.</p><p>PayPal alışverişlerinizde ödeme yapmak için varsayılan ödeme yönteminiz kullanılacak.</p><p>Bu sözleşmeyi iptal etmek için PayPal Hesabınıza giriş yapın, <strong>Profil</strong> &gt; <strong>Ayarlar</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> ve bu mağazayı listeden kaldırın.</p>");
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>Varsayılan ödeme kaynağınız bu mağazadan ileri tarihli PayPal ödemelerini yapmak için kullanılacaktır.</p><p>Bu sözleşmeyi iptal etmek için PayPal hesabınıza giriş yapın, <strong>Profile</strong> &gt; <strong>Ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> bölümüne gidin ve bu mağazayı listeden kaldırın.</p><p><a href='%s'>PayPal Kullanıcı Sözleşmesi</a>’nin Düzenli Ödeme bölümü uygulanacaktır.</p><p>Ödemelerinizin PayPal hesabınızla yapıldığından emin olmak için bu uygulama küçük bir test işlemi simüle edebilir ancak bunun için para transferi yapılmaz.</p>");
        String str10 = "<h1><strong>İleri Ödeme Talimatı</strong></h1><p>İleride PayPal Hesabınızdan çekim yapılabilmesi için bu uygulama küçük bir test işlemini simüle edecek ancak ödeme transferi yapılmayacaktır.</p><p>PayPal alışverişlerinizde ödeme yapmak için varsayılan ödeme yönteminiz kullanılacak.</p><p>Bu talimatı iptal etmek için PayPal hesabınıza giriş yapın, <strong>Profil</strong> &gt; <strong>Hesap ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> bölümüne gidin ve bu mağazayı listeden kaldırın.</p><p>Daha fazla bilgi için lütfen <a href='%s'>PayPal Kullanıcı Sözleşmesi</a>’nin “Talimatlı Ödemeler” bölümüne bakın.</p>";
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str10);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str10);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>PayPal hesabınızdan gelecekte çekim yapılabilmesini sağlamak için bu uygulama, küçük bir test işlem simüle edebilir ancak para transferi yapılmayacaktır.</p><p>PayPal alışverişleriniz için PayPal bakiyeniz veya birincil kredi veya banka kartınız kullanılacak.</p><p>Bu sözleşmeyi iptal etmek için PayPal hesabınıza giriş yapın, <strong>Profil</strong> &gt; <strong>Ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> ve bu mağazayı listeden çıkarın.</p>");
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str10);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str10);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str10);
        f37212b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Gelecek Ödeme Sözleşmesi</strong></h1><p>PayPal alışverişlerin ödemesini yapmak için öncelikle PayPal bakiyenizi kullanacaktır. Bu bakiye, toplamı karşılamıyorsa sırasıyla banka hesabınız, PayPal Kredi, banka kartı, kredi kartı ve/veya eÇek kullanılacaktır.</p><p>Bu sözleşmeyi iptal etmek için, www.paypal.com <strong>Profil</strong> &gt; <strong>Ayarlarım</strong> &gt; <strong>PayPal ile Giriş Yapın</strong> ve bu mağazayı listeden çıkarın.</p><p>İleride PayPal hesabınızdan çekim yapılabileceğinden emin olmak için küçük bir ödeme talimatı gerekli olabilir. Talimat geçersiz olacak ve sizden çekim yapılmayacaktır.</p>");
        f37212b.put("LOG_IN_TO_PAYPAL|AU", "PayPal ile giriş yapın");
        f37212b.put("LOG_IN_TO_PAYPAL|GB", "PayPal ile giriş yapın");
        String str11 = "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.com adresinde giriş yapın ve ardından <strong>Profil</strong>, <strong>Güvenlik</strong> sayfasındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, mağaza tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>";
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str11);
        String str12 = "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları iş ortağı ile paylaşılır.</p><p>Onayı geri almak için PayPal hesabınıza giriş yapın ve dişli çark simgesini tıklayın. <strong>Güvenlik</strong> sayfasına gidin, <strong>PayPal ile Giriş Yapın</strong>ı seçin ve bu iş ortağını kaldırın.</p><p>PayPal, iş ortağı tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>";
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str12);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.com adresinde giriş yapın ve ardından <strong>Profil</strong> ayarlarındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, iş ortağı tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str11);
        String str13 = "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için PayPal hesabınıza giriş yapın ve ardından <strong>Profil</strong> ayarlarınızdaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, mağaza tarafındaki işlem veya hatalardan sorumlu değildir.</p>";
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str13);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str12);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için PayPal hesabınıza giriş yapın ve ardından <strong>Profil</strong> ayarlarındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, mağaza tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>";
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için PayPal hesabınıza giriş yapın, sağ üst köşedeki dişli çark simgesini tıklayın, <strong>Güvenlik Merkezi</strong>ni ve ardından <strong>PayPal ile Giriş Yapın</strong>ı seçerek bu mağazayı kaldırın. Hâlâ klasik web sitesini kullanıyorsanız <strong>Profilim</strong>e gidin, <strong>Hesap Ayarlarım</strong>ı ve ardından <strong>PayPal ile Giriş Yapın</strong>ı seçerek mağazayı kaldırın.</p><p>PayPal, mağaza tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları iş ortağı ile paylaşılır.</p><p>Onayı geri çekmek için PayPal hesabınıza giriş yapın, ardından <strong>Profil</strong> ayarlarının altındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne gidin ve bu iş ortağını kaldırın.</p><p>PayPal, iş ortağı tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.it adresinde giriş yapın ve ardından <strong>Profil</strong>, <strong>Güvenlik</strong> sayfasındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p><p>PayPal, mağaza tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str13);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str13);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları iş ortağı ile paylaşılır.</p><p>Onayı geri çekmek için paypal.ru adresinde giriş yapın, sağ üst köşedeki dişli çark simgesini tıklayın, <strong>Güvenlik</strong> sekmesini seçin ve <strong>PayPal ile Giriş Yapın</strong> seçeneğinde bu iş ortağını kaldırın.</p><p>PayPal, iş ortağı tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.com.tr adresinde giriş yapın, sağ üst köşedeki dişli çark simgesini tıklayın <strong>Güvenlik</strong> sekmesini seçin ve <strong>PayPal ile Giriş Yapın</strong> seçeneğinde bu iş ortağını kaldırın.</p><p>PayPal, mağaza tarafındaki işlemlerden veya hatalardan sorumlu değildir.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>İlgili tüm işlem ayrıntıları mağaza ile paylaşılır.</p><p>Onayı geri çekmek için paypal.com adresinde giriş yapın ve ardından <strong>Profil</strong> ayarlarındaki <strong>PayPal ile Giriş Yapın</strong> bölümüne giderek bu mağazayı kaldırın.</p>");
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str11);
        f37212b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str11);
        f37213c.put("AMOUNT_MISMATCH", "Alışveriş sepeti toplam tutarı satış tutarı ile eşleşmiyor.");
        f37213c.put("AUTHORIZATION_ALREADY_COMPLETED", "Bu talimat zaten tamamlandı.");
        f37213c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Talimat iptal edilemeyecek bir durum düzeyinde.");
        f37213c.put("AUTHORIZATION_EXPIRED", "Talimatın süresi doldu.");
        f37213c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Talep edilen yetkilendirme kimliği mevcut değil.");
        f37213c.put("AUTHORIZATION_VOIDED", "Yetki geçersiz kılındı.");
        f37213c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Yalnızca orijinal yetkilendirmeyi yeniden yetkilendirebilirsiniz.");
        f37213c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Yeniden yetkilendirme ödeme döneminde yapılamaz.");
        f37213c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Bu tutar, izin verilen limiti aşıyor.");
        f37213c.put("CARD_TOKEN_PAYER_MISMATCH", "Kayıtlı kart bilgilerine erişilemiyor.");
        f37213c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kart bilgileri geçersiz. Lütfen düzeltip tekrar gönderin.");
        f37213c.put("CREDIT_CARD_REFUSED", "Kart reddedildi.");
        f37213c.put("CURRENCY_MISMATCH", "Tahsilat para birimi ile talimat para birimi aynı olmalıdır.");
        f37213c.put("CURRENCY_NOT_ALLOWED", "Bu para birimi şu anda PayPal tarafından desteklenmiyor.");
        f37213c.put("DATA_RETRIEVAL", str);
        f37213c.put("DUPLICATE_REQUEST_ID", str);
        f37213c.put("EXPIRED_CREDIT_CARD", "Kartın kullanım süresi sona erdi");
        f37213c.put("EXPIRED_CREDIT_CARD_TOKEN", "Bu karta ilişkin bilgiler artık kayıtlı değil.\nLütfen tekrar gönderin.");
        f37213c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Özellik bu satıcı tarafından desteklenmiyor.");
        f37213c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Bu işlem kısmi olarak iade edildi.");
        f37213c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Hızlı ödeme belirlenen işlem amacı için desteklenmiyor.");
        f37213c.put("INSTRUMENT_DECLINED", "Seçilen ödeme yönteminiz kabul edilmemiştir. Lütfen farklı bir ödeme yöntemi seçin.");
        f37213c.put("INSUFFICIENT_FUNDS", "Alıcı ödeme yapamıyor - yetersiz bakiye.");
        f37213c.put("INTERNAL_SERVICE_ERROR", str);
        f37213c.put("INVALID_ACCOUNT_NUMBER", "Bu hesap numarası mevcut değil.");
        f37213c.put("INVALID_ARGUMENT", "Geçersiz bağımsız değişken nedeniyle işlem reddedildi");
        f37213c.put("INVALID_CITY_STATE_ZIP", "Geçersiz şehir/eyalet/posta kodu kombinasyonu.");
        f37213c.put("INVALID_FACILITATOR_CONFIGURATION", "Bu işlem geçersiz bir ara konfigürasyon nedeniyle işlenemiyor.");
        f37213c.put("INVALID_PAYER_ID", "Sistem hatası (geçersiz Ödeyen Kimliği). Lütfen daha sonra tekrar deneyin.");
        f37213c.put("INVALID_RESOURCE_ID", str);
        f37213c.put("PAYEE_ACCOUNT_INVALID", "Satıcı hesabında onaylı bir e-posta adresi bulunmuyor.");
        f37213c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Bu satıcı şu anda ödeme alamıyor.");
        f37213c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Satıcı hesabında onaylı bir e-posta adresi bulunmuyor.");
        f37213c.put("PAYEE_ACCOUNT_RESTRICTED", "Bu satıcı şu anda ödeme alamıyor.");
        f37213c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Hesabınız kilitli veya kapalı.");
        f37213c.put("PAYER_ACCOUNT_RESTRICTED", "Hesabınız kısıtlandı.");
        f37213c.put("PAYER_CANNOT_PAY", "Bu işlem için PayPal ile ödeme yapamazsınız.");
        f37213c.put("PAYER_EMPTY_BILLING_ADDRESS", "PayPal olmayan kredi kartı işlemleri için fatura adresi gereklidir.");
        f37213c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Kayıtlı kart bilgilerine erişilemiyor.");
        f37213c.put("PAYMENT_APPROVAL_EXPIRED", "Ödeme onayının süresi doldu.");
        f37213c.put("PAYMENT_EXPIRED", "Ödeme süresi sona erdi.");
        f37213c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Ödeyen, ödemeyi onaylamadı.");
        f37213c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal talep numarası geçersiz. Lütfen daha sonra tekrar deneyin.");
        f37213c.put("PAYMENT_STATE_INVALID", "Ödemenin şu anki durumu nedeniyle bu talep geçersizdir.");
        f37213c.put("PERMISSION_DENIED", "Talep edilen işlem için izin yok.");
        f37213c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Talep edilen para iadesi, işlemin tutarını aşıyor.");
        f37213c.put("REFUND_TIME_LIMIT_EXCEEDED", "Bu işlem para iadesi yapılamayacak kadar eski.");
        f37213c.put("REQUIRED_SCOPE_MISSING", str);
        f37213c.put("TOO_MANY_REAUTHORIZATIONS", "Bu yetkilendirme için başka yeniden yetkilendirme yapamazsınız.");
        f37213c.put("TRANSACTION_ALREADY_REFUNDED", "Bu işlem iade edildi.");
        f37213c.put("TRANSACTION_LIMIT_EXCEEDED", "Bu tutar, izin verilen limiti aşıyor.");
        f37213c.put("TRANSACTION_REFUSED", "İşlem reddedildi.");
        f37213c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "İşlem reddedildi.");
        f37213c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Mağaza profili tercihi bazı işlemleri otomatik reddetmek üzere ayarlanmıştır.");
        f37213c.put("UNKNOWN_ERROR", str);
        f37213c.put("UNSUPPORTED_PAYEE_COUNTRY", "Ülkeniz desteklenmiyor.");
        f37213c.put("VALIDATION_ERROR", "Ödeme bilgileri geçersiz. Lütfen düzeltip tekrar gönderin.");
        f37213c.put("ORDER_ALREADY_COMPLETED", "Sipariş geçersiz, süresi doldu veya tamamlandı.");
        f37213c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Sipariş için sağlanan maksimum yetkilendirmeye ulaşıldı.");
        f37213c.put("ORDER_VOIDED", "Siparişiniz geçersiz kılındı.");
        f37213c.put("ORDER_CANNOT_BE_VOIDED", "Sipariş geçersiz kılınamayacak bir durumda.");
        f37213c.put("INVALID_EXPERIENCE_PROFILE_ID", str);
        f37213c.put("UNAUTHORIZED_PAYMENT", "Mağaza bu tür ile yapılan ödemeleri kabul etmiyor.");
        f37213c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Para birimi kart türünde desteklenmiyor.");
        f37213c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kart türü desteklenmiyor.");
        f37213c.put("ADDRESS_ADDITION_ERROR", "PayPal hesabına gönderim adresi eklenirken hata oluştu.");
        f37213c.put("DUPLICATE_TRANSACTION", "Yinelenen işlem.");
        f37213c.put("INVALID_SHIPPING_ADDRESS", "Verilen gönderim adresi geçerli değil.");
        f37213c.put("PAYMENT_CREATION_ERROR", "Bu ödeme ayarlanırken bir sorun oluştu. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Bu ödeme ayarlanırken bir sorun oluştu; kartınızın süresi sona ermiş. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Bu ödeme ayarlanırken bir sorun oluştu; kredi kartı gibi bir anında ödeme yöntemi gerekiyor. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Bu ödeme ayarlanırken bir sorun oluştu; kartın onaylanması gerekiyor. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Bu ödeme ayarlanırken bir sorun oluştu; bu uygulama, hesabınızın bir telefon numarası içermesini gerektiriyor. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Bu ödeme ayarlanırken bir sorun oluştu; hesap için banka veya ödeme kartı gibi geçerli bir ödeme yöntemi gerekiyor. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Bu ödeme ayarlanırken bir sorun oluştu; bakiyeniz ekside. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Bu ödeme ayarlanırken bir sorun oluştu; gönderme limitinize ulaşıldı. Hesabınızı kontrol etmek için lütfen PayPal web sitesini ziyaret edin.");
        f37213c.put("AUTH_RC_RISK_FAILURE", "Riskten dolayı reddedildi.");
        f37213c.put("AUTH_RC_OFAC_BLOCKED_IP", "Yetkisiz müşteri.");
        f37213c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Yetkisiz müşteri.");
        f37213c.put("invalid_user", "Hatalı kullanıcı adı/parola. Lütfen tekrar deneyin.");
        f37213c.put("locked_user", "PayPal hesabınız geçici olarak kilitlendi. Lütfen daha sonra tekrar deneyin veya PayPal hesabınızın kilidini hemen açmak için www.paypal.com adresine gidin.");
        f37213c.put("max_attempts_exceeded", "Çok sayıda başarısız giriş denemesi var. Lütfen daha sonra tekrar deneyin.");
        f37213c.put("invalid_request", "Bir hata oluştu.");
        String str15 = "İstek yetkilendirilmedi.";
        f37213c.put("unauthorized_client", str15);
        f37213c.put("access_denied", str15);
        f37213c.put("unsupported_response_type", "Bir hata oluştu.");
        f37213c.put("invalid_scope", str15);
        f37213c.put("server_error", str);
        f37213c.put("temporarily_unavailable", str);
        f37213c.put("stepup_required", "Giriş işleminiz şu anda tamamlanamadı. Lütfen tekrar deneyin veya PayPal hesabınıza ilişkin herhangi bir güvenlik endişesi konusunda www.paypal.com adresini ziyaret edin.");
        f37213c.put("account_locked_generate_challenge_limit_exceeded", "Çok fazla oturum açma girişimi. Lütfen daha sonra tekrar deneyin veya yardım için PayPal ile iletişime geçin.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "tr";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37212b.containsKey(sb2) ? f37212b.get(sb2) : f37211a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37213c.get(str);
    }
}
