package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.i */
public final class C11830i implements C11857oc {

    /* renamed from: a */
    private static final Map f37231a = new HashMap();

    /* renamed from: b */
    private static final Map f37232b = new HashMap();

    /* renamed from: c */
    private static final Map f37233c = new HashMap();

    public C11830i() {
        f37231a.put(C11761Rb.AGREE_AND_PAY, "同意並付款");
        f37231a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "及其他");
        f37231a.put(C11761Rb.AUTHENTICATING, "認證");
        f37231a.put(C11761Rb.BACK_BUTTON, "返回");
        f37231a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "備用");
        f37231a.put(C11761Rb.CANCEL, "取消");
        f37231a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "美國運通");
        f37231a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37231a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37231a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37231a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37231a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37231a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37231a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37231a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37231a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37231a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37231a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37231a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37231a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37231a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37231a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37231a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "變更付款方式");
        f37231a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "支票");
        f37231a.put(C11761Rb.CHECKING_DEVICE, "正在檢查此裝置…");
        f37231a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "清除信用卡資料");
        f37231a.put(C11761Rb.CONFIRM, "確認");
        f37231a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "確定要清除信用卡資料？");
        f37231a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "對信用卡收費");
        f37231a.put(C11761Rb.CONFIRM_LOG_OUT, "確定要登出 PayPal？");
        f37231a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "付款");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "同意");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "帳戶建立日期");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "帳戶狀態");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "帳戶類型");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "地址");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "年齡層");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "出生日期");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "電郵地址");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "全名");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "性別");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "語言");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "地點");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "電話號碼");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "時區");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "分享以下資料：%s。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "使用流暢結帳功能。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s 要求你：");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "披露連結至你 PayPal 帳戶的<a href='%1$s'>付款方式</a>。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "啟用資金選項顯示，以便你作出選擇。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>授權</a>以 PayPal 支付所有未來在 %2$s 的購物款項。你指示 PayPal 支付所有由 %3$s 發出的付款要求。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "允許他們在 PayPal 錢包新增並管理會員卡。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "同意 %1$s <a href='%2$s'>私隱權政策</a>和<a href='%3$s'>用戶同意書</a>。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "允許他們代表你<a href='%1$s'>要求付款</a>，直至你撤回許可為止。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "允許他們代表你<a href='%1$s'>發出付款</a>，直至你撤回許可為止。");
        f37231a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "贊同");
        f37231a.put(C11761Rb.EMAIL, "電子郵件");
        f37231a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "模擬資料");
        f37231a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37231a.put(C11761Rb.EXPIRES_ON_DATE, "到期");
        f37231a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>付款方式</strong></h1><p>PayPal 只會披露你可以使用的付款方式。</p>");
        f37231a.put(C11761Rb.FORGOT_PASSWORD, "忘記密碼？");
        f37231a.put(C11761Rb.FROM_ACCOUNT, "從");
        f37231a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "未來向 %1$s 付款時要以什麼方式提供資金？");
        f37231a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>未來付款同意書</strong></h1><p>你的預設資金來源將會用作支付此商家的未來 PayPal 付款。</p><p>要取消此同意書，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>我的設定</strong>」&gt;「<strong>以 PayPal 登入</strong>」，並從清單中移除此商家。</p><p>請遵守「<a href='%s'>PayPal 用戶同意書</a>」中的「定時定額付款」部份。</p><p>要確定你的 PayPal 帳戶可順利付款，這個應用程式可能模擬一次小額測試交易，但不會有任何實際資金轉帳。</p>");
        f37231a.put(C11761Rb.INTERNAL_ERROR, "內部錯誤");
        f37231a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>按一下下方按鈕，代表我同意「<a href='%1$s'>PayPal 用戶同意書</a>」的條款並聲明我遵守日本的法律及法例，其中包括依照「<a href='%2$s'>外匯及外國貿易法</a>」，對北韓及伊朗進行的國際制裁以完成交易。</p>");
        f37231a.put(C11761Rb.LOG_IN, "登入");
        String str = "使用 PayPal 登入";
        f37231a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37231a.put(C11761Rb.LOG_OUT_BUTTON, "登出");
        f37231a.put(C11761Rb.LOG_OUT, "登出");
        f37231a.put(C11761Rb.OK, "確定");
        f37231a.put(C11761Rb.PASSWORD, "密碼");
        f37231a.put(C11761Rb.PAY_AFTER_DELIVERY, "送達後付款");
        f37231a.put(C11761Rb.PAY_WITH, "付款方式：");
        f37231a.put(C11761Rb.PAY_WITH_CARD, "使用信用卡付款");
        f37231a.put(C11761Rb.PAYPAL_BALANCE, "PayPal 餘額");
        f37231a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37231a.put(C11761Rb.PHONE, "電話");
        f37231a.put(C11761Rb.PIN, "PIN 碼");
        f37231a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "偏好付款方式");
        f37231a.put(C11761Rb.PRIVACY, "PayPal 保護你的<a href='%s'>私隱</a>和財務資料。");
        f37231a.put(C11761Rb.PROCESSING, "處理中");
        f37231a.put(C11761Rb.REMEMBER_CARD, "記住此卡");
        f37231a.put(C11761Rb.REQUEST_MONEY, "要求付款");
        f37231a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.com 登入帳戶，然後前往「<strong>個人檔案</strong>」設定下的「<strong>使用 PayPal 登入</strong>」選項，並移除該商家。</p><p>對於合作夥伴的任何行動或失誤，PayPal 概不負責。</p>");
        f37231a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "儲蓄");
        f37231a.put(C11761Rb.SEND_MONEY, "支付款項");
        f37231a.put(C11761Rb.SERVER_PROBLEM, "PayPal 伺服器通訊發生問題。請重試。");
        f37231a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "請重新登入 PayPal。");
        f37231a.put(C11761Rb.SESSION_EXPIRED_TITLE, "工作階段到期");
        f37231a.put(C11761Rb.SHIPPING_ADDRESS, "運送地址");
        f37231a.put(C11761Rb.SIGN_UP, "PayPal 新用戶？註冊");
        f37231a.put(C11761Rb.STAY_LOGGED_IN, "保持登入");
        f37231a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "系統錯誤 (%s)。請稍後再試。");
        f37231a.put(C11761Rb.TRY_AGAIN, "重試");
        f37231a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "由於你的帳戶已啟用雙重認證，因此無法登入。");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "安全代碼");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "傳送短訊到你的手機。你收到的 6 位數代碼有效期為 5 分鐘。");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "正在傳送短訊");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "輸入 6 位數安全代碼");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "你的手機號碼");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "傳送短訊");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "再次傳送短訊");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "由於你的帳戶已啟用雙重認證，因此無法登入。請登入 PayPal 網站並啟用安全金匙。");
        f37231a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "不允許從此裝置發出付款。");
        f37231a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "未授權的裝置");
        f37231a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "不允許向此商家付款（無效的 clientId）。");
        f37231a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "無效的商家");
        f37231a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "處理付款時發生問題。請重試。");
        f37231a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "不明來源");
        f37231a.put(C11761Rb.WE_ARE_SORRY, "很抱歉");
        f37231a.put(C11761Rb.YOUR_ORDER, "你的訂單");
        f37231a.put(C11761Rb.ANDROID_OS_TOO_OLD, "這個裝置的 Android 系統版本過舊，因此無法與 PayPal 通訊。請升級 Android 系統，或改用一部較新的裝置。");
        f37231a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "清除信用卡？");
        f37231a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "獲取同意失敗");
        f37231a.put(C11761Rb.CONNECTION_FAILED_TITLE, "連線失敗");
        f37231a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "登入失敗");
        f37231a.put(C11761Rb.LOGIN_WITH_EMAIL, "使用你的密碼登入");
        f37231a.put(C11761Rb.LOGIN_WITH_PHONE, "用 PIN 碼登入");
        f37231a.put(C11761Rb.ONE_MOMENT, "請稍候…");
        f37231a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "付款失敗");
        f37231a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "掃描");
        f37231a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "安全代碼不正確。請重試。");
        f37231a.put(C11761Rb.VIA_LABEL, "透過");
        String str2 = "系統錯誤。請稍後再試。";
        f37231a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "披露連結至你 PayPal 帳戶的<a href='%1$s'>資金來源</a>之相關資料。";
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "代表你披露<a href='%1$s'>資金來源</a>，直至你撤回許可為止。";
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "披露連結至你 PayPal 帳戶的<a href='%1$s'>付款方式</a>之相關資料。";
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "向他們披露連結至你 PayPal 帳戶的<a href='%1$s'>資金來源</a>之相關資料。");
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "披露連結至你 PayPal 帳戶的<a href='%1$s'>資金來源</a>。");
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "披露連結至你 PayPal 帳戶的<a href='%1$s'>資金來源</a>。");
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f37232b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>授權</a>以 PayPal 支付所有未來在 %2$s 的購物款項。你指示 PayPal 支付所有由 %3$s 發出的付款要求。</p><p>請參閱「<a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal 定時定額付款與結帳同意書</a>」以獲得更多資料。</p>");
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>授權</a>以 PayPal 支付所有未來在 %2$s 的購物款項。你指示 PayPal 支付所有由 %3$s 發出的付款要求。</p><p>請參閱「<a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal 定時定額付款與結帳同意書</a>」以獲得更多資料。</p>");
        String str6 = "<a href='%1$s'>授權</a>以 PayPal 支付所有未來的購物款項。你授權及指示 PayPal 支付所有款項。";
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37232b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "預先核准從你的 PayPal 帳戶支付未來的付款，無需每次登入 PayPal。<a href='%1$s'>檢視額外條款</a>，包括付款方式以及取消未來付款的方法。");
        String str7 = "允許 %2$s 代表你<a href='%1$s'>要求付款</a>，直至你撤回許可為止。";
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37232b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "允許 %2$s 代表你<a href='%1$s'>發出付款</a>，直至你撤回許可為止。";
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37232b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>付款方式</strong></h1><p>PayPal 只會披露你可以使用哪些資金來源。</p>";
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>付款方式</strong></h1><p>PayPal 只會披露你可以使用哪些資金來源的相關資料。</p>";
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37232b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>未來付款同意書</strong></h1><p>為確定未來可以對你的 PayPal 帳戶收費，這個應用程式可能模擬一次小額測試交易，測試中不會進行任何資金轉帳。</p><p>你的預設付款方式（是次訂購交易中使用的 PayPal 餘額、已連結的銀行帳戶、扣帳卡或信用卡）將會用作支付 PayPal 購物款項。請留意，若你的預設付款方式沒有足夠的資金去支付購物款項，你的銀行或信用卡供應商可能會向你收取額外費用。</p><p>若要取消此同意書，請登入 PayPal 帳戶並前往「<strong>個人檔案</strong>」，然後在「以 PayPal 登入」旁按一下「<strong>我的設定</strong>」及「<strong>變更</strong>」。</p>");
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>未來付款同意書</strong></h1><p>為確保未來可以對你的 PayPal 帳戶收費，這個應用程式可能模擬一次小額測試交易，測試中不會進行任何付款轉帳。</p><p>你的 PayPal 餘額或主要信用卡又或扣帳卡將會用作支付 PayPal 購物款項。</p><p>要取消此同意書，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>我的設定</strong>」&gt;「<strong>以 PayPal 登入</strong>」，並從清單中移除此商家。</p>");
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>未來付款同意書</strong></h1><p>為確保未來可以對你的 PayPal 帳戶收費，這個應用程式可能模擬一次小額測試交易，測試中不會進行任何付款轉帳。</p><p>你的預設付款方式將會用作支付 PayPal 購物款項。</p><p>要取消此同意書，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>設定</strong>」&gt;「<strong>以 PayPal 登入</strong>」，並從清單中移除此商家。</p>");
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>未來付款同意書</strong></h1><p>你的預設資金來源將會用作支付此商家的未來 PayPal 付款。</p><p>要取消此同意書，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>我的設定</strong>」&gt;「<strong>使用 PayPal 登入</strong>」，並從清單中移除此商家。</p><p>請遵守「<a href='%s'>PayPal 用戶同意書</a>」中的「定時定額付款」部份。</p><p>要確定你的 PayPal 帳戶可順利付款，這個應用程式可能模擬一次小額測試交易，但不會有任何實際資金轉帳。</p>");
        String str11 = "<h1><strong>未來付款授權</strong></h1><p>為確保未來可以對你的 PayPal 帳戶收費，這個應用程式可能模擬一次小額測試交易，測試中不會進行任何付款轉帳。</p><p>你的預設付款方式將會用作支付 PayPal 購物款項。</p><p>要取消此授權，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>我的帳戶設定</strong>」&gt;「<strong>使用 PayPal 登入</strong>」，並從清單中移除此商家。</p><p>請參閱「<a href='%s'>PayPal 用戶同意書</a>」中的「預先核准付款」部份，以獲得更多資料。</p>";
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>未來付款同意書</strong></h1><p>為確保未來可以對你的 PayPal 帳戶收費，這個應用程式可能模擬一次小額測試交易，測試中不會進行任何付款轉帳。</p><p>你的 PayPal 餘額或主要信用卡又或扣帳卡將會用作支付 PayPal 購物款項。</p><p>要取消此同意書，請登入 PayPal 帳戶，前往「<strong>個人檔案</strong>」&gt;「<strong>我的設定</strong>」&gt;「<strong>以 PayPal 登入</strong>」，並從清單中移除此商家。</p>");
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37232b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>未來付款同意書</strong></h1><p>PayPal 將會先使用你的 PayPal 餘額支付購物款項。若 PayPal 餘額不足以支付總額，就會順序使用你的銀行帳戶、PayPal Credit、扣帳卡、信用卡及 / 或電子支票來提供資金。</p><p>要取消此同意書，請前往 www.paypal.com「<strong>個人檔案</strong>」&gt;「<strong>我的設定</strong>」&gt;「<strong>以 PayPal 登入</strong>」，並從清單中移除此商家。</p><p>或許需要小額付款授權，才能確定未來可對你的 PayPal 帳戶收費。授權將會失效，你將不需要支付費用。</p>");
        f37232b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37232b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.com 登入帳戶，然後前往「<strong>個人檔案</strong>」，於「<strong>交易安全專區</strong>」下找出「<strong>使用 PayPal 登入</strong>」，並移除該商家。</p><p>對於商家的任何行動或失誤，PayPal 概不負責。</p>";
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>任何相關的交易詳細資料均會向商家披露。</p><p>如要撤回許可，請登入 PayPal 帳戶並按一下齒輪圖示。前往「<strong>交易安全專區</strong>」，然後選取「<strong>使用 PayPal 登入</strong>」，並移除該合作夥伴。</p><p>對於合作夥伴的任何行動或失誤，PayPal 概不負責。</p>";
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.com 登入帳戶，然後前往「<strong>個人檔案</strong>」設定下的「<strong>使用 PayPal 登入</strong>」選項，並移除該商家。</p><p>對於合作夥伴的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請登入 PayPal 帳戶，然後前往「<strong>個人檔案</strong>」設定下的「<strong>使用 PayPal 登入</strong>」選項，並移除該商家。</p><p>對於商家的任何行動或失誤，PayPal 概不負責。</p>";
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請登入 PayPal 帳戶，然後按一下右上角的齒輪圖示，選取「<strong>交易安全專區</strong>」後， 於「<strong>使用 PayPal 登入</strong>」選項下移除有關商家。如你仍在使用傳統版網站，請前往「<strong>個人檔案</strong>」，選取「<strong>我的帳戶設定</strong>」後，於「<strong>使用 PayPal 登入</strong>」選項下移除有關商家。</p><p>對於商家的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>任何相關的交易詳細資料均會向商家披露。</p><p>如要撤回許可，請登入 PayPal 帳戶，於「<strong>個人檔案</strong>」設定下選取「<strong>使用 PayPal 登入</strong>」，並移除該合作夥伴。</p><p>對於合作夥伴的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.it 登入帳戶，然後前往「<strong>個人檔案</strong>」，於「<strong>交易安全專區</strong>」下找出「<strong>使用 PayPal 登入</strong>」，並移除該商家。</p><p>對於商家的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>任何相關的交易詳細資料均會向商家披露。</p><p>如要撤回許可，請於 paypal.ru 登入帳戶，然後按一下右上角的齒輪圖示，選取「<strong>交易安全專區</strong>」標籤後，於「<strong>使用 PayPal 登入</strong>」選項下移除該合作夥伴。</p><p>對於合作夥伴的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.com.tr 登入帳戶，然後按一下右上角的齒輪圖示，選取「<strong>交易安全專區</strong>」標籤後， 於「<strong>使用 PayPal 登入</strong>」選項下移除該合作夥伴。</p><p>對於商家的任何行動或失誤，PayPal 概不負責。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>任何相關的交易詳情均將會向商家披露。</p><p>如要撤回許可，請於 paypal.com 登入帳戶，然後前往「<strong>個人檔案</strong>」設定下的「<strong>使用 PayPal 登入</strong>」選項，並移除該商家。</p>");
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37232b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37233c.put("AMOUNT_MISMATCH", "購物車物品的總金額與銷售金額不相符。");
        f37233c.put("AUTHORIZATION_ALREADY_COMPLETED", "該授權已完成。");
        f37233c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "授權處於無法作廢的狀態。");
        f37233c.put("AUTHORIZATION_EXPIRED", "授權已到期。");
        f37233c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "要求的授權 ID 不存在。");
        f37233c.put("AUTHORIZATION_VOIDED", "授權已作廢。");
        f37233c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "只能重新授權原交易，授權本身不能重複進行。");
        f37233c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "寬限期內不允許重新授權。");
        f37233c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "金額超出了允許的限額。");
        f37233c.put("CARD_TOKEN_PAYER_MISMATCH", "無法存取已儲存的信用卡資料。");
        f37233c.put("CREDIT_CARD_CVV_CHECK_FAILED", "信用卡資料無效。請更正並重新提交。");
        f37233c.put("CREDIT_CARD_REFUSED", "信用卡被拒絕。");
        f37233c.put("CURRENCY_MISMATCH", "取得資金的貨幣必須與授權貨幣相同。");
        f37233c.put("CURRENCY_NOT_ALLOWED", "PayPal 目前不支援此貨幣。");
        f37233c.put("DATA_RETRIEVAL", str2);
        f37233c.put("DUPLICATE_REQUEST_ID", str2);
        f37233c.put("EXPIRED_CREDIT_CARD", "信用卡已到期");
        f37233c.put("EXPIRED_CREDIT_CARD_TOKEN", "此信用卡的資料已不在檔案中。\n請重新提交。");
        f37233c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "此供應商不支援此功能。");
        f37233c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "此筆交易已進行部分退款。");
        f37233c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "「立即付款」不支援此目的。");
        f37233c.put("INSTRUMENT_DECLINED", "你選擇的付款方式不獲接受。請選擇另一種付款方式。");
        f37233c.put("INSUFFICIENT_FUNDS", "買家無法付款 － 資金不足。");
        f37233c.put("INTERNAL_SERVICE_ERROR", str2);
        f37233c.put("INVALID_ACCOUNT_NUMBER", "帳戶號碼不存在。");
        f37233c.put("INVALID_ARGUMENT", "由於引數無效，因此交易被拒。");
        f37233c.put("INVALID_CITY_STATE_ZIP", "無效的城市 / 州 / 郵遞區號組合。");
        f37233c.put("INVALID_FACILITATOR_CONFIGURATION", "由於支援機構的設定無效，無法處理此筆交易。");
        f37233c.put("INVALID_PAYER_ID", "系統錯誤（無效的付款人 ID）。請稍後再試。");
        f37233c.put("INVALID_RESOURCE_ID", str2);
        f37233c.put("PAYEE_ACCOUNT_INVALID", "供應商帳戶沒有已確認的電郵地址。");
        f37233c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "此供應商目前無法接收付款。");
        f37233c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "供應商帳戶沒有已確認的電郵地址。");
        f37233c.put("PAYEE_ACCOUNT_RESTRICTED", "此供應商目前無法接收付款。");
        f37233c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "你的帳戶已被鎖上或關閉。");
        f37233c.put("PAYER_ACCOUNT_RESTRICTED", "你的帳戶受到限制。");
        f37233c.put("PAYER_CANNOT_PAY", "你無法使用 PayPal 為這宗交易付款。");
        f37233c.put("PAYER_EMPTY_BILLING_ADDRESS", "如要進行非 PayPal 信用卡交易，必須提供帳單地址。");
        f37233c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "無法存取已儲存的信用卡資料。");
        f37233c.put("PAYMENT_APPROVAL_EXPIRED", "付款的核准已到期。");
        f37233c.put("PAYMENT_EXPIRED", "付款已到期。");
        f37233c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "付款人尚未核准付款。");
        f37233c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal 要求號碼無效。請稍後再試。");
        f37233c.put("PAYMENT_STATE_INVALID", "由於付款的目前狀態，此項要求無效。");
        f37233c.put("PERMISSION_DENIED", "不允許進行要求的操作。");
        f37233c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "要求的退款超出了原交易的金額。");
        f37233c.put("REFUND_TIME_LIMIT_EXCEEDED", "此交易日期過久，無法退款。");
        f37233c.put("REQUIRED_SCOPE_MISSING", str2);
        f37233c.put("TOO_MANY_REAUTHORIZATIONS", "不允許對此項授權進行重新授權。");
        f37233c.put("TRANSACTION_ALREADY_REFUNDED", "此筆交易已進行退款。");
        f37233c.put("TRANSACTION_LIMIT_EXCEEDED", "金額超出了允許的限額。");
        f37233c.put("TRANSACTION_REFUSED", "交易被拒。");
        f37233c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "交易被拒。");
        f37233c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "商家個人檔案的偏好設定已設為自動拒絕某些交易。");
        f37233c.put("UNKNOWN_ERROR", str2);
        f37233c.put("UNSUPPORTED_PAYEE_COUNTRY", "不支援你的國家或地區。");
        f37233c.put("VALIDATION_ERROR", "付款資料無效。請更正並重新提交。");
        f37233c.put("ORDER_ALREADY_COMPLETED", "訂購已作廢、已過期或已完成。");
        f37233c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "該訂購的允許授權已達上限。");
        f37233c.put("ORDER_VOIDED", "訂購已作廢。");
        f37233c.put("ORDER_CANNOT_BE_VOIDED", "訂購處於無法作廢的狀態。");
        f37233c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37233c.put("UNAUTHORIZED_PAYMENT", "商家不接受使用此付款類型。");
        f37233c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "信用卡類型不支援的貨幣。");
        f37233c.put("DCC_CC_TYPE_NOT_SUPPORTED", "不支援的信用卡類型。");
        f37233c.put("ADDRESS_ADDITION_ERROR", "將運送地址加入 PayPal 帳戶時發生錯誤。");
        f37233c.put("DUPLICATE_TRANSACTION", "重複交易。");
        f37233c.put("INVALID_SHIPPING_ADDRESS", "你提供的運送地址無效。");
        f37233c.put("PAYMENT_CREATION_ERROR", "設定這筆付款時發生問題。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "設定這筆付款時發生問題 － 你的信用卡已過期。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "設定這筆付款時發生問題 － 必需使用即時付款方式，例如信用卡。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "設定這筆付款時發生問題 － 必須確認信用卡。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "設定這筆付款時發生問題 － 這個應用程式要求你的帳戶必須有電話號碼。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "設定這筆付款時發生問題 － 帳戶需要有效的資金來源，例如銀行帳戶或付款卡。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "設定這筆付款時發生問題 － 你的餘額為負數。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "設定這筆付款時發生問題 － 你已達到付款限額的上限。請前往 PayPal 網站查看你的帳戶。");
        f37233c.put("AUTH_RC_RISK_FAILURE", "由於風險過高，交易已被拒絕。");
        f37233c.put("AUTH_RC_OFAC_BLOCKED_IP", "此客戶未獲授權。");
        f37233c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "此客戶未獲授權。");
        f37233c.put("invalid_user", "用戶名稱／密碼不正確。請重試。");
        f37233c.put("locked_user", "你的 PayPal 帳戶已被暫時封鎖。請稍後再試，或前往 www.paypal.com 立即將你的 PayPal 帳戶解鎖。");
        f37233c.put("max_attempts_exceeded", "登入失敗次數過多。請稍後再試。");
        f37233c.put("invalid_request", "發生錯誤。");
        String str15 = "此項要求未獲授權。";
        f37233c.put("unauthorized_client", str15);
        f37233c.put("access_denied", str15);
        f37233c.put("unsupported_response_type", "發生錯誤。");
        f37233c.put("invalid_scope", str15);
        f37233c.put("server_error", str2);
        f37233c.put("temporarily_unavailable", str2);
        f37233c.put("stepup_required", "系統暫時無法將你登入。請稍後再試。如果你對你的 PayPal 帳戶安全有任何疑慮，請前往 www.paypal.com 回報。");
        f37233c.put("account_locked_generate_challenge_limit_exceeded", "嘗試登入次數過多。請稍後再試，或者聯絡 PayPal 尋求協助。");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "zh-Hant";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37232b.containsKey(sb2) ? f37232b.get(sb2) : f37231a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37233c.get(str);
    }
}
