package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.h */
public final class C11826h implements C11857oc {

    /* renamed from: a */
    private static final Map f37226a = new HashMap();

    /* renamed from: b */
    private static final Map f37227b = new HashMap();

    /* renamed from: c */
    private static final Map f37228c = new HashMap();

    public C11826h() {
        f37226a.put(C11761Rb.AGREE_AND_PAY, "同意并付款");
        f37226a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "和其他");
        f37226a.put(C11761Rb.AUTHENTICATING, "正在验证");
        f37226a.put(C11761Rb.BACK_BUTTON, "返回");
        f37226a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "备用");
        f37226a.put(C11761Rb.CANCEL, "取消");
        f37226a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37226a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37226a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37226a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37226a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37226a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37226a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37226a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37226a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37226a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37226a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37226a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37226a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37226a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37226a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37226a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37226a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "更改付款方式");
        f37226a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "支票");
        f37226a.put(C11761Rb.CHECKING_DEVICE, "正在检查此设备…");
        f37226a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "清除卡信息");
        f37226a.put(C11761Rb.CONFIRM, "确认");
        f37226a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "您确定要清除您的卡信息吗？");
        f37226a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "用卡付款");
        f37226a.put(C11761Rb.CONFIRM_LOG_OUT, "您确定要退出PayPal吗？");
        f37226a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "付款");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "同意");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "账户创建日期");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "账户状态");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "账户类型");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "地址");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "年龄范围");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "出生日期");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "邮箱地址");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "全名");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "性别");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "语言");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "地区");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "电话");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "时区");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "共享以下：%s。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "使用无缝结账。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s要求您：");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "共享与您的PayPal账户关联的<a href='%1$s'>付款方式</a>。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "支持显示您的资金选项，让您可以自由选择。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "对以后用PayPal付款的%2$s购物<a href='%1$s'>授权付款</a>。您授权PayPal支付%3$s请求的所有金额。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "允许他们在您的PayPal钱包中添加并管理他们的积分卡。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "同意%1$s《<a href='%2$s'>隐私权保护规则</a>》和《<a href='%3$s'>用户协议</a>》。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "在您撤回同意前允许他们代表您<a href='%1$s'>收款</a>。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "在您撤回同意前允许他们代表您<a href='%1$s'>付款</a>。");
        f37226a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "同意");
        f37226a.put(C11761Rb.EMAIL, "邮箱地址");
        f37226a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "模拟数据");
        f37226a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37226a.put(C11761Rb.EXPIRES_ON_DATE, "到期：");
        f37226a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>付款方式</strong></h1><p>PayPal仅共享您的哪些付款方式可供使用。</p>");
        f37226a.put(C11761Rb.FORGOT_PASSWORD, "忘了密码？");
        f37226a.put(C11761Rb.FROM_ACCOUNT, "从");
        f37226a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "您希望如何为以后向%1$s的付款提供资金？");
        f37226a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>日后付款协议</strong></h1><p>此商家将使用您的默认资金来源支付日后的PayPal付款。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p><p>此时适用<a href='%s'>PayPal用户协议</a>“循环付款”部分的规定。</p><p>为确保可通过您的PayPal账户付款，此应用程序将模拟一次小型的测试交易，但是不会转移资金。</p>");
        f37226a.put(C11761Rb.INTERNAL_ERROR, "内部错误");
        f37226a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>点击下面的按钮，即表示本人同意<a href='%1$s'>PayPal用户协议</a>的条款，并声明本人遵守日本的法律法规（包括根据<a href='%2$s'>外汇与外贸实施条例</a>对朝鲜和伊朗实施的付款制裁措施）来完成交易。</p>");
        f37226a.put(C11761Rb.LOG_IN, "登录");
        String str = "使用PayPal登录";
        f37226a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37226a.put(C11761Rb.LOG_OUT_BUTTON, "退出");
        f37226a.put(C11761Rb.LOG_OUT, "退出");
        f37226a.put(C11761Rb.OK, "确定");
        f37226a.put(C11761Rb.PASSWORD, "密码");
        f37226a.put(C11761Rb.PAY_AFTER_DELIVERY, "交货后付款");
        f37226a.put(C11761Rb.PAY_WITH, "付款方式");
        f37226a.put(C11761Rb.PAY_WITH_CARD, "用卡付款");
        f37226a.put(C11761Rb.PAYPAL_BALANCE, "PayPal余额");
        f37226a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37226a.put(C11761Rb.PHONE, "电话");
        f37226a.put(C11761Rb.PIN, "识别码");
        f37226a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "首选付款方式");
        f37226a.put(C11761Rb.PRIVACY, "PayPal会保护您的<a href='%s'>隐私</a>和财务信息。");
        f37226a.put(C11761Rb.PROCESSING, "处理中");
        f37226a.put(C11761Rb.REMEMBER_CARD, "记住卡的信息");
        f37226a.put(C11761Rb.REQUEST_MONEY, "收款");
        f37226a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.com，然后转到<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>选项并移除该商家。</p><p>对于合作伙伴执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37226a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "储蓄");
        f37226a.put(C11761Rb.SEND_MONEY, "付款");
        f37226a.put(C11761Rb.SERVER_PROBLEM, "与PayPal服务器通信时发生了问题。请重试。");
        f37226a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "请重新登录到PayPal。");
        f37226a.put(C11761Rb.SESSION_EXPIRED_TITLE, "会话已超时");
        f37226a.put(C11761Rb.SHIPPING_ADDRESS, "送货地址");
        f37226a.put(C11761Rb.SIGN_UP, "尚未注册？注册");
        f37226a.put(C11761Rb.STAY_LOGGED_IN, "保持登录状态");
        f37226a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "系统错误 (%s)。请稍后重试。");
        f37226a.put(C11761Rb.TRY_AGAIN, "重试");
        f37226a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "无法登录，因为您的账户已启用双因素验证。");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "安全码");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "发送短信到您的手机。您收到的6位数代码在5分钟内有效。");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "正在发送短信");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "输入6位数安全代码");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "您的手机号码");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "发送短信");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "重新发送短信");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "无法登录，因为您的账户已启用双因素验证。请访问PayPal网站以激活您的密钥。");
        f37226a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "不允许通过此设备付款。");
        f37226a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "未经授权的设备");
        f37226a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "不允许向此商家付款（客户端ID无效）。");
        f37226a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "无效的商家");
        f37226a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "处理您的付款时遇到了问题。请重试。");
        f37226a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "无法识别的源");
        f37226a.put(C11761Rb.WE_ARE_SORRY, "很抱歉");
        f37226a.put(C11761Rb.YOUR_ORDER, "您的订单");
        f37226a.put(C11761Rb.ANDROID_OS_TOO_OLD, "此设备不能与PayPal通信，因为此版本的Android太旧。请升级Android或尝试较新的设备。");
        f37226a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "清除卡？");
        f37226a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "同意失败");
        f37226a.put(C11761Rb.CONNECTION_FAILED_TITLE, "连接失败");
        f37226a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "登录失败");
        f37226a.put(C11761Rb.LOGIN_WITH_EMAIL, "使用密码登录");
        f37226a.put(C11761Rb.LOGIN_WITH_PHONE, "使用识别码登录");
        f37226a.put(C11761Rb.ONE_MOMENT, "请稍候…");
        f37226a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "付款失败");
        f37226a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "扫描");
        f37226a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "安全代码不正确。请重试。");
        f37226a.put(C11761Rb.VIA_LABEL, "通过");
        String str2 = "系统错误。请稍后重试。";
        f37226a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "共享与您的PayPal账户关联的<a href='%1$s'>资金来源</a>的信息。";
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "在您撤回同意前代表您共享<a href='%1$s'>资金来源</a>。";
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "共享与您的PayPal账户关联的<a href='%1$s'>付款方式</a>的信息。";
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "与他们共享与您的PayPal账户关联的<a href='%1$s'>资金来源</a>的信息。");
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "共享与您的PayPal账户关联的<a href='%1$s'>资金来源</a>。");
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "共享与您的PayPal账户关联的<a href='%1$s'>资金来源</a>。");
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f37227b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>对以后用PayPal付款的%2$s购物<a href='%1$s'>授权付款</a>。您授权PayPal支付%3$s请求的所有金额。</p><p>请阅读<a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal循环付款和结算协议</a>，了解更多信息。</p>");
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>对以后用PayPal付款的%2$s购物<a href='%1$s'>授权付款</a>。您授权PayPal支付%3$s请求的所有金额。</p><p>请阅读<a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal循环付款和结算协议</a>，了解更多信息。</p>");
        String str6 = "对以后用PayPal付款的购物<a href='%1$s'>授权付款</a>。您授权并指示PayPal支付所有金额。";
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37227b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "预先核准通过您的PayPal账户进行日后付款，而不需要每次都登录到PayPal。<a href='%1$s'>查看其他条款</a>，包括付款方式以及如何取消日后付款。");
        String str7 = "在您撤回同意前允许%2$s代表您<a href='%1$s'>收款</a>。";
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37227b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "在您撤回同意前允许%2$s代表您<a href='%1$s'>付款</a>。";
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37227b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>付款方式</strong></h1><p>PayPal仅共享您的哪些资金来源可供使用。</p>";
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>付款方式</strong></h1><p>PayPal共享的信息仅限于您的哪些资金来源可供使用。</p>";
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37227b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>日后付款协议</strong></h1><p>为确保以后可从您的PayPal账户收款，此应用程序将模拟一次小型的测试交易，但是不会转移资金。</p><p>您的默认付款方式（PayPal余额、关联的银行账户、借记卡或信用卡，照此顺序使用）将用于支付PayPal购物款项。请注意，如果您的默认付款方式中没有足够的资金来支付购物款，您的银行或卡提供商可能会向您收取费用。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong>，点击<strong>设置</strong>，再点击“使用PayPal登录”旁边的<strong>更改</strong>。</p>");
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>日后付款协议</strong></h1><p>为确保以后可从您的PayPal账户收款，此应用程序将模拟一次小型的测试交易，但是不会转移资金。</p><p>您的PayPal余额或首选信用卡或借记卡将用于支付PayPal购物款项。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p>");
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>日后付款协议</strong></h1><p>为确保以后可从您的PayPal账户收款，此应用程序将模拟一次小型的测试交易，但是不会转移款项。</p><p>您的默认付款方式将用于支付PayPal购物款项。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p>");
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>日后付款协议</strong></h1><p>您的默认资金来源将用于支付以后在此商家的PayPal付款。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p><p>适用<a href='%s'>PayPal《用户协议》</a>“循环付款”部分的规定。</p><p>为确保可通过您的PayPal账户付款，此应用程序将模拟一次小型的测试交易，但是不会转移资金。</p>");
        String str11 = "<h1><strong>日后付款授权</strong></h1><p>为确保以后可从您的PayPal账户收款，此应用程序将模拟一次小型的测试交易，但是不会转移款项。</p><p>您的默认付款方式将用于支付PayPal购物款项。</p><p>若要取消此授权，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>我的账户设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p><p>如需了解更多信息，请阅读<a href='%s'>PayPal《用户协议》</a>的“预核准付款”部分。</p>";
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>日后付款协议</strong></h1><p>为确保以后可从您的PayPal账户收款，此应用程序将模拟一次小型的测试交易，但是不会转移资金。</p><p>您的PayPal余额或首选信用卡或借记卡将用于支付PayPal购物款项。</p><p>若要取消此协议，请登录到您的PayPal账户，前往<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p>");
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37227b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>日后付款协议</strong></h1><p>PayPal将首先使用您的PayPal余额为购物付款。如果PayPal余额不足，则依次使用您的银行账户、PayPal Credit、借记卡、信用卡以及电子支票。</p><p>若要取消此协议，请前往www.paypal.com<strong>用户信息</strong> &gt; <strong>设置</strong> &gt; <strong>使用PayPal登录</strong>，然后从列表中删除此商家。</p><p>为确保以后可从您的PayPal账户收款，可能需要您提供小额付款授权。授权将被作废，并且不会向您收款。</p>");
        f37227b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37227b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.com，然后转到<strong>用户信息</strong>、<strong>安全</strong>，找到<strong>使用PayPal登录</strong>并移除该商家。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>";
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>将与合作伙伴共享任何相关交易详情。</p><p>要撤回同意，请登录您的PayPal账户并点击齿轮图标。转到<strong>安全</strong>，选择<strong>使用PayPal登录</strong>并移除该合作伙伴。</p><p>对于合作伙伴执行的任何操作或发生的任何错误，PayPal概不负责。</p>";
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.com，然后转到<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>选项并移除该商家。</p><p>对于合作伙伴执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录您的PayPal账户，然后转到您的<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>选项并移除该商家。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>";
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        String str15 = "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录您的PayPal账户，然后转到<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>选项并移除该商家。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>";
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str15);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录您的PayPal账户，点击右上角的齿轮图标，选择<strong>安全中心</strong>，选择<strong>使用PayPal登录</strong>，然后移除该商家。如果您仍在使用经典版网站，请转到<strong>我的用户信息</strong>，选择<strong>我的账户设置</strong>，选择<strong>使用PayPal登录</strong>，然后移除该商家。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>将与合作伙伴共享任何相关交易详情。</p><p>要撤回同意，请登录您的PayPal账户，然后转到<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>并移除该合作伙伴。</p><p>对于合作伙伴执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.it，然后转到<strong>用户信息</strong>、<strong>安全</strong>，找到<strong>使用PayPal登录</strong>并移除该商家。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str15);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>将与合作伙伴共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.ru，点击右上角的齿轮图标，选择<strong>安全</strong>选项卡并在<strong>使用PayPal登录</strong>选项中移除该合作伙伴。</p><p>对于合作伙伴执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str15);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.com.tr，点击右上角的齿轮图标，选择<strong>安全</strong>选项卡并在<strong>使用PayPal登录</strong>选项中移除该合作伙伴。</p><p>对于商家执行的任何操作或发生的任何错误，PayPal概不负责。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>将与商家共享任何相关交易详情。</p><p>要撤回同意，请登录paypal.com，然后转到<strong>用户信息</strong>设置下的<strong>使用PayPal登录</strong>选项并移除该商家。</p>");
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37227b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37228c.put("AMOUNT_MISMATCH", "购物车物品总金额与销售额不符。");
        f37228c.put("AUTHORIZATION_ALREADY_COMPLETED", "此授权已完成。");
        f37228c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "授权处于无法作废的状态。");
        f37228c.put("AUTHORIZATION_EXPIRED", "授权已经到期。");
        f37228c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "请求的授权号不存在。");
        f37228c.put("AUTHORIZATION_VOIDED", "授权已作废。");
        f37228c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "只能重新批准原始授权，而不能重新授权。");
        f37228c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "在支付期内不允许重新授权。");
        f37228c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "金额超出了允许的限额。");
        f37228c.put("CARD_TOKEN_PAYER_MISMATCH", "无法访问保存的卡信息。");
        f37228c.put("CREDIT_CARD_CVV_CHECK_FAILED", "卡信息无效。请更正并重新提交。");
        f37228c.put("CREDIT_CARD_REFUSED", "卡被拒绝。");
        f37228c.put("CURRENCY_MISMATCH", "获取的币种必须与授权的币种一样。");
        f37228c.put("CURRENCY_NOT_ALLOWED", "PayPal目前不支持此币种。");
        f37228c.put("DATA_RETRIEVAL", str2);
        f37228c.put("DUPLICATE_REQUEST_ID", str2);
        f37228c.put("EXPIRED_CREDIT_CARD", "卡已过期");
        f37228c.put("EXPIRED_CREDIT_CARD_TOKEN", "备案中已没有此卡的信息。\n请重新提交。");
        f37228c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "此供应商不支持该功能。");
        f37228c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "此交易的部分款项已退还。");
        f37228c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "传递的意图不支持立即付款。");
        f37228c.put("INSTRUMENT_DECLINED", "您选择的付款方式不被接受。请选择另一种方式。");
        f37228c.put("INSUFFICIENT_FUNDS", "买家无法付款——资金不足。");
        f37228c.put("INTERNAL_SERVICE_ERROR", str2);
        f37228c.put("INVALID_ACCOUNT_NUMBER", "账号不存在。");
        f37228c.put("INVALID_ARGUMENT", "参数无效，交易被拒绝");
        f37228c.put("INVALID_CITY_STATE_ZIP", "市/州/邮编组合无效。");
        f37228c.put("INVALID_FACILITATOR_CONFIGURATION", "由于一个服务商配置无效，此交易无法处理。");
        f37228c.put("INVALID_PAYER_ID", "系统错误（付款人ID无效）。请稍后重试。");
        f37228c.put("INVALID_RESOURCE_ID", str2);
        f37228c.put("PAYEE_ACCOUNT_INVALID", "供应商账户中没有经过确认的邮箱地址。");
        f37228c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "此供应商目前无法接收付款。");
        f37228c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "供应商账户中没有经过确认的邮箱地址。");
        f37228c.put("PAYEE_ACCOUNT_RESTRICTED", "此供应商目前无法接收付款。");
        f37228c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "您的账户已被锁定或注销。");
        f37228c.put("PAYER_ACCOUNT_RESTRICTED", "您的账户已受到限制。");
        f37228c.put("PAYER_CANNOT_PAY", "您不能使用PayPal为此交易付款。");
        f37228c.put("PAYER_EMPTY_BILLING_ADDRESS", "非PayPal信用卡交易需要账单地址。");
        f37228c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "无法访问保存的卡信息。");
        f37228c.put("PAYMENT_APPROVAL_EXPIRED", "付款核准已过期。");
        f37228c.put("PAYMENT_EXPIRED", "付款已过期。");
        f37228c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "付款人未批准付款。");
        f37228c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal请求ID无效。请稍后重试。");
        f37228c.put("PAYMENT_STATE_INVALID", "鉴于当前的付款状态，此请求无效。");
        f37228c.put("PERMISSION_DENIED", "没有权限执行请求的操作。");
        f37228c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "请求的退款金额超出了原始交易金额。");
        f37228c.put("REFUND_TIME_LIMIT_EXCEEDED", "此交易时间太久，无法再退款。");
        f37228c.put("REQUIRED_SCOPE_MISSING", str2);
        f37228c.put("TOO_MANY_REAUTHORIZATIONS", "不允许再重新批准此授权。");
        f37228c.put("TRANSACTION_ALREADY_REFUNDED", "此交易已退款。");
        f37228c.put("TRANSACTION_LIMIT_EXCEEDED", "金额超出了允许的限额。");
        f37228c.put("TRANSACTION_REFUSED", "交易被拒绝。");
        f37228c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "交易被拒绝。");
        f37228c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "商家用户信息习惯设定已设置为自动拒绝某些交易。");
        f37228c.put("UNKNOWN_ERROR", str2);
        f37228c.put("UNSUPPORTED_PAYEE_COUNTRY", "您的国家或地区不受支持。");
        f37228c.put("VALIDATION_ERROR", "付款信息无效。请更正并重新提交。");
        f37228c.put("ORDER_ALREADY_COMPLETED", "订单已作废、过期或完成。");
        f37228c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "该订单已达到允许授权的最大值。");
        f37228c.put("ORDER_VOIDED", "订单已作废。");
        f37228c.put("ORDER_CANNOT_BE_VOIDED", "订单处于无法作废的状态。");
        f37228c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37228c.put("UNAUTHORIZED_PAYMENT", "商家不接受此类型的付款。");
        f37228c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "卡类型不支持该币种。");
        f37228c.put("DCC_CC_TYPE_NOT_SUPPORTED", "卡类型不受支持。");
        f37228c.put("ADDRESS_ADDITION_ERROR", "添加送货地址到PayPal账户时遇到错误。");
        f37228c.put("DUPLICATE_TRANSACTION", "重复交易。");
        f37228c.put("INVALID_SHIPPING_ADDRESS", "提供的送货地址无效。");
        f37228c.put("PAYMENT_CREATION_ERROR", "设置此付款时出现问题。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "设置此付款时出现问题——您的卡已过期。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "设置此付款时出现问题——需要进行即时付款，例如信用卡付款。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "设置此付款时出现问题——卡必须经过确认。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "设置此付款时出现问题——此应用程序要求在账户中登记电话号码。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "设置此付款时出现问题——账户需要有效的资金来源，例如银行账户或支付卡。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "设置此付款时出现问题——您的余额为负数。请访问PayPal网站并检查您的账户。");
        f37228c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "设置此付款时出现问题——您已达到支付限额。请访问PayPal网站并检查您的账户。");
        f37228c.put("AUTH_RC_RISK_FAILURE", "因风险被拒绝。");
        f37228c.put("AUTH_RC_OFAC_BLOCKED_IP", "客户端未获授权。");
        f37228c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "客户端未获授权。");
        f37228c.put("invalid_user", "用户名/密码不正确。请重试。");
        f37228c.put("locked_user", "您的PayPal账户暂时被锁定。请稍后重试，或前往www.paypal.com立即解锁您的PayPal账户。");
        f37228c.put("max_attempts_exceeded", "登录失败次数过多。请稍后重试。");
        f37228c.put("invalid_request", "发生错误。");
        f37228c.put("unauthorized_client", "请求未经授权。");
        f37228c.put("access_denied", "请求未经授权。");
        f37228c.put("unsupported_response_type", "发生错误。");
        f37228c.put("invalid_scope", "请求未经授权。");
        f37228c.put("server_error", str2);
        f37228c.put("temporarily_unavailable", str2);
        f37228c.put("stepup_required", "暂时无法完成您的登录。请稍后重试，或转到www.paypal.com解决任何与您的PayPal账户相关的安全问题。");
        f37228c.put("account_locked_generate_challenge_limit_exceeded", "登录尝试次数过多。请稍后重试，或联系PayPal获取帮助。");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "zh-Hans";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37227b.containsKey(sb2) ? f37227b.get(sb2) : f37226a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37228c.get(str);
    }
}
