package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.f */
public final class C11818f implements C11857oc {

    /* renamed from: a */
    private static final Map f37195a = new HashMap();

    /* renamed from: b */
    private static final Map f37196b = new HashMap();

    /* renamed from: c */
    private static final Map f37197c = new HashMap();

    public C11818f() {
        f37195a.put(C11761Rb.AGREE_AND_PAY, "ยอมรับและชำระเงิน");
        f37195a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "และอื่นๆ");
        f37195a.put(C11761Rb.AUTHENTICATING, "กำลังตรวจสอบความถูกต้อง");
        f37195a.put(C11761Rb.BACK_BUTTON, "ย้อนกลับ");
        f37195a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "สำรอง");
        f37195a.put(C11761Rb.CANCEL, "ยกเลิก");
        f37195a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37195a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37195a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37195a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37195a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37195a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37195a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37195a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37195a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37195a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37195a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37195a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37195a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37195a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37195a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37195a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37195a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "เปลี่ยนวิธีการชำระเงิน");
        f37195a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "กระแสรายวัน");
        f37195a.put(C11761Rb.CHECKING_DEVICE, "กำลังตรวจสอบอุปกรณ์นี้…");
        f37195a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "ลบข้อมูลบัตรทั้งหมด");
        f37195a.put(C11761Rb.CONFIRM, "ยืนยัน");
        f37195a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูลบัตรทั้งหมด");
        f37195a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "ชาร์จการ์ด");
        f37195a.put(C11761Rb.CONFIRM_LOG_OUT, "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ PayPal");
        f37195a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "ชำระเงิน");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "ยอมรับ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "วันที่สร้างบัญชี");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "สถานะบัญชี");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "ประเภทบัญชี");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "ที่อยู่");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "ช่วงอายุ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "วันเดือนปีเกิด");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "ที่อยู่อีเมล");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "ชื่อเต็ม");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "เพศ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "ภาษา");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "ประเทศ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "หมายเลขโทรศัพท์");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "เขตเวลา");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "เปิดเผยข้อมูลต่อไปนี้: %s");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "ใช้การชำระเงินแบบไร้รอยต่อ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s ขอให้คุณ:");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "เปิดเผย<a href='%1$s'>วิธีการชำระเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "เปิดใช้งานการแสดงแหล่งเงิน เพื่อให้คุณสามารถเลือกได้");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>อนุญาตให้เรียกเก็บเงิน</a> สำหรับการซื้อสินค้า %2$s ในอนาคตที่ชำระด้วย PayPal คุณระบุให้ PayPal ชำระเงินทั้งหมดตามที่ %3$s ขอ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "อนุญาตให้เพิ่มและจัดการบัตรตอบแทนลูกค้าสมาชิกในกระเป๋าสตางค์ PayPal ของคุณ");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "ยอมรับ <a href='%2$s'>นโยบายความเป็นส่วนตัว</a> และ <a href='%3$s'>สัญญาสำหรับผู้ใช้บริการ</a> ของ %1$s");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "อนุญาตให้บุคคลดังกล่าว<a href='%1$s'>เรียกเก็บเงิน</a>ในนามของคุณจนกว่าคุณจะเพิกถอนความยินยอม");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "อนุญาตให้บุคคลดังกล่าว<a href='%1$s'>ชำระเงิน</a>ในนามของคุณจนกว่าคุณจะเพิกถอนความยินยอม");
        f37195a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "ความยินยอม");
        f37195a.put(C11761Rb.EMAIL, "อีเมล");
        f37195a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "ข้อมูลจำลอง");
        f37195a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37195a.put(C11761Rb.EXPIRES_ON_DATE, "หมดอายุ");
        f37195a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>วิธีการชำระเงิน</strong></h1><p>PayPal จะเปิดเผยเพียงแค่ว่ามีวิธีการชำระเงินใดบ้างที่สามารถใช้ได้</p>");
        f37195a.put(C11761Rb.FORGOT_PASSWORD, "ลืมรหัสผ่าน");
        f37195a.put(C11761Rb.FROM_ACCOUNT, "จาก");
        f37195a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "คุณต้องการใช้แหล่งเงินใดชำระเงินให้แก่ %1$s ในอนาคต");
        f37195a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>ระบบจะใช้แหล่งเงินที่เป็นค่าดีฟอลต์ของคุณเพื่อชำระเงินด้วย PayPal จากผู้ค้ารายนี้ในอนาคต</p><p>ถ้าต้องการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นไปที่ <strong>‘ข้อมูลบัญชี’</strong> &gt; <strong>‘การตั้งค่าของฉัน’</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal’</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p><p>หัวข้อ ‘การชำระเงินเป็นงวด’ ใน<a href='%s'>สัญญาสำหรับผู้ใช้บริการของ PayPal</a> มีผลกับข้อตกลงนี้</p><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าบัญชี PayPal ของคุณสามารถชำระเงินได้ในอนาคต</p>");
        f37195a.put(C11761Rb.INTERNAL_ERROR, "ข้อผิดพลาดภายใน");
        f37195a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>โดยการคลิกที่ปุ่มด้านล่างนี้ ข้าพเจ้าตกลงยอมรับข้อกำหนดของ <a href='%1$s'>สัญญาสำหรับผู้ใช้บริการของ PayPal</a> และขอยืนยันว่าข้าพเจ้าปฏิบัติตามกฎหมายและข้อบังคับของญี่ปุ่น ซึ่งรวมถึงมาตรการห้ามไม่ให้มีการชำระเงินไปยังเกาหลีเหนือและอิหร่าน ซึ่งเป็นไปตาม <a href='%2$s'>กฎหมายว่าด้วยการแลกเปลี่ยนเงินตราต่างประเทศและการค้าต่างประเทศ</a> เพื่อทำรายการดังกล่าวให้เสร็จสมบูรณ์</p>");
        f37195a.put(C11761Rb.LOG_IN, "เข้าสู่ระบบ");
        String str = "เข้าสู่ระบบด้วย PayPal";
        f37195a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37195a.put(C11761Rb.LOG_OUT_BUTTON, "ออกจากระบบ");
        f37195a.put(C11761Rb.LOG_OUT, "ออกจากระบบ");
        f37195a.put(C11761Rb.OK, "ตกลง");
        f37195a.put(C11761Rb.PASSWORD, "รหัสผ่าน");
        f37195a.put(C11761Rb.PAY_AFTER_DELIVERY, "ชำระเงินหลังจากได้รับสินค้า");
        f37195a.put(C11761Rb.PAY_WITH, "ชำระเงินด้วย");
        f37195a.put(C11761Rb.PAY_WITH_CARD, "ชำระเงินด้วยบัตร");
        f37195a.put(C11761Rb.PAYPAL_BALANCE, "ยอดคงเหลือในบัญชี PayPal");
        f37195a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37195a.put(C11761Rb.PHONE, "โทรศัพท์");
        f37195a.put(C11761Rb.PIN, "PIN");
        f37195a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "วิธีการชำระเงินหลัก");
        f37195a.put(C11761Rb.PRIVACY, "PayPal ปกป้อง<a href='%s'>ความเป็นส่วนตัว</a>และข้อมูลทางการเงินของคุณ");
        f37195a.put(C11761Rb.PROCESSING, "กำลังดำเนินการ");
        f37195a.put(C11761Rb.REMEMBER_CARD, "จำบัตร");
        f37195a.put(C11761Rb.REQUEST_MONEY, "เรียกเก็บเงิน");
        f37195a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.com แล้วไปที่ตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> ใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของพันธมิตร</p>");
        f37195a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "ออมทรัพย์");
        f37195a.put(C11761Rb.SEND_MONEY, "ชำระเงิน");
        f37195a.put(C11761Rb.SERVER_PROBLEM, "เกิดปัญหาในการติดต่อกับเซิร์ฟเวอร์ของ PayPal โปรดลองอีกครั้ง");
        f37195a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "โปรดเข้าสู่ระบบ PayPal อีกครั้ง");
        f37195a.put(C11761Rb.SESSION_EXPIRED_TITLE, "เซสชันหมดเวลา");
        f37195a.put(C11761Rb.SHIPPING_ADDRESS, "ที่อยู่สำหรับจัดส่ง");
        f37195a.put(C11761Rb.SIGN_UP, "ถ้าไม่เคยใช้ PayPal มาก่อน สมัครสมาชิก");
        f37195a.put(C11761Rb.STAY_LOGGED_IN, "อยู่ในระบบต่อไป");
        f37195a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "ระบบเกิดข้อผิดพลาด (%s) โปรดลองอีกครั้งในภายหลัง");
        f37195a.put(C11761Rb.TRY_AGAIN, "โปรดลองอีกครั้ง");
        f37195a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "ไม่สามารถเข้าสู่ระบบได้เนื่องจากบัญชีของคุณเปิดใช้งานการรับรองความถูกต้องด้วยสองปัจจัยอยู่");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "รหัสความปลอดภัย");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "ส่งข้อความไปที่โทรศัพท์ของคุณ รหัส 6 หลักที่คุณได้รับจะใช้ได้เป็นเวลา 5 นาที");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "กำลังส่งข้อความ");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "โปรดป้อนรหัสความปลอดภัย 6 หลัก");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "หมายเลขโทรศัพท์มือถือของคุณ");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "ส่งข้อความ");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "ส่งข้อความอีกครั้ง");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "ไม่สามารถเข้าสู่ระบบได้เนื่องจากบัญชีของคุณเปิดใช้งานการรับรองความถูกต้องด้วยสองปัจจัยอยู่ โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อเปิดใช้รหัสลับความปลอดภัยค่ะ");
        f37195a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "ไม่อนุญาตให้ชำระเงินจากอุปกรณ์นี้");
        f37195a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "อุปกรณ์ไม่ได้รับอนุญาต");
        f37195a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "ไม่อนุญาตให้ชำระเงินให้ผู้ค้ารายนี้ (clientId ไม่ถูกต้อง)");
        f37195a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "ผู้ค้าไม่ถูกต้อง");
        f37195a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "เกิดปัญหาขณะดำเนินการชำระเงินให้คุณ โปรดลองอีกครั้ง");
        f37195a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "ไม่ทราบแหล่งที่มา");
        f37195a.put(C11761Rb.WE_ARE_SORRY, "ขออภัยค่ะ");
        f37195a.put(C11761Rb.YOUR_ORDER, "คำสั่งซื้อของคุณ");
        f37195a.put(C11761Rb.ANDROID_OS_TOO_OLD, "อุปกรณ์นี้ไม่สามารถสื่อสารกับ PayPal ได้เนื่องจาก Andriod เวอร์ชันนี้เก่าเกินไป โปรดอัปเกรด Android หรือลองอุปกรณ์ที่ใหม่กว่า");
        f37195a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "ลบบัตรทั้งหมดหรือไม่");
        f37195a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "ขอความยินยอมไม่สำเร็จ");
        f37195a.put(C11761Rb.CONNECTION_FAILED_TITLE, "เชื่อมต่อไม่สำเร็จ");
        f37195a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "เข้าสู่ระบบไม่สำเร็จ");
        f37195a.put(C11761Rb.LOGIN_WITH_EMAIL, "เข้าสู่ระบบด้วยรหัสผ่าน");
        f37195a.put(C11761Rb.LOGIN_WITH_PHONE, "เข้าสู่ระบบด้วย PIN");
        f37195a.put(C11761Rb.ONE_MOMENT, "โปรดรอสักครู่…");
        f37195a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "ชำระเงินไม่สำเร็จ");
        f37195a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "สแกน");
        f37195a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "รหัสความปลอดภัยไม่ถูกต้อง โปรดลองอีกครั้ง");
        f37195a.put(C11761Rb.VIA_LABEL, "ผ่าน");
        String str2 = "ระบบเกิดข้อผิดพลาด โปรดลองอีกครั้งในภายหลัง";
        f37195a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "เปิดเผยข้อมูลเกี่ยวกับ<a href='%1$s'>แหล่งเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณ";
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "เปิดเผย<a href='%1$s'>แหล่งเงิน</a>ในนามของคุณจนกว่าคุณจะเพิกถอนความยินยอม";
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "เปิดเผยข้อมูลเกี่ยวกับ<a href='%1$s'>วิธีการชำระเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณ";
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "เปิดเผยข้อมูลเกี่ยวกับ<a href='%1$s'>แหล่งเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณให้บุคคลดังกล่าวทราบ");
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "เปิดเผย<a href='%1$s'>แหล่งเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณ");
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "เปิดเผย<a href='%1$s'>แหล่งเงิน</a>ที่เชื่อมโยงอยู่กับบัญชี PayPal ของคุณ");
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f37196b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>อนุญาตให้เรียกเก็บเงิน</a> สำหรับการซื้อสินค้า %2$s ในอนาคตที่ชำระด้วย PayPal คุณระบุให้ PayPal ชำระเงินทั้งหมดตามที่ %3$s ขอ</p><p>โปรดดูข้อมูลเพิ่มเติมใน <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>การชำระเงินเป็นงวดและข้อตกลงการเรียกเก็บเงินของ PayPal</a></p>");
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>อนุญาตให้เรียกเก็บเงิน</a> สำหรับการซื้อสินค้า %2$s ในอนาคตที่ชำระด้วย PayPal คุณระบุให้ PayPal ชำระเงินทั้งหมดตามที่ %3$s ขอ</p><p>โปรดดูข้อมูลเพิ่มเติมใน <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>การชำระเงินเป็นงวดและข้อตกลงการเรียกเก็บเงินของ PayPal</a></p>");
        String str6 = "<a href='%1$s'>อนุญาตให้เรียกเก็บเงิน</a>สำหรับการซื้อสินค้าในอนาคตที่ชำระด้วย PayPal คุณอนุญาตและสั่งให้ PayPal ชำระเงินทุกจำนวน";
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37196b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "อนุญาตการชำระเงินจากบัญชี PayPal ของคุณในอนาคตไว้ล่วงหน้าโดยไม่ต้องเข้าสู่ระบบ PayPal ทุกครั้ง <a href='%1$s'>ดูข้อกำหนดเพิ่มเติม</a> รวมถึงวิธีการชำระเงินและวิธียกเลิกการชำระเงินในอนาคต");
        String str7 = "อนุญาตให้ %2$s <a href='%1$s'>เรียกเก็บเงิน</a>ในนามของคุณจนกว่าคุณจะเพิกถอนความยินยอม";
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37196b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "อนุญาตให้ %2$s <a href='%1$s'>ชำระเงิน</a>ในนามของคุณจนกว่าคุณจะเพิกถอนความยินยอม";
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37196b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>วิธีการชำระเงิน</strong></h1><p>PayPal จะเปิดเผยเพียงว่ามีแหล่งเงินใดบ้างที่สามารถใช้ได้</p>";
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37196b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้วิธีชำระเงินที่เป็นค่าดีฟอลต์ของคุณ (ยอดคงเหลือในบัญชี PayPal ของคุณ, บัญชีธนาคารที่เชื่อมโยงไว้, บัตรเดบิตหรือบัตรเครดิต เรียงตามลำดับ) เพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal ทั้งนี้โปรดทราบว่า ถ้าวิธีชำระเงินที่เป็นค่าดีฟอลต์มีเงินไม่พอสำหรับชำระค่าสินค้าทั้งหมด ธนาคารหรือผู้ออกบัตรอาจเรียกเก็บค่าธรรมเนียมจากคุณ</p><p>ถ้าการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ แล้วไปที่ <strong>‘ข้อมูลบัญชี’</strong> แล้วคลิก <strong>‘การตั้งค่าของฉัน’</strong> แล้วคลิก <strong>‘เปลี่ยน’</strong> ข้าง ‘เข้าสู่ระบบด้วย PayPal’</p>");
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้ยอดคงเหลือในบัญชี PayPal ของคุณ หรือบัตรเครดิตหรือบัตรเดบิตหลัก เพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal</p><p>ถ้าคุณต้องการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ แล้วไปที่ <strong>‘ข้อมูลบัญชี’</strong> &gt; <strong>‘การตั้งค่าของฉัน’</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal’</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p>");
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้วิธีชำระเงินที่เป็นค่าดีฟอลต์ของคุณเพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal</p><p>ถ้าคุณต้องการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นไปที่ <strong>‘ข้อมูลบัญชี’</strong> &gt; <strong>‘การตั้งค่า’</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal’</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p>");
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>ระบบจะใช้แหล่งเงินที่เป็นค่าดีฟอลต์ของคุณเพื่อชำระเงินด้วย PayPal จากผู้ค้ารายนี้ในอนาคต</p><p>ถ้าต้องการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นไปที่ <strong>‘ข้อมูลบัญชี‘</strong> &gt; <strong>‘การตั้งค่าของฉัน‘</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p><p>หัวข้อ ‘การชำระเงินเป็นงวด‘ ใน<a href='%s'>สัญญาสำหรับผู้ใช้บริการของ PayPal</a> มีผลกับข้อตกลงนี้</p><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าบัญชี PayPal ของคุณสามารถชำระเงินได้ในอนาคต</p>");
        String str10 = "<h1><strong>การอนุญาตการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้วิธีชำระเงินที่เป็นค่าดีฟอลต์ของคุณเพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal</p><p>ถ้าคุณต้องการยกเลิกการอนุญาตนี้ ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นไปที่ <strong>‘ข้อมูลบัญชี‘</strong> &gt; <strong>‘การตั้งค่าบัญชีของฉัน‘</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p><p>โปรดดูข้อมูลเพิ่มเติมในหัวข้อ ‘การชำระเงินแบบอนุมัติล่วงหน้า‘ ใน <a href='%s'>สัญญาสำหรับผู้ใช้บริการของ PayPal</a></p>";
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str10);
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>การอนุญาตการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้วิธีชำระเงินที่เป็นค่าดีฟอลต์ของคุณเพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal</p><p>ถ้าคุณต้องการยกเลิกการอนุญาตนี้ ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นไปที่ <strong>‘ข้อมูลบัญชี‘</strong> &gt; <strong>‘การตั้งค่าบัญชีของฉัน‘</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p><p>โปรดดูข้อมูลเพิ่มเติมในหัวข้อ ‘การชำระเงินแบบอนุมัติล่วงหน้า’ ใน <a href='%s'>สัญญาสำหรับผู้ใช้บริการของ PayPal</a></p>");
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>แอปนี้อาจจำลองการทำรายการยอดเล็กๆ เพื่อเป็นการทดสอบโดยไม่มีการโอนเงินจริง เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต</p><p>ระบบจะใช้ยอดคงเหลือในบัญชี PayPal ของคุณ หรือบัตรเครดิตหรือบัตรเดบิตหลัก เพื่อชำระค่าสินค้าที่ซื้อด้วย PayPal</p><p>ถ้าคุณต้องการยกเลิกข้อตกลงนี้ ให้เข้าสู่บัญชี PayPal ของคุณ แล้วไปที่ <strong>‘ข้อมูลบัญชี’</strong> &gt; <strong>‘การตั้งค่าของฉัน’</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal’</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p>");
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str10);
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str10);
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str10);
        f37196b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>ข้อตกลงการชำระเงินในอนาคต</strong></h1><p>PayPal จะใช้ยอดคงเหลือในบัญชี PayPal เพื่อชำระค่าสินค้าก่อน ถ้าไม่พอที่จะชำระยอดรวม จึงจะใช้บัญชีธนาคาร PayPal Credit บัตรเดบิต บัตรเครดิต และ/หรือ eCheck ตามลำดับ</p><p>ถ้าต้องการยกเลิกข้อตกลงนี้ ให้ไปที่ www.paypal.com <strong>‘ข้อมูลบัญชี’</strong> &gt; <strong>‘การตั้งค่าของฉัน’</strong> &gt; <strong>‘เข้าสู่ระบบด้วย PayPal’</strong> แล้วลบผู้ค้ารายนี้ออกจากรายการ</p><p>ทั้งนี้อาจมีการขออนุญาตเรียกเก็บเงินยอดเล็กๆ เพื่อให้มั่นใจว่าจะสามารถเรียกเก็บเงินจากบัญชี PayPal ของคุณได้ในอนาคต โดยการขออนุญาตนี้จะถูกยกเลิกและคุณจะไม่ถูกเรียกเก็บเงินใดๆ</p>");
        f37196b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37196b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str11 = "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.com จากนั้นไปที่ <strong>‘ข้อมูลบัญชี‘</strong> <strong>‘ข้อมูลความปลอดภัย‘</strong> หาคำว่า <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>";
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str11);
        String str12 = "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้พันธมิตรทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม โปรดเข้าสู่บัญชี PayPal ของคุณ จากนั้นคลิกไอคอนรูปเฟือง ไปที่ <strong>‘ข้อมูลความปลอดภัย‘</strong> แล้วเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบพันธมิตรรายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของพันธมิตร</p>";
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str12);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.com แล้วไปที่ตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> ใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของพันธมิตร</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str11);
        String str13 = "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่บัญชี PayPal ของคุณ แล้วไปที่ตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> ใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> ของคุณ แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>";
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str13);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str12);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่บัญชี PayPal ของคุณ แล้วไปที่ตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> ใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>";
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นคลิกไอคอนรูปเฟืองตรงมุมบนขวา แล้วเลือกแท็บ <strong>‘ศูนย์ข้อมูลความปลอดภัย‘</strong> จากนั้นเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออก ถ้าคุณยังใช้เว็บไซต์แบบคลาสสิกอยู่ ให้ไปที่ <strong>‘ข้อมูลบัญชีของฉัน‘</strong> จากนั้นเลือก <strong>‘การตั้งค่าบัญชีของฉัน‘</strong> แล้วเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้พันธมิตรทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่บัญชี PayPal ของคุณ จากนั้นใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> ให้ไปที่ <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของพันธมิตร</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.it จากนั้นไปที่ <strong>‘ข้อมูลบัญชี‘</strong>, <strong>‘ข้อมูลความปลอดภัย‘</strong> หาคำว่า <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบผู้ค้ารายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str13);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str13);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้พันธมิตรทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.ru จากนั้นคลิกไอคอนรูปเฟืองตรงมุมบนขวา แล้วเลือกแท็บ <strong>‘ข้อมูลความปลอดภัย‘</strong> ในตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบพันธมิตรรายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของพันธมิตร</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.com.tr จากนั้นคลิกไอคอนรูปเฟืองตรงมุมบนขวา แล้วเลือกแท็บ <strong>‘ข้อมูลความปลอดภัย‘</strong> ในตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> แล้วลบพันธมิตรรายนี้ออก</p><p>PayPal จะไม่รับผิดชอบต่อการดำเนินการหรือข้อผิดพลาดใดๆ ในส่วนของผู้ค้า</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>เราจะเปิดเผยรายละเอียดการทำรายการใดๆ ก็ตามที่เกี่ยวข้องให้ผู้ค้าทราบ</p><p>ถ้าต้องการเพิกถอนความยินยอม ให้เข้าสู่ระบบที่ paypal.com แล้วไปที่ตัวเลือก <strong>‘เข้าสู่ระบบด้วย PayPal‘</strong> ใต้การตั้งค่า <strong>‘ข้อมูลบัญชี‘</strong> แล้วลบผู้ค้ารายนี้ออก</p>");
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str11);
        f37196b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str11);
        f37197c.put("AMOUNT_MISMATCH", "ยอดรวมของสินค้าในตะกร้าไม่ตรงยอดเงินที่จำหน่าย");
        f37197c.put("AUTHORIZATION_ALREADY_COMPLETED", "การอนุญาตนี้ดำเนินการเสร็จเรียบร้อยไปแล้ว");
        f37197c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "การอนุญาตอยู่ในสถานะที่ไม่สามารถยกเลิกได้");
        f37197c.put("AUTHORIZATION_EXPIRED", "การอนุญาตหมดอายุแล้ว");
        f37197c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "ไม่พบ ID การอนุญาตที่ขอ");
        f37197c.put("AUTHORIZATION_VOIDED", "การอนุญาตถูกยกเลิกแล้ว");
        f37197c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "สามารถอนุญาตใหม่ได้เฉพาะการอนุญาตเดิมเท่านั้น ไม่ใช่กับรายการที่เคยอนุญาตใหม่ไปแล้ว");
        f37197c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "ไม่สามารถอนุญาตใหม่ภายในช่วง Honor Period ได้");
        f37197c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "จำนวนเงินเกินวงเงินที่อนุญาต");
        f37197c.put("CARD_TOKEN_PAYER_MISMATCH", "ไม่สามารถเข้าถึงข้อมูลบัตรที่บันทึกไว้ได้");
        f37197c.put("CREDIT_CARD_CVV_CHECK_FAILED", "ข้อมูลบัตรไม่ถูกต้อง โปรดแก้ไขและส่งข้อมูลอีกครั้ง");
        f37197c.put("CREDIT_CARD_REFUSED", "บัตรถูกปฏิเสธ");
        f37197c.put("CURRENCY_MISMATCH", "สกุลเงินในการตัดยอด (Capture) ต้องเหมือนกับสกุลเงินในการอนุญาต");
        f37197c.put("CURRENCY_NOT_ALLOWED", "PayPal ไม่รองรับสกุลเงินนี้ในขณะนี้");
        f37197c.put("DATA_RETRIEVAL", str2);
        f37197c.put("DUPLICATE_REQUEST_ID", str2);
        f37197c.put("EXPIRED_CREDIT_CARD", "บัตรหมดอายุแล้ว");
        f37197c.put("EXPIRED_CREDIT_CARD_TOKEN", "ไม่มีข้อมูลบัตรใบนี้ในระบบแล้ว\nโปรดส่งข้อมูลอีกครั้ง");
        f37197c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "ฟีเจอร์นี้ไม่ได้รับการรองรับสำหรับผู้ค้ารายนี้");
        f37197c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "การทำรายการนี้ได้รับการคืนเงินบางส่วนไปแล้ว");
        f37197c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Immediate Pay ไม่ได้รับการรองรับสำหรับจุดมุ่งหมายที่ผ่านไปแล้ว");
        f37197c.put("INSTRUMENT_DECLINED", "คุณเลือกวิธีการชำระเงินที่ระบบไม่รับ โปรดเลือกชำระเงินด้วยวิธีอื่น");
        f37197c.put("INSUFFICIENT_FUNDS", "ผู้ซื้อไม่สามารถชำระเงินได้ - เงินไม่พอ");
        f37197c.put("INTERNAL_SERVICE_ERROR", str2);
        f37197c.put("INVALID_ACCOUNT_NUMBER", "ไม่พบเลขที่บัญชีที่ระบุ");
        f37197c.put("INVALID_ARGUMENT", "การทำรายการถูกปฏิเสธเนื่องจากอาร์กิวเมนต์ไม่ถูกต้อง");
        f37197c.put("INVALID_CITY_STATE_ZIP", "เมือง/รัฐ/รหัสไปรษณีย์ไม่ถูกต้อง");
        f37197c.put("INVALID_FACILITATOR_CONFIGURATION", "ไม่สามารถทำรายการนี้ได้เนื่องจาก Facilitator Configuration ไม่ถูกต้อง");
        f37197c.put("INVALID_PAYER_ID", "ระบบเกิดข้อผิดพลาด (ID ผู้ชำระไม่ถูกต้อง) โปรดลองอีกครั้งในภายหลัง");
        f37197c.put("INVALID_RESOURCE_ID", str2);
        f37197c.put("PAYEE_ACCOUNT_INVALID", "บัญชีผู้ค้าไม่มีที่อยู่อีเมลที่ยืนยันแล้ว");
        f37197c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "ผู้ค้ารายนี้ไม่สามารถรับการชำระเงินได้ในขณะนี้");
        f37197c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "บัญชีผู้ค้าไม่มีที่อยู่อีเมลที่ยืนยันแล้ว");
        f37197c.put("PAYEE_ACCOUNT_RESTRICTED", "ผู้ค้ารายนี้ไม่สามารถรับการชำระเงินได้ในขณะนี้");
        f37197c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "บัญชีของคุณถูกล็อคหรือถูกปิด");
        f37197c.put("PAYER_ACCOUNT_RESTRICTED", "บัญชีของคุณถูกจำกัดการใช้งาน");
        f37197c.put("PAYER_CANNOT_PAY", "คุณไม่สามารถชำระเงินสำหรับการทำรายการนี้ผ่าน PayPal ได้");
        f37197c.put("PAYER_EMPTY_BILLING_ADDRESS", "ต้องระบุที่อยู่สำหรับส่งใบเรียกเก็บในการทำรายการผ่านบัตรเครดิตนอก PayPal");
        f37197c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "ไม่สามารถเข้าถึงข้อมูลบัตรที่บันทึกไว้ได้");
        f37197c.put("PAYMENT_APPROVAL_EXPIRED", "การอนุมัติให้ชำระเงินหมดอายุแล้ว");
        f37197c.put("PAYMENT_EXPIRED", "การชำระเงินหมดอายุแล้ว");
        f37197c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "ผู้ชำระไม่ได้อนุมัติให้ชำระเงิน");
        f37197c.put("PAYMENT_REQUEST_ID_INVALID", "ID คำขอของ PayPal ไม่ถูกต้อง โปรดลองอีกครั้งในภายหลัง");
        f37197c.put("PAYMENT_STATE_INVALID", "คำขอนี้ไม่ถูกต้องเนื่องจากสถานะปัจจุบันของการชำระเงิน");
        f37197c.put("PERMISSION_DENIED", "ไม่ได้รับอนุญาตให้ดำเนินการตามที่ขอ");
        f37197c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "จำนวนเงินที่ขอคืนเกินจำนวนเงินของการทำรายการเดิม");
        f37197c.put("REFUND_TIME_LIMIT_EXCEEDED", "การทำรายการนี้นานเกินที่จะคืนเงิน");
        f37197c.put("REQUIRED_SCOPE_MISSING", str2);
        f37197c.put("TOO_MANY_REAUTHORIZATIONS", "ไม่สามารถอนุญาตใหม่สำหรับการอนุญาตนี้ได้อีกแล้ว");
        f37197c.put("TRANSACTION_ALREADY_REFUNDED", "การทำรายการนี้ได้รับการคืนเงินไปแล้ว");
        f37197c.put("TRANSACTION_LIMIT_EXCEEDED", "จำนวนเงินเกินวงเงินที่อนุญาต");
        f37197c.put("TRANSACTION_REFUSED", "การทำรายการถูกปฏิเสธ");
        f37197c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "การทำรายการถูกปฏิเสธ");
        f37197c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "ผู้ค้าตั้งค่าในบัญชีให้ปฏิเสธการทำรายการบางประเภทโดยอัตโนมัติ");
        f37197c.put("UNKNOWN_ERROR", str2);
        f37197c.put("UNSUPPORTED_PAYEE_COUNTRY", "ประเทศของคุณยังไม่มีการรองรับ");
        f37197c.put("VALIDATION_ERROR", "ข้อมูลการชำระเงินไม่ถูกต้อง โปรดแก้ไขและส่งข้อมูลอีกครั้ง");
        f37197c.put("ORDER_ALREADY_COMPLETED", "การสั่งซื้อสินค้าถูกยกเลิก หมดอายุ หรือเสร็จสมบูรณ์แล้ว");
        f37197c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "จำนวนครั้งของการอนุญาตสั่งซื้อสินค้าที่ได้รับอนุญาตถึงขีดจำกัดสูงสุดแล้ว");
        f37197c.put("ORDER_VOIDED", "การสั่งซื้อสินค้าถูกยกเลิกแล้ว");
        f37197c.put("ORDER_CANNOT_BE_VOIDED", "การสั่งซื้อสินค้าอยู่ในสถานะที่ป้องกันไม่ให้มีการยกเลิก");
        f37197c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37197c.put("UNAUTHORIZED_PAYMENT", "ผู้ค้าไม่รับการชำระเงินประเภทนี้");
        f37197c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "ไม่สามารถใช้สกุลเงินนี้กับบัตรประเภทนี้ได้");
        f37197c.put("DCC_CC_TYPE_NOT_SUPPORTED", "ไม่รองรับบัตรประเภทนี้");
        f37197c.put("ADDRESS_ADDITION_ERROR", "เกิดข้อผิดพลาดขณะเพิ่มที่อยู่สำหรับจัดส่งในบัญชี PayPal");
        f37197c.put("DUPLICATE_TRANSACTION", "ทำรายการซ้ำ");
        f37197c.put("INVALID_SHIPPING_ADDRESS", "ที่อยู่สำหรับจัดส่งที่ให้ไว้ไม่ถูกต้อง");
        f37197c.put("PAYMENT_CREATION_ERROR", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - บัตรของคุณหมดอายุแล้ว โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - ต้องชำระเงินแบบทันที เช่น บัตรเครดิต โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - ต้องยืนยันบัตร โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ แอปนี้กำหนดว่าบัญชีของคุณต้องใส่หมายเลขโทรศัพท์ โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - บัญชีต้องการแหล่งเงินที่ถูกต้อง เช่น บัญชีธนาคารหรือบัตรสำหรับชำระเงิน โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - ยอดคงเหลือของคุณติดลบ โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "เกิดปัญหากับการตั้งค่าการชำระเงินรายการนี้ - ยอดคงเหลือของคุณติดลบ โปรดเข้าไปที่เว็บไซต์ PayPal เพื่อตรวจสอบบัญชีของคุณ");
        f37197c.put("AUTH_RC_RISK_FAILURE", "ถูกปฏิเสธเนื่องจากมีความเสี่ยง");
        f37197c.put("AUTH_RC_OFAC_BLOCKED_IP", "ไคลเอนต์ไม่ได้รับอนุญาต");
        f37197c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "ไคลเอนต์ไม่ได้รับอนุญาต");
        f37197c.put("invalid_user", "ชื่อผู้ใช้/รหัสผ่านไม่ถูกต้อง โปรดลองอีกครั้ง");
        f37197c.put("locked_user", "บัญชี PayPal ของคุณถูกล็อคชั่วคราว โปรดลองอีกครั้งในภายหลัง หรือไปที่ www.paypal.com เพื่อปลดล็อคบัญชี PayPal ของคุณในทันที");
        f37197c.put("max_attempts_exceeded", "เข้าสู่ระบบไม่ผ่านหลายครั้งเกินไป โปรดลองอีกครั้งในภายหลัง");
        f37197c.put("invalid_request", "เกิดข้อผิดพลาด");
        String str15 = "คำขอไม่ได้รับอนุญาต";
        f37197c.put("unauthorized_client", str15);
        f37197c.put("access_denied", str15);
        f37197c.put("unsupported_response_type", "เกิดข้อผิดพลาด");
        f37197c.put("invalid_scope", str15);
        f37197c.put("server_error", str2);
        f37197c.put("temporarily_unavailable", str2);
        f37197c.put("stepup_required", "คุณไม่สามารถเข้าสู่ระบบให้เสร็จสมบูรณ์ได้ในขณะนี้ โปรดลองอีกครั้งในภายหลัง หรือไปที่ www.paypal.com เพื่อดูข้อมูลด้านความปลอดภัยเกี่ยวกับบัญชี PayPal ของคุณ");
        f37197c.put("account_locked_generate_challenge_limit_exceeded", "เข้าสู่ระบบไม่ผ่านหลายครั้งเกินไป โปรดลองอีกครั้งในภายหลัง หรือติดต่อ PayPal เพื่อขอความช่วยเหลือค่ะ");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "th";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37196b.containsKey(sb2) ? f37196b.get(sb2) : f37195a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37197c.get(str);
    }
}
