package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.d */
public final class C11800d implements C11857oc {

    /* renamed from: a */
    private static final Map f37153a = new HashMap();

    /* renamed from: b */
    private static final Map f37154b = new HashMap();

    /* renamed from: c */
    private static final Map f37155c = new HashMap();

    public C11800d() {
        f37153a.put(C11761Rb.AGREE_AND_PAY, "Согласиться и оплатить");
        f37153a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "и прочие");
        f37153a.put(C11761Rb.AUTHENTICATING, "Выполняется проверка");
        f37153a.put(C11761Rb.BACK_BUTTON, "Пред.");
        f37153a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Резервный");
        f37153a.put(C11761Rb.CANCEL, "Отмена");
        f37153a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37153a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37153a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37153a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37153a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37153a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37153a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37153a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37153a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37153a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37153a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37153a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37153a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37153a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37153a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37153a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37153a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Изменить способ оплаты");
        f37153a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Проверка");
        f37153a.put(C11761Rb.CHECKING_DEVICE, "Выполняется проверка устройства…");
        f37153a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Очистить данные карты");
        f37153a.put(C11761Rb.CONFIRM, "Подтвердить");
        f37153a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Вы уверены, что хотите очистить сведения о банковской карте?");
        f37153a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Оплатить по карте");
        f37153a.put(C11761Rb.CONFIRM_LOG_OUT, "Выйти из учетной записи PayPal?");
        f37153a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Оплатить");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Соглашаюсь");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Дата создания счета");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Статус счета");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Тип счета");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Адрес");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Возрастной диапазон");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Дата рождения");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Эл. почта");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Полное имя");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Пол");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Язык");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Локаль");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Телефон");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Часовой пояс");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Использовать совместно: %s.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Оцените идеальный процесс оплаты покупок.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s просит вашего разрешения:");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Поделиться информацией о <a href='%1$s'>способах оплаты</a>, привязанных к вашему счету PayPal.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Включите отображение ваших источников средств, чтобы вы могли выбирать при совершении покупок.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Подтвердить списания</a> за будущие покупки через PayPal у продавца %2$s. Вы разрешаете PayPal оплачивать все суммы, запрашиваемые %3$s.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "подключать и управлять дисконтными картами через ваш счет PayPal.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Подтвердить согласие с положениями %1$s <a href='%2$s'>Политики конфиденциальности</a> и <a href='%3$s'>Соглашения с пользователем</a>.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Разрешить им <a href='%1$s'>запрашивать денежные средства</a> от вашего имени, пока вы не аннулируете свое согласие.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Разрешить им <a href='%1$s'>отправлять денежные средства</a> от вашего имени, пока вы не аннулируете свое согласие.");
        f37153a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Согласиться");
        f37153a.put(C11761Rb.EMAIL, "Эл. почта");
        f37153a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Ложные данные");
        f37153a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Изолированная программная среда");
        f37153a.put(C11761Rb.EXPIRES_ON_DATE, "Действует до");
        f37153a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Способы оплаты</strong></h1><p>PayPal делится информацией только о том, какой из ваших способов оплаты доступен для использования.</p>");
        f37153a.put(C11761Rb.FORGOT_PASSWORD, "Забыли пароль?");
        f37153a.put(C11761Rb.FROM_ACCOUNT, "С");
        f37153a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Какой источник средств предпочтительнее для будущих платежей пользователю %1$s?");
        f37153a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для всех будущих платежей через PayPal этот продавец будет использовать ваш источник средств по умолчанию.</p><p>Для отмены данного соглашения войдите в систему PayPal под своим именем и перейдите по вкладке <strong>Профиль</strong> &gt; <strong>Мои настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите этого продавца из списка.</p><p>Будут применены условия раздела о регулярных платежах <a href='%s'>Соглашения с пользователем в отношении услуг PayPal</a>.</p><p>Для проверки работоспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p>");
        f37153a.put(C11761Rb.INTERNAL_ERROR, "Внутренняя ошибка");
        f37153a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Нажимая кнопку ниже, я подтверждаю свое согласие с условиями <a href='%1$s'>Соглашения с пользователем в отношении услуг PayPal</a> и заявляю, что, совершая данную финансовую операцию, действую в соответствии с действующим законодательством Японии, включая санкции в отношении перевода платежей в Северную Корею и Иран в рамках <a href='%2$s'>Закона об обмене валют и зарубежной торговле</a>.</p>");
        f37153a.put(C11761Rb.LOG_IN, "Войти");
        String str = "Войти через PayPal";
        f37153a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37153a.put(C11761Rb.LOG_OUT_BUTTON, "Выход");
        f37153a.put(C11761Rb.LOG_OUT, "Выход");
        f37153a.put(C11761Rb.OK, "ОК");
        f37153a.put(C11761Rb.PASSWORD, "Пароль");
        f37153a.put(C11761Rb.PAY_AFTER_DELIVERY, "Оплата после доставки");
        f37153a.put(C11761Rb.PAY_WITH, "Способ оплаты:");
        f37153a.put(C11761Rb.PAY_WITH_CARD, "Оплатить картой");
        f37153a.put(C11761Rb.PAYPAL_BALANCE, "Остаток на счете PayPal");
        f37153a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37153a.put(C11761Rb.PHONE, "Телефон");
        f37153a.put(C11761Rb.PIN, "PIN-код");
        f37153a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Предпочтительный способ оплаты");
        f37153a.put(C11761Rb.PRIVACY, "PayPal гарантирует защиту ваших <a href='%s'>конфиденциальных данных</a> и финансовой информации.");
        f37153a.put(C11761Rb.PROCESSING, "Выполняется обработка");
        f37153a.put(C11761Rb.REMEMBER_CARD, "Запомнить карту");
        f37153a.put(C11761Rb.REQUEST_MONEY, "Запросить средства");
        f37153a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com, выберите <strong>Войти через PayPal</strong> в разделе <strong>Профиль</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37153a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Сберегательный");
        f37153a.put(C11761Rb.SEND_MONEY, "Отпр. средства");
        f37153a.put(C11761Rb.SERVER_PROBLEM, "Была проблема связи с серверами PayPal. Повторите попытку.");
        f37153a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Войдите в учетную запись PayPal заново.");
        f37153a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Ваш сеанс истек");
        f37153a.put(C11761Rb.SHIPPING_ADDRESS, "Адрес доставки");
        f37153a.put(C11761Rb.SIGN_UP, "Впервые в PayPal? Зарегистрироваться");
        f37153a.put(C11761Rb.STAY_LOGGED_IN, "Не выходить из системы");
        f37153a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Системная ошибка (%s). Повторите попытку позже.");
        f37153a.put(C11761Rb.TRY_AGAIN, "Повторить");
        f37153a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Не удалось выполнить вход, так как для вашего счета включена процедура двухфакторной аутентификации.");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Код безопасности карты");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Отправьте SMS-сообщение на свой номер телефона. 6-значный код, который вы получили, будет действителен в течение 5 минут.");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Отправка SMS-сообщения");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Введите 6-значный код безопасности");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Номер вашего мобильного телефона");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Отправить SMS-сообщение");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Отправить SMS-сообщение еще раз");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Не удалось выполнить вход, так как для вашего счета включена процедура двухфакторной аутентификации. Войдите на веб-сайт PayPal, чтобы активировать ваш ключ безопасности.");
        f37153a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Платежи через данное устройство запрещены.");
        f37153a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Неавторизованное устройство");
        f37153a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Платежи данному продавцу не разрешены (недействительный код клиента).");
        f37153a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Недействительный продавец");
        f37153a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "При обработке платежа произошла ошибка. Повторите попытку.");
        f37153a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Нераспознанный источник");
        f37153a.put(C11761Rb.WE_ARE_SORRY, "Приносим извинения");
        f37153a.put(C11761Rb.YOUR_ORDER, "Ваш заказ");
        f37153a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Данное устройство не может связаться с PayPal, потому что данная версия Android слишком стара. Обновите версию Android или попробуйте более новое устройство.");
        f37153a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Очистить данные карты?");
        f37153a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Не удалось подтвердить согласие");
        f37153a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Соединение не выполнено");
        f37153a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Не удалось войти в систему");
        f37153a.put(C11761Rb.LOGIN_WITH_EMAIL, "Войти в систему при помощи пароля");
        f37153a.put(C11761Rb.LOGIN_WITH_PHONE, "Войти при помощи PIN-кода");
        f37153a.put(C11761Rb.ONE_MOMENT, "Минуточку…");
        f37153a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Не удалось выполнить платеж");
        f37153a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Сканирование");
        f37153a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Неправильный код безопасности. Повторите попытку.");
        f37153a.put(C11761Rb.VIA_LABEL, "через");
        String str2 = "Системная ошибка. Повторите попытку позже.";
        f37153a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "Предоставить информацию об <a href='%1$s'>источниках средств</a>, привязанных к вашему счету PayPal.";
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "Использовать <a href='%1$s'>источники средств</a> от вашего имени, пока вы не аннулируете свое согласие.";
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str5 = "Предоставить информацию о <a href='%1$s'>способах оплаты</a>, указанных в вашем счете PayPal.";
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Предоставить им информацию об <a href='%1$s'>источниках средств</a>, привязанных к вашему счету PayPal.");
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Раскрыть <a href='%1$s'>источники средств</a>, привязанные к вашему счету PayPal.");
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Раскрыть <a href='%1$s'>источники средств</a>, привязанные к вашему счету PayPal.");
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f37154b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Подтвердить списания</a> за будущие покупки через PayPal у продавца %2$s. Вы разрешаете PayPal оплачивать все суммы, запрашиваемые %3$s.</p><p>Для получения дополнительной информации смотрите <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Соглашение PayPal о регулярных платежах и выставлении счетов</a>.</p>");
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Подтвердить списания</a> за будущие покупки через PayPal у продавца %2$s. Вы разрешаете PayPal оплачивать все суммы, запрашиваемые %3$s.</p><p>Для получения дополнительной информации смотрите <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Соглашение PayPal о регулярных платежах и выставлении счетов</a>.</p>");
        String str6 = "<a href='%1$s'>Подтвердить списания</a> за будущие покупки через PayPal. Вы разрешаете PayPal оплачивать все суммы.";
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37154b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Предварительно подтвердите будущие платежи, совершаемые с вашего счета PayPal, не заходя каждый раз в систему PayPal. <a href='%1$s'>См. дополнительные условия</a>, в том числе способы оплаты и отмены будущих платежей.");
        String str7 = "Разрешить партнеру %2$s <a href='%1$s'>запрашивать денежные средства</a> от вашего имени, пока вы не аннулируете свое согласие.";
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37154b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Разрешить партнеру %2$s <a href='%1$s'>отправлять денежные средства</a> от вашего имени, пока вы не аннулируете свое согласие.";
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37154b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>Способы оплаты</strong></h1><p>Компания PayPal предоставляет информацию только о том, какой из ваших источников средств доступен для использования.</p>";
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37154b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для проверки платежеспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p><p>Для оплаты покупок через PayPal будет использован источник средств по умолчанию (в следующем порядке: остаток на вашем счете PayPal, привязанный банковский счет, привязанная банковская карта). Имейте в виду, что если способ оплаты по умолчанию окажется недостаточным для того, что оплатить покупку полностью, то банк или эмитент банковской карты может начислить вам комиссию.</p><p>Для отмены данного соглашения войдите в систему PayPal под своим именем и перейдите к вкладке <strong>Профиль</strong>, затем нажмите <strong>Мои настройки</strong> и <strong>Изменить</strong> (рядом с кнопкой «Войти через PayPal»).</p>");
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для проверки платежеспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p><p>Для оплаты покупок через PayPal будут использоваться остаток на вашем счете PayPal или основная банковская карта.</p><p>Для отмены данного соглашения войдите в систему PayPal под своим именем и перейдите по вкладке <strong>Профиль</strong> &gt; <strong>Мои настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите этого продавца из списка.</p>");
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для проверки платежеспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p><p>Для оплаты покупок через PayPal будет использован источник средств по умолчанию.</p><p>Для отмены данного соглашения войдите в систему PayPal под своим именем и перейдите к вкладке <strong>Профиль</strong> &gt; <strong>Настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите этого продавца из списка.</p>");
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для всех будущих платежей через PayPal этот продавец будет использовать ваш источник средств по умолчанию.</p><p>Для отмены данного соглашения зайдите в счет PayPal, перейдите по вкладке <strong>Профиль</strong> &gt; <strong>Мои настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите продавца из списка.</p><p>Будут применены условия раздела о регулярных платежах <a href='%s'>Соглашения с пользователем в отношении услуг PayPal</a>.</p><p>Для проверки работоспособности вашего счета PayPal это приложение может выполнить небольшую пробную операцию без снятия или перевода денег.</p>");
        String str10 = "<h1><strong>Авторизация будущих платежей</strong></h1><p>Для проверки платежеспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p><p>Для оплаты покупок через PayPal будет использован источник средств по умолчанию.</p><p>Для отмены данного разрешения войдите в систему PayPal под своим именем и перейдите к вкладке <strong>Профиль</strong> &gt; <strong>Настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите этого продавца из списка.</p><p>Для получения дополнительной информации смотрите раздел «Предварительно утвержденные платежи» <a href='%s'>Соглашения с пользователем в отношении услуг PayPal</a>.</p>";
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str10);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str10);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для проверки платежеспособности вашего счета PayPal это приложение может выполнить небольшую тестовую операцию без снятия или перевода денег.</p><p>Для оплаты покупок через PayPal будут использоваться остаток на вашем счете PayPal или основная банковская карта.</p><p>Для отмены данного соглашения войдите в систему PayPal под своим именем и перейдите по вкладке <strong>Профиль</strong> &gt; <strong>Мои настройки</strong> &gt; <strong>Войти через PayPal</strong> и удалите этого продавца из списка.</p>");
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str10);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str10);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str10);
        f37154b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Соглашение о будущих платежах</strong></h1><p>Для оплаты покупки сначала будет использоваться остаток на вашем счете PayPal. Если этой суммы будет недостаточно, чтобы оплатить покупку полностью, будут использоваться другие варианты оплаты в следующем порядке: банковский счет, счет PayPal Credit, дебетовая карта, кредитная карта и/или электронный чек.</p><p>Для отмены данного соглашения перейдите на сайт www.paypal.com: <strong>Профиль</strong> &gt; <strong>Мои настройки</strong> &gt; <strong>Войти через PayPal</strong> — и удалите этого продавца из списка.</p><p>Для проверки платежеспособности вашего счета PayPal может понадобиться авторизация с помощью небольшого платежа. Авторизация будет аннулирована, и средства не будут списаны со счета.</p>");
        f37154b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37154b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str11 = "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com, выберите <strong>Профиль</strong>, <strong>Безопасность</strong>, найдите раздел <strong>Войти через PayPal</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>";
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str11);
        String str12 = "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы партнеру.</p><p>Для отмены согласия войдите в свою учетную запись PayPal и нажмите значок шестеренки. Выберите <strong>Безопасность</strong>, далее <strong>Войти через PayPal</strong>, и удалите данного партнера.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>";
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str12);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com, выберите <strong>Войти через PayPal</strong> в разделе <strong>Профиль</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str11);
        String str13 = "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите в счет PayPal, откройте вкладку <strong>Профиль</strong>, <strong>Войти через PayPal</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>";
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str13);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str12);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите в свой счет, выберите <strong>Войти через PayPal</strong> в разделе <strong>Профиль</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>";
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите в счет PayPal, выберите иконку с шестеренкой в правом верхнем углу, откройте вкладку <strong>Безопасность</strong>, <strong>Войти через PayPal</strong> и удалите данного партнера. Если вы все еще используете классическую версию сайта, то выберите <strong>Мой профиль</strong>, <strong>Настройки счета</strong>, <strong>Войти через PayPal</strong>, и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы партнеру.</p><p>Для отмены согласия зайдите в свой счет, выберите <strong>Войти через PayPal</strong> в разделе <strong>Профиль</strong> и удалите данного партнера.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com.it, выберите <strong>Профиль</strong>, <strong>Безопасность</strong>, найдите раздел <strong>Войти через PayPal</strong> и удалите данного продавца.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str13);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str13);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы партнеру.</p><p>Для отмены согласия зайдите на сайт paypal.ru, выберите иконку с шестеренкой в правом верхнем углу, откройте вкладку <strong>Безопасность</strong> в разделе <strong>Войти через PayPal</strong> и удалите данного партнера.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com.tr, выберите иконку с шестеренкой в правом верхнем углу, откройте вкладку <strong>Безопасность</strong> в разделе <strong>Войти через PayPal</strong> и удалите данного партнера.</p><p>Компания PayPal не несет ответственности за действия или ошибки со стороны продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Любые сведения, относящиеся к операции, будут переданы продавцу.</p><p>Для отмены согласия зайдите на сайт paypal.com, выберите <strong>Войти через PayPal</strong> в разделе <strong>Профиль</strong> и удалите данного продавца.</p>");
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str11);
        f37154b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str11);
        f37155c.put("AMOUNT_MISMATCH", "Общая стоимость товаров в корзине не соответствует сумме продажи.");
        f37155c.put("AUTHORIZATION_ALREADY_COMPLETED", "Авторизация уже выполнена.");
        f37155c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Невозможно аннулировать авторизацию на данном этапе.");
        f37155c.put("AUTHORIZATION_EXPIRED", "Срок авторизации истек.");
        f37155c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Запрашиваемый код авторизации не существует.");
        f37155c.put("AUTHORIZATION_VOIDED", "Ваше разрешение аннулировано.");
        f37155c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Разрешено только повторное подтверждение первоначальной авторизации, а не повторная авторизация.");
        f37155c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Повторное подтверждение не разрешается в течение срока акцептования.");
        f37155c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Сумма превышает допустимый лимит.");
        f37155c.put("CARD_TOKEN_PAYER_MISMATCH", "Не удается получить доступ к сохраненным данным карты.");
        f37155c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Сведения о банковской карте недействительны. Исправьте и попробуйте еще раз.");
        f37155c.put("CREDIT_CARD_REFUSED", "Карта отклонена.");
        f37155c.put("CURRENCY_MISMATCH", "Валюта получения должна совпадать с валютой авторизации.");
        f37155c.put("CURRENCY_NOT_ALLOWED", "Данная валюта в настоящее время не поддерживается в системе PayPal.");
        f37155c.put("DATA_RETRIEVAL", str2);
        f37155c.put("DUPLICATE_REQUEST_ID", str2);
        f37155c.put("EXPIRED_CREDIT_CARD", "Срок действия карты истек.");
        f37155c.put("EXPIRED_CREDIT_CARD_TOKEN", "Данные этой банковской карты были удалены из базы.\nОтправьте еще раз.");
        f37155c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Функция не поддерживается для данного поставщика.");
        f37155c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Средства по этой операции частично возвращены.");
        f37155c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Немедленная оплата не поддерживается.");
        f37155c.put("INSTRUMENT_DECLINED", "Выбранный вами способ оплаты не был принят. Выберите другой способ оплаты.");
        f37155c.put("INSUFFICIENT_FUNDS", "Покупатель не может произвести оплату: недостаточно средств.");
        f37155c.put("INTERNAL_SERVICE_ERROR", str2);
        f37155c.put("INVALID_ACCOUNT_NUMBER", "Такого номера счета не существует.");
        f37155c.put("INVALID_ARGUMENT", "Операция отклонена из-за недопустимой команды.");
        f37155c.put("INVALID_CITY_STATE_ZIP", "Недопустимое сочетание названий города/страны/почтового индекса.");
        f37155c.put("INVALID_FACILITATOR_CONFIGURATION", "Данная операция не может быть обработана вследствие недействительной конфигурации помощника.");
        f37155c.put("INVALID_PAYER_ID", "Системная ошибка (недействительный код плательщика). Повторите попытку позже.");
        f37155c.put("INVALID_RESOURCE_ID", str2);
        f37155c.put("PAYEE_ACCOUNT_INVALID", "Электронный адрес в счете PayPal получателя не подтвержден.");
        f37155c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "В настоящий момент получатель не может принять платеж.");
        f37155c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Электронный адрес в счете PayPal получателя не подтвержден.");
        f37155c.put("PAYEE_ACCOUNT_RESTRICTED", "В настоящий момент получатель не может принять платеж.");
        f37155c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ваш счет заблокирован или закрыт.");
        f37155c.put("PAYER_ACCOUNT_RESTRICTED", "Доступ к вашему счету ограничен.");
        f37155c.put("PAYER_CANNOT_PAY", "Вы не можете совершить данную операцию через PayPal.");
        f37155c.put("PAYER_EMPTY_BILLING_ADDRESS", "Адрес для выставления счета требуется для операций по банковским картам, совершаемых не через PayPal.");
        f37155c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Не удается получить доступ к сохраненным данным карты.");
        f37155c.put("PAYMENT_APPROVAL_EXPIRED", "Истек срок подтверждения платежа.");
        f37155c.put("PAYMENT_EXPIRED", "Истек срок платежа.");
        f37155c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Плательщик не подтвердил платеж.");
        f37155c.put("PAYMENT_REQUEST_ID_INVALID", "Код запроса PayPal недопустим. Повторите попытку позже.");
        f37155c.put("PAYMENT_STATE_INVALID", "Данный запрос недействителен вследствие текущего состояния платежа.");
        f37155c.put("PERMISSION_DENIED", "Требуется разрешение для запрашиваемой операции.");
        f37155c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Требуемое возмещение превышает сумму исходной операции.");
        f37155c.put("REFUND_TIME_LIMIT_EXCEEDED", "Истек срок возмещения по данной операции.");
        f37155c.put("REQUIRED_SCOPE_MISSING", str2);
        f37155c.put("TOO_MANY_REAUTHORIZATIONS", "Больше не допускается повторных подтверждений для данной авторизации.");
        f37155c.put("TRANSACTION_ALREADY_REFUNDED", "Возврат уже осуществлен.");
        f37155c.put("TRANSACTION_LIMIT_EXCEEDED", "Сумма превышает допустимый лимит.");
        f37155c.put("TRANSACTION_REFUSED", "В выполнении операции было отказано.");
        f37155c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "В выполнении операции было отказано.");
        f37155c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Настройки профиля продавца установлены на автоматическое отклонение определенных операций.");
        f37155c.put("UNKNOWN_ERROR", str2);
        f37155c.put("UNSUPPORTED_PAYEE_COUNTRY", "Ваша страна не поддерживается.");
        f37155c.put("VALIDATION_ERROR", "Реквизиты платежа недействительны. Исправьте и попробуйте еще раз.");
        f37155c.put("ORDER_ALREADY_COMPLETED", "Заказ уже был аннулирован, срок его уже истек или он уже был выполнен.");
        f37155c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Достигнуто максимально разрешенное количество авторизаций для заказа.");
        f37155c.put("ORDER_VOIDED", "Заказ был аннулирован.");
        f37155c.put("ORDER_CANNOT_BE_VOIDED", "Заказ находится в состоянии, при котором невозможно аннулирование.");
        f37155c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37155c.put("UNAUTHORIZED_PAYMENT", "Продавец не принимает платежи такого типа.");
        f37155c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Эта валюта не поддерживается для карты данного типа.");
        f37155c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Данный тип банковской карты не поддерживается.");
        f37155c.put("ADDRESS_ADDITION_ERROR", "Произошла ошибка при добавлении адреса доставки к вашему счету PayPal.");
        f37155c.put("DUPLICATE_TRANSACTION", "Дублированная операция.");
        f37155c.put("INVALID_SHIPPING_ADDRESS", "Предоставленный адрес доставки недействителен.");
        f37155c.put("PAYMENT_CREATION_ERROR", "При обработке платежа произошла ошибка. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "При создании платежа произошла ошибка — истек срок действия вашей карты. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "При создании платежа произошла ошибка — требуется мгновенный платеж, например, по кредитной карте. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "При создании платежа произошла ошибка — необходимо подтвердить карту. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "При создании платежа произошла ошибка — для работы приложения необходимо указать номер телефона в учетной записи. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "При создании платежа произошла ошибка — для работы со счетом необходимо указать действительный источник средств, например банковский счет или платежную карту. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "При создании платежа произошла ошибка — у вас отрицательный остаток на счете. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "При создании платежа произошла ошибка — достигнут лимит на отправку средств. Войдите на сайт PayPal, чтобы проверить свой счет.");
        f37155c.put("AUTH_RC_RISK_FAILURE", "Отменено в связи с потенциальным риском.");
        f37155c.put("AUTH_RC_OFAC_BLOCKED_IP", "Клиент не санкционирован.");
        f37155c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Клиент не санкционирован.");
        f37155c.put("invalid_user", "Неправильное имя пользователя/пароль. Повторите попытку.");
        f37155c.put("locked_user", "Ваш счет PayPal временно заблокирован. Повторите попытку позже или перейдите на сайт www.paypal.com для незамедлительного разблокирования счета PayPal.");
        f37155c.put("max_attempts_exceeded", "Превышено количество неудавшихся попыток входа в систему. Повторите попытку позже.");
        f37155c.put("invalid_request", "Возникла ошибка.");
        String str15 = "Запрос не санкционирован.";
        f37155c.put("unauthorized_client", str15);
        f37155c.put("access_denied", str15);
        f37155c.put("unsupported_response_type", "Возникла ошибка.");
        f37155c.put("invalid_scope", str15);
        f37155c.put("server_error", str2);
        f37155c.put("temporarily_unavailable", str2);
        f37155c.put("stepup_required", "Не удается войти в систему в данный момент. Повторите попытку позже или перейдите на www.paypal.com, чтобы выяснить, существуют ли проблемы с безопасностью вашего счета PayPal.");
        f37155c.put("account_locked_generate_challenge_limit_exceeded", "Вы превысили допустимое количество попыток входа в систему. Повторите попытку позже или свяжитесь с PayPal, если вам нужна помощь.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "ru";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37154b.containsKey(sb2) ? f37154b.get(sb2) : f37153a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37155c.get(str);
    }
}
