package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.e */
public final class C11808e implements C11857oc {

    /* renamed from: a */
    private static final Map f37177a = new HashMap();

    /* renamed from: b */
    private static final Map f37178b = new HashMap();

    /* renamed from: c */
    private static final Map f37179c = new HashMap();

    public C11808e() {
        f37177a.put(C11761Rb.AGREE_AND_PAY, "Godkänn och betala");
        f37177a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "och annan");
        f37177a.put(C11761Rb.AUTHENTICATING, "Autentisering utförs");
        f37177a.put(C11761Rb.BACK_BUTTON, "Tillbaka");
        f37177a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Reservmetod");
        f37177a.put(C11761Rb.CANCEL, "Avbryt");
        f37177a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37177a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37177a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37177a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37177a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37177a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37177a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37177a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37177a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37177a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37177a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37177a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37177a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37177a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37177a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37177a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37177a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Ändra betalningsmetod");
        f37177a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Lönekonto");
        f37177a.put(C11761Rb.CHECKING_DEVICE, "Enheten kontrolleras …");
        f37177a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Ta bort kortuppgifter");
        f37177a.put(C11761Rb.CONFIRM, "Bekräfta");
        f37177a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Vill du ta bort kortuppgifterna?");
        f37177a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Debitera kort");
        f37177a.put(C11761Rb.CONFIRM_LOG_OUT, "Vill du logga ut från PayPal?");
        f37177a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Betala");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Godkänn");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Datum då kontot skapades");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotyp");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adress");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Åldersintervall");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Födelsedatum");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadress");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullständigt namn");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kön");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Språk");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Språkinställning");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidszon");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Dela det här: %s.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Betala smidigt.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s ber dig att:");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Dela <a href='%1$s'>betalningsmetoderna</a> som är kopplade till ditt PayPal-konto.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktivera visning av dina betalningsalternativ så att du kan välja mellan dem.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Tillåt att de lägger till och hanterar sina lojalitetskort i din PayPal-e-plånbok.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "godkänna <a href='%2$s'>sekretesspolicyn</a> och <a href='%3$s'>användaravtalet</a> för %1$s.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Tillåt dem att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Tillåt dem att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.");
        f37177a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Medgivande");
        f37177a.put(C11761Rb.EMAIL, "E-post");
        f37177a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Exempeldata");
        f37177a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37177a.put(C11761Rb.EXPIRES_ON_DATE, "Går ut");
        f37177a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilken av dina betalningsmetoder som ska användas.</p>");
        f37177a.put(C11761Rb.FORGOT_PASSWORD, "Har du glömt lösenordet?");
        f37177a.put(C11761Rb.FROM_ACCOUNT, "Från");
        f37177a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "På vilket sätt vill du göra framtida betalningar till %1$s?");
        f37177a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett för den här handlaren.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Avsnittet Återkommande betalningar i <a href='%s'>PayPals användaravtal</a> gäller.</p><p>Appen simulerar eventuellt en liten testtransaktion för att se till att du kan göra betalningar från ditt PayPal-konto, men inga pengar överförs.</p>");
        f37177a.put(C11761Rb.INTERNAL_ERROR, "Internt fel");
        f37177a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Genom att klicka på knappen godtar jag villkoren i <a href='%1$s'>PayPals användaravtal</a> och intygar att jag följer japanska lagar och regleringar, inklusive sanktionerna mot betalningar till Nordkorea och Iran enligt <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> för att slutföra transaktionen.</p>");
        f37177a.put(C11761Rb.LOG_IN, "Logga in");
        String str = "Logga in med PayPal";
        f37177a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37177a.put(C11761Rb.LOG_OUT_BUTTON, "Logga ut");
        f37177a.put(C11761Rb.LOG_OUT, "Logga ut");
        f37177a.put(C11761Rb.OK, "OK");
        f37177a.put(C11761Rb.PASSWORD, "Lösenord");
        f37177a.put(C11761Rb.PAY_AFTER_DELIVERY, "Betala efter leverans");
        f37177a.put(C11761Rb.PAY_WITH, "Betala med");
        f37177a.put(C11761Rb.PAY_WITH_CARD, "Betala med kort");
        f37177a.put(C11761Rb.PAYPAL_BALANCE, "PayPal-saldo");
        f37177a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37177a.put(C11761Rb.PHONE, "Telefon");
        f37177a.put(C11761Rb.PIN, "Pinkod");
        f37177a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Favoritbetalningsmetod");
        f37177a.put(C11761Rb.PRIVACY, "PayPal skyddar dina <a href='%s'>personliga uppgifter</a> och dina betalningsuppgifter.");
        f37177a.put(C11761Rb.PROCESSING, "Behandling");
        f37177a.put(C11761Rb.REMEMBER_CARD, "Kom ihåg kort");
        f37177a.put(C11761Rb.REQUEST_MONEY, "Be om betalning");
        f37177a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f37177a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparkonto");
        f37177a.put(C11761Rb.SEND_MONEY, "Överföra pengar");
        f37177a.put(C11761Rb.SERVER_PROBLEM, "Det gick inte att kommunicera med PayPal-servrarna. Försök igen.");
        f37177a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Logga in på PayPal igen.");
        f37177a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sessionen har upphört att gälla");
        f37177a.put(C11761Rb.SHIPPING_ADDRESS, "Leveransadress");
        f37177a.put(C11761Rb.SIGN_UP, "Har du inte använt PayPal förut? Skapa konto");
        f37177a.put(C11761Rb.STAY_LOGGED_IN, "Fortsätt att vara inloggad");
        f37177a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Systemfel (%s). Försök igen senare.");
        f37177a.put(C11761Rb.TRY_AGAIN, "Försök igen");
        f37177a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Det gick inte att logga in eftersom tvåfaktorautentisering har aktiverats för ditt konto.");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Säkerhetskod");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Skicka ett sms till din mobiltelefon. Den sexsiffriga koden du får är giltig i 5 minuter.");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Skicka sms");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Ange den sexsiffriga säkerhetskoden");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ditt mobilnummer");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Skicka sms");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Skicka sms igen");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Det gick inte att logga in eftersom tvåfaktorautentisering har aktiverats för ditt konto. Gå till PayPals webbplats för att aktivera säkerhetsnyckeln.");
        f37177a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Betalningar från den här enheten är inte tillåtna.");
        f37177a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Obehörig enhet");
        f37177a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalningar till den här handlaren medges inte (ogiltigt klient-id).");
        f37177a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Ogiltig handlare");
        f37177a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Det gick inte att behandla din betalning. Försök igen.");
        f37177a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Okänd betalningsmetod");
        f37177a.put(C11761Rb.WE_ARE_SORRY, "Tyvärr");
        f37177a.put(C11761Rb.YOUR_ORDER, "Din order");
        f37177a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Den här enheten kan inte kommunicera med PayPal eftersom den här versionen av Android är för gammal. Uppgradera Android eller försök med en nyare enhet.");
        f37177a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Vill du ta bort kortet?");
        f37177a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Samtycke misslyckades");
        f37177a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Anslutningen misslyckades");
        f37177a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Inloggningen misslyckades");
        f37177a.put(C11761Rb.LOGIN_WITH_EMAIL, "Logga in med ditt lösenord");
        f37177a.put(C11761Rb.LOGIN_WITH_PHONE, "Logga in med din pinkod");
        f37177a.put(C11761Rb.ONE_MOMENT, "Ett ögonblick …");
        f37177a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Betalningen misslyckades");
        f37177a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Skanna");
        f37177a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Felaktig säkerhetskod. Försök igen.");
        f37177a.put(C11761Rb.VIA_LABEL, "Via");
        String str2 = "Systemfel. Försök igen senare.";
        f37177a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "Dela information om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.";
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        String str4 = "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.";
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str4);
        String str5 = "Dela <a href='%1$s'>betalningsalternativen</a> för din räkning tills du drar tillbaka ditt medgivande.";
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str6 = "Dela information om de <a href='%1$s'>betalningsmetoder</a> som är kopplade till ditt PayPal-konto.";
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str6);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Dela information med dem om de <a href='%1$s'>betalningsalternativ</a> som är kopplade till ditt PayPal-konto.");
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Dela <a href='%1$s'>betalningsalternativen</a> som är kopplade till ditt PayPal-konto.");
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Dela <a href='%1$s'>betalningsalternativen</a> som är kopplade till ditt PayPal-konto.");
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str4);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str6);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str4);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str6);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str5);
        f37178b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str5);
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.</p><p>Mer information finns i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtal om återkommande betalningar och fakturering</a>.</p>");
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkänna avgifter</a> för framtida köp hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som begärs av %3$s.</p><p>Mer information finns i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtal om återkommande betalningar och fakturering</a>.</p>");
        String str7 = "<a href='%1$s'>Godkänn att pengar dras</a> för framtida köp som betalas med PayPal. Du ber PayPal betala alla belopp och godkänner detta.";
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str7);
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str7);
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str7);
        f37178b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Godkänn på förhand framtida betalningar från ditt PayPal-konto utan att logga in på PayPal varje gång. <a href='%1$s'>Se fler villkor</a>, inklusive betalningsmetoder och information om hur du avbryter framtida betalningar.");
        String str8 = "Tillåt %2$s att <a href='%1$s'>be om betalning</a> för din räkning tills du drar tillbaka ditt medgivande.";
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str8);
        f37178b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str8);
        String str9 = "Tillåt %2$s att <a href='%1$s'>överföra pengar</a> för din räkning tills du drar tillbaka ditt medgivande.";
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str9);
        f37178b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str9);
        String str10 = "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan användas.</p>";
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str10);
        f37178b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str10);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Med appen simuleras eventuellt en liten testtransaktion för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard (PayPal-saldo, kopplat bankkonto eller betalkort, i den ordningen). Tänk på att banken eller kortutfärdaren kan ta ut en avgift om det inte finns tillräckligt med pengar för att täcka köpet.</p><p>Om du vill upphäva avtalet loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong>. Klicka sedan på <strong>Mina inställningar</strong> och <strong>Ändra</strong> bredvid ”Logga in med PayPal”.</p>");
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med ditt PayPal-saldo eller ditt primära betalkort.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill upphäva avtalet loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong> &gt; <strong>Inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett för den här handlaren.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Avsnittet Återkommande betalningar i <a href='%s'>PayPals användaravtal</a> gäller.</p><p>Appen simulerar eventuellt en liten testtransaktion för att se till att du kan göra betalningar från ditt PayPal-konto, men inga pengar överförs.</p>");
        String str11 = "<h1><strong>Godkännande för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godkännandet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina kontoinställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p><p>Mer information finns i avsnittet ”Förgodkända betalningar” i <a href='%s'>PayPals användaravtal</a>.</p>";
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen för att se till att ditt PayPal-konto kan debiteras senare, men inga pengar överförs.</p><p>PayPal-köpen betalas med ditt PayPal-saldo eller ditt primära betalkort.</p><p>Om du vill upphäva avtalet loggar du in på PayPal-kontot och går till <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren från listan.</p>");
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37178b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Avtal för framtida betalningar</strong></h1><p>Vid köp dras pengar först från ditt PayPal-saldo. Om det inte täcker summan dras resterande summa från ditt bankkonto, PayPal Credit, betalkort, och/eller eCheck, i den ordningen.</p><p>Gå till www.paypal.com <strong>Min profil</strong> &gt; <strong>Mina inställningar</strong> &gt; <strong>Logga in med PayPal</strong> och ta bort handlaren från listan om du vill upphäva avtalet.</p><p>Det kan hända att en mindre betalning måste godkännas för att ditt PayPal-konto ska kunna debiteras i framtiden. Godkännandet annulleras sedan och du debiteras inte.</p>");
        f37178b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37178b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str12 = "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>";
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen. Gå till <strong>Säkerhet</strong>, välj <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>";
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>";
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och klickar på kugghjulssymbolen längst upp till höger. Välj sedan <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och tar bort handlaren. Om du fortfarande använder den gamla vyn ska du gå till <strong>Min profil</strong>, välja <strong>Mina kontoinställningar</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på ditt PayPal-konto och går till <strong>Min profil</strong> och tar sedan bort partnern under <strong>Logga in med PayPal</strong>.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.it och går till <strong>Min profil</strong>. Välj sedan fliken <strong>Säkerhet</strong>, gå till <strong>Logga in med PayPal</strong> och ta bort den här handlaren.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.ru och klickar på kugghjulssymbolen längst upp till höger. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från partnerns sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com.tr och klickar på kugghjulssymbolen längst upp till höger. Välj sedan fliken <strong>Säkerhet</strong>, gå till avsnittet <strong>Logga in med PayPal</strong> och ta bort den här partnern.</p><p>PayPal ansvarar inte för åtgärder eller fel från handlarens sida.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in på paypal.com och går till avsnittet <strong>Logga in med PayPal</strong> under inställningarna för <strong>Min profil</strong> och tar bort handlaren.</p>");
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37178b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37179c.put("AMOUNT_MISMATCH", "Totalbeloppet för objekten i kundvagnen matchar inte försäljningsbeloppet.");
        f37179c.put("AUTHORIZATION_ALREADY_COMPLETED", "Godkännandet har redan slutförts.");
        f37179c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkännandets nuvarande status gör att det inte kan annulleras.");
        f37179c.put("AUTHORIZATION_EXPIRED", "Godkännandet har gått ut.");
        f37179c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det id för godkännande som har begärts finns inte.");
        f37179c.put("AUTHORIZATION_VOIDED", "Ditt godkännande har annullerats.");
        f37179c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Det går endast att omgodkänna det ursprungliga godkännandet, inte ett omgodkännande.");
        f37179c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Det är inte tillåtet att omgodkänna inom garantiperioden.");
        f37179c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beloppet överskrider den tillåtna gränsen.");
        f37179c.put("CARD_TOKEN_PAYER_MISMATCH", "Det gick inte att komma åt de sparade kortuppgifterna.");
        f37179c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortuppgifterna är ogiltiga. Korrigera och skicka igen.");
        f37179c.put("CREDIT_CARD_REFUSED", "Kortet nekades.");
        f37179c.put("CURRENCY_MISMATCH", "Inkasseringsvalutan måste vara samma som valutan för godkännandet.");
        f37179c.put("CURRENCY_NOT_ALLOWED", "Den här valutan stöds inte för närvarande av PayPal.");
        f37179c.put("DATA_RETRIEVAL", str2);
        f37179c.put("DUPLICATE_REQUEST_ID", str2);
        f37179c.put("EXPIRED_CREDIT_CARD", "Kortet har upphört att gälla");
        f37179c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informationen för det här kortet finns inte längre sparad.\nSkicka igen.");
        f37179c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktionen stöds inte för betalningsmottagaren.");
        f37179c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Transaktionen har delvis återbetalats.");
        f37179c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Direktbetalning stöds inte för det här.");
        f37179c.put("INSTRUMENT_DECLINED", "Den betalningsmetod du valde godkändes inte. Välj en annan betalningsmetod.");
        f37179c.put("INSUFFICIENT_FUNDS", "Köparen kan inte betala – pengar saknas.");
        f37179c.put("INTERNAL_SERVICE_ERROR", str2);
        f37179c.put("INVALID_ACCOUNT_NUMBER", "Kontonumret finns inte.");
        f37179c.put("INVALID_ARGUMENT", "Transaktionen nekades på grund av ett ogiltigt argument");
        f37179c.put("INVALID_CITY_STATE_ZIP", "Ogiltig kombination av ort/delstat/postnummer.");
        f37179c.put("INVALID_FACILITATOR_CONFIGURATION", "Den här transaktionen kan inte behandlas på grund av ogiltig konfiguration hos partnern.");
        f37179c.put("INVALID_PAYER_ID", "Systemfel (betalarens id är ogiltigt). Försök igen senare.");
        f37179c.put("INVALID_RESOURCE_ID", str2);
        f37179c.put("PAYEE_ACCOUNT_INVALID", "Det finns ingen bekräftad e-postadress för betalningsmottagarens konto.");
        f37179c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Den här säljaren kan inte ta emot betalningar just nu.");
        f37179c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Det finns ingen bekräftad e-postadress för betalningsmottagarens konto.");
        f37179c.put("PAYEE_ACCOUNT_RESTRICTED", "Den här säljaren kan inte ta emot betalningar just nu.");
        f37179c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ditt konto är spärrat eller stängt.");
        f37179c.put("PAYER_ACCOUNT_RESTRICTED", "Ditt konto är begränsat.");
        f37179c.put("PAYER_CANNOT_PAY", "Du kan inte betala den här transaktionen med PayPal.");
        f37179c.put("PAYER_EMPTY_BILLING_ADDRESS", "Faktureringsadress krävs för korttransaktioner som inte görs med PayPal.");
        f37179c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Det gick inte att komma åt de sparade kortuppgifterna.");
        f37179c.put("PAYMENT_APPROVAL_EXPIRED", "Godkännandet av betalningen har upphört att gälla.");
        f37179c.put("PAYMENT_EXPIRED", "Betalningen har upphört att gälla.");
        f37179c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betalaren inte har godkänt betalningen.");
        f37179c.put("PAYMENT_REQUEST_ID_INVALID", "PayPals id för begäran är ogiltigt. Försök igen senare.");
        f37179c.put("PAYMENT_STATE_INVALID", "Denna begäran är ogiltig på grund av betalningens nuvarande status.");
        f37179c.put("PERMISSION_DENIED", "Det finns inget tillstånd för den begärda åtgärden.");
        f37179c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den begärda återbetalningen överskrider beloppet för den ursprungliga transaktionen.");
        f37179c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transaktionen är för gammal för att återbetalas.");
        f37179c.put("REQUIRED_SCOPE_MISSING", str2);
        f37179c.put("TOO_MANY_REAUTHORIZATIONS", "Inga fler omgodkännanden är tillåtna för det här godkännandet.");
        f37179c.put("TRANSACTION_ALREADY_REFUNDED", "Transaktionen har redan återbetalats.");
        f37179c.put("TRANSACTION_LIMIT_EXCEEDED", "Beloppet överskrider den tillåtna gränsen.");
        f37179c.put("TRANSACTION_REFUSED", "Transaktionen nekades.");
        f37179c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaktionen nekades.");
        f37179c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Handlarens profil är inställd på att automatiskt neka vissa transaktioner.");
        f37179c.put("UNKNOWN_ERROR", str2);
        f37179c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet stöds inte.");
        f37179c.put("VALIDATION_ERROR", "Betalningsuppgifterna är ogiltiga. Korrigera och skicka igen.");
        f37179c.put("ORDER_ALREADY_COMPLETED", "Beställningen har redan annullerats, gått ut eller slutförts.");
        f37179c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Högsta antal tillåtna tillstånd för beställningen har uppnåtts.");
        f37179c.put("ORDER_VOIDED", "Din order har annullerats.");
        f37179c.put("ORDER_CANNOT_BE_VOIDED", "Beställningen är i ett skede som inte medger annullering.");
        f37179c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37179c.put("UNAUTHORIZED_PAYMENT", "Handlaren tar inte emot den här betalningstypen.");
        f37179c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valutan stöds inte för korttypen.");
        f37179c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen stöds inte.");
        f37179c.put("ADDRESS_ADDITION_ERROR", "Fel påträffades när en leveransadress skulle läggas till PayPal-kontot.");
        f37179c.put("DUPLICATE_TRANSACTION", "Dubblettransaktion.");
        f37179c.put("INVALID_SHIPPING_ADDRESS", "Den angivna leveransadressen är ogiltig.");
        f37179c.put("PAYMENT_CREATION_ERROR", "Det uppstod ett problem när betalningen skulle registreras. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det uppstod ett problem när betalningen skulle registreras – kortet har upphört att gälla. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det uppstod ett problem när betalningen skulle registreras – direktbetalning krävs, t.ex. med ett betalkort. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det uppstod ett problem när betalningen skulle registreras – kortet måste bekräftas. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det uppstod ett problem när betalningen skulle registreras – kontot måste innehålla ett telefonnummer enligt villkoren för appen. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det uppstod ett problem när betalningen skulle registreras – kontot behöver en giltig betalningsmetod, t.ex. ett bankkonto eller betalkort. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det uppstod ett problem när betalningen skulle registreras – saldot är övertrasserat. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det uppstod ett problem när betalningen skulle registreras – du har kommit upp till överföringsgränsen. Kontrollera ditt konto på PayPals webbplats.");
        f37179c.put("AUTH_RC_RISK_FAILURE", "Nekad på grund av risk.");
        f37179c.put("AUTH_RC_OFAC_BLOCKED_IP", "Obehörig klient.");
        f37179c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Obehörig klient.");
        f37179c.put("invalid_user", "Fel användarnamn/lösenord. Försök igen.");
        f37179c.put("locked_user", "Ditt PayPal-konto har tillfälligt låsts. Försök igen senare eller gå till www.paypal.com för att låsa upp ditt PayPal-konto direkt.");
        f37179c.put("max_attempts_exceeded", "För många misslyckade inloggningsförsök. Försök igen senare.");
        f37179c.put("invalid_request", "Ett fel har inträffat.");
        String str15 = "Begäran medges ej.";
        f37179c.put("unauthorized_client", str15);
        f37179c.put("access_denied", str15);
        f37179c.put("unsupported_response_type", "Ett fel har inträffat.");
        f37179c.put("invalid_scope", str15);
        f37179c.put("server_error", str2);
        f37179c.put("temporarily_unavailable", str2);
        f37179c.put("stepup_required", "Det går inte att slutföra din inloggning just nu. Försök igen senare eller gå till www.paypal.com om du har några säkerhetsfrågor om ditt PayPal-konto.");
        f37179c.put("account_locked_generate_challenge_limit_exceeded", "För många inloggningsförsök. Försök igen senare eller kontakta PayPal för att få hjälp.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "sv";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37178b.containsKey(sb2) ? f37178b.get(sb2) : f37177a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37179c.get(str);
    }
}
