package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.zc */
public final class C12033zc implements C11857oc {

    /* renamed from: a */
    private static final Map f37863a = new HashMap();

    /* renamed from: b */
    private static final Map f37864b = new HashMap();

    /* renamed from: c */
    private static final Map f37865c = new HashMap();

    public C12033zc() {
        f37863a.put(C11761Rb.AGREE_AND_PAY, "Accetta e paga");
        f37863a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "e altri");
        f37863a.put(C11761Rb.AUTHENTICATING, "Autenticazione…");
        f37863a.put(C11761Rb.BACK_BUTTON, "Indietro");
        f37863a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Di riserva");
        f37863a.put(C11761Rb.CANCEL, "Annulla");
        f37863a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        String str = "Carta Aura";
        f37863a.put(C11761Rb.CARDTYPE_CARTAAURA, str);
        f37863a.put(C11761Rb.CARDTYPE_CARTEAURORE, str);
        f37863a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Prepagata PayPal");
        f37863a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37863a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37863a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37863a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37863a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37863a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37863a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37863a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37863a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37863a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37863a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37863a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37863a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Modifica metodo di pagamento");
        String str2 = "Conto corrente";
        f37863a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, str2);
        f37863a.put(C11761Rb.CHECKING_DEVICE, "Controllo dispositivo…");
        f37863a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Rimuovi dati della carta");
        f37863a.put(C11761Rb.CONFIRM, "Conferma");
        f37863a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Rimuovere i dati della carta?");
        f37863a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Addebita importo sulla carta");
        f37863a.put(C11761Rb.CONFIRM_LOG_OUT, "Vuoi uscire da PayPal?");
        f37863a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Paga");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Accetta");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data creazione conto");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Stato del conto");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo di conto");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Indirizzo");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Fascia di età");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data di nascita");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Indirizzo email");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nome e cognome");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sesso");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Lingua");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefono");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Fuso orario");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Condividi il seguente: %s.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Usa Pagamento express.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s ti chiede di:");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Condividi i <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Per effettuare una scelta, attiva la visualizzazione dei metodi di pagamento.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "consentirgli di aggiungere e gestire la propria carta fedeltà nel tuo portafoglio PayPal.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Accettare l’<a href='%2$s'></a> Informativa sulla privacy<a href='%3$s'> e le</a> Condizioni d’uso di %1$s.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Consentirgli di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Consentirgli di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        f37863a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Consenso");
        f37863a.put(C11761Rb.EMAIL, "Email");
        f37863a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Dati di esempio");
        f37863a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37863a.put(C11761Rb.EXPIRES_ON_DATE, "Scadenza");
        f37863a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal condivide solo i tuoi metodi di pagamento disponibili per l’utilizzo.</p>");
        f37863a.put(C11761Rb.FORGOT_PASSWORD, "Password dimenticata?");
        f37863a.put(C11761Rb.FROM_ACCOUNT, "Da");
        f37863a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Come vuoi pagare i prossimi acquisti su %1$s?");
        f37863a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>Si applica la sezione Pagamenti automatici delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        f37863a.put(C11761Rb.INTERNAL_ERROR, "Errore interno");
        f37863a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Cliccando il pulsante di seguito, accetto le <a href='%1$s'>Condizioni d’uso PayPal</a> e dichiaro di rispettare le leggi e normative del Giappone, tra cui le sanzioni previste per i pagamenti alla Corea del Nord e all’Iran in base al <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> (Legge sugli scambi e sul commercio estero), per completare la transazione.</p>");
        f37863a.put(C11761Rb.LOG_IN, "Accedi");
        String str3 = "Log in con PayPal";
        f37863a.put(C11761Rb.LOG_IN_TO_PAYPAL, str3);
        f37863a.put(C11761Rb.LOG_OUT_BUTTON, "Esci");
        f37863a.put(C11761Rb.LOG_OUT, "Esci");
        f37863a.put(C11761Rb.OK, "OK");
        f37863a.put(C11761Rb.PASSWORD, "Password");
        f37863a.put(C11761Rb.PAY_AFTER_DELIVERY, "Paga dopo la consegna");
        f37863a.put(C11761Rb.PAY_WITH, "Paga con");
        f37863a.put(C11761Rb.PAY_WITH_CARD, "Paga con una carta");
        f37863a.put(C11761Rb.PAYPAL_BALANCE, "Saldo PayPal");
        f37863a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37863a.put(C11761Rb.PHONE, "Telefono");
        f37863a.put(C11761Rb.PIN, "PIN");
        f37863a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Metodo di pagamento preferito");
        f37863a.put(C11761Rb.PRIVACY, "PayPal protegge la tua <a href='%s'>privacy</a> e i tuoi dati.");
        f37863a.put(C11761Rb.PROCESSING, "Elaborazione in corso");
        f37863a.put(C11761Rb.REMEMBER_CARD, "Ricorda dati carta");
        f37863a.put(C11761Rb.REQUEST_MONEY, "Richiedi denaro");
        f37863a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        f37863a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, str2);
        f37863a.put(C11761Rb.SEND_MONEY, "Invia denaro");
        f37863a.put(C11761Rb.SERVER_PROBLEM, "Si è verificato un problema con i nostri server. Riprova.");
        f37863a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Ripeti l’accesso a PayPal.");
        f37863a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sessione scaduta");
        f37863a.put(C11761Rb.SHIPPING_ADDRESS, "Indirizzo di spedizione");
        f37863a.put(C11761Rb.SIGN_UP, "Non hai un conto PayPal? Registrati");
        f37863a.put(C11761Rb.STAY_LOGGED_IN, "Rimani connesso");
        f37863a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Errore di sistema (%s). Riprova più tardi.");
        f37863a.put(C11761Rb.TRY_AGAIN, "Riprova");
        f37863a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione.");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Codice di sicurezza");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Ricevi un SMS sul tuo telefono. Il codice a 6 cifre sarà valido per 5 minuti.");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Invio SMS in corso");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Immetti il codice di sicurezza a 6 cifre");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Numero di cellulare");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Ricevi SMS");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Ricevi un altro SMS");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione. Visita il sito PayPal per attivare la chiave di accesso.");
        f37863a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Pagamenti da questo dispositivo non consentiti.");
        f37863a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo non autorizzato");
        f37863a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "I pagamenti a questo venditore non sono consentiti (clientId non valido).");
        f37863a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Sito non valido");
        f37863a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Si è verificato un problema durante l’elaborazione del pagamento. Riprova.");
        f37863a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Metodo non riconosciuto");
        f37863a.put(C11761Rb.WE_ARE_SORRY, "Spiacenti");
        f37863a.put(C11761Rb.YOUR_ORDER, "Il tuo ordine");
        f37863a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Questo dispositivo non dialoga con PayPal perché la versione di Android è obsoleta. Aggiorna Android o prova con un dispositivo più recente.");
        f37863a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Rimuovere la carta?");
        f37863a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Consenso non riuscito");
        f37863a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Connessione non riuscita");
        f37863a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Accesso non riuscito");
        f37863a.put(C11761Rb.LOGIN_WITH_EMAIL, "Accedi con la password");
        f37863a.put(C11761Rb.LOGIN_WITH_PHONE, "Accedi con il PIN");
        f37863a.put(C11761Rb.ONE_MOMENT, "Attendi…");
        f37863a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Pagamento non riuscito");
        f37863a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Scansione");
        f37863a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Codice di sicurezza errato. Riprova.");
        f37863a.put(C11761Rb.VIA_LABEL, "tramite");
        String str4 = "Errore di sistema. Riprova più tardi.";
        f37863a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str4);
        String str5 = "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.";
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str5);
        String str6 = "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.";
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Condividi con loro i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str6);
        f37864b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str6);
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        String str7 = "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.";
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str7);
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str7);
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str7);
        f37864b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preautorizza i prossimi pagamenti dal tuo conto PayPal senza effettuare ogni volta l’accesso al conto. <a href='%1$s'>Vedi le condizioni aggiuntive</a>, tra cui i metodi di pagamento e le modalità di annullamento dei pagamenti preautorizzati.");
        String str8 = "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.";
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str8);
        f37864b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str8);
        String str9 = "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.";
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str9);
        f37864b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str9);
        String str10 = "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>";
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str10);
        f37864b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str10);
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito (il saldo PayPal, il conto bancario, la carta di credito o di debito, in quest’ordine) verrà usato per pagare gli acquisti con PayPal. Se sul tuo metodo di pagamento preferito non è presente denaro sufficiente per l’acquisto, la banca o la società emittente della carta potrebbe addebitarti una tariffa.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Modifica</strong> accanto a “Log in con PayPal”.</p>");
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Si applica la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        String str11 = "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>";
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a> per maggiori informazioni.</p>");
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37864b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Come prima opzione per pagare i tuoi acquisti, verrà usato il tuo saldo PayPal. Se non è sufficiente, verranno usati, nell’ordine, il conto bancario, PayPal Credit, la carta di debito (bancomat), la carta di credito e/o gli eCheck.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante dall’elenco.</p><p>Potrebbe essere richiesta l’autorizzazione di un piccolo pagamento per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal. L’autorizzazione verrà annullata e non ti verrà addebitato alcun importo.</p>");
        f37864b.put("LOG_IN_TO_PAYPAL|AU", str3);
        f37864b.put("LOG_IN_TO_PAYPAL|GB", str3);
        String str12 = "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>";
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>";
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>";
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco. Se usi ancora la versione classica del sito, vai al tuo <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p>");
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37864b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37865c.put("AMOUNT_MISMATCH", "Il totale del carrello non corrisponde all’importo delle vendite.");
        f37865c.put("AUTHORIZATION_ALREADY_COMPLETED", "L’autorizzazione è già stata completata.");
        f37865c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L’autorizzazione è in una provincia in cui non può essere annullata.");
        f37865c.put("AUTHORIZATION_EXPIRED", "L’autorizzazione è scaduta.");
        f37865c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L’ID autorizzazione richiesto non esiste.");
        f37865c.put("AUTHORIZATION_VOIDED", "L’autorizzazione è stata annullata.");
        f37865c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "È possibile riautorizzare solo le autorizzazioni originali.");
        f37865c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "La riautorizzazione non è consentita nel periodo di validità.");
        f37865c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
        f37865c.put("CARD_TOKEN_PAYER_MISMATCH", "Impossibile accedere ai dati della carta in archivio.");
        f37865c.put("CREDIT_CARD_CVV_CHECK_FAILED", "I dati della carta non sono validi. Correggi i tuoi dati e riprova.");
        f37865c.put("CREDIT_CARD_REFUSED", "Carta rifiutata.");
        f37865c.put("CURRENCY_MISMATCH", "La valuta di riscossione deve essere uguale a quella di autorizzazione.");
        f37865c.put("CURRENCY_NOT_ALLOWED", "Valuta non supportata da PayPal.");
        f37865c.put("DATA_RETRIEVAL", str4);
        f37865c.put("DUPLICATE_REQUEST_ID", str4);
        f37865c.put("EXPIRED_CREDIT_CARD", "La carta è scaduta");
        f37865c.put("EXPIRED_CREDIT_CARD_TOKEN", "I dati di questa carta non sono più in archivio.\nInoltrali di nuovo.");
        f37865c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "La funzione non è supportata per questo beneficiario.");
        f37865c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "La transazione è stata già rimborsata parzialmente.");
        f37865c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "L’opzione di pagamento immediato non è supportata per la finalità impostata.");
        f37865c.put("INSTRUMENT_DECLINED", "Il metodo di pagamento selezionato non è stato accettato. Scegli un altro metodo di pagamento.");
        f37865c.put("INSUFFICIENT_FUNDS", "L’acquirente non può pagare per denaro insufficiente.");
        f37865c.put("INTERNAL_SERVICE_ERROR", str4);
        f37865c.put("INVALID_ACCOUNT_NUMBER", "Il numero di conto non esiste.");
        f37865c.put("INVALID_ARGUMENT", "Transazione rifiutata per problemi tecnici");
        f37865c.put("INVALID_CITY_STATE_ZIP", "Combinazione Città/Provincia/CAP non valida.");
        f37865c.put("INVALID_FACILITATOR_CONFIGURATION", "Impossibile elaborare la transazione per configurazione non valida.");
        f37865c.put("INVALID_PAYER_ID", "Errore di sistema (ID acquirente non valido). Riprova più tardi.");
        f37865c.put("INVALID_RESOURCE_ID", str4);
        f37865c.put("PAYEE_ACCOUNT_INVALID", "Il conto del beneficiario non ha un’email confermata.");
        f37865c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Questo venditore non può ricevere pagamenti al momento.");
        f37865c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Il conto del beneficiario non ha un’email confermata.");
        f37865c.put("PAYEE_ACCOUNT_RESTRICTED", "Questo venditore non può ricevere pagamenti al momento.");
        f37865c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Il tuo conto è bloccato o chiuso.");
        f37865c.put("PAYER_ACCOUNT_RESTRICTED", "Il tuo conto è stato limitato.");
        f37865c.put("PAYER_CANNOT_PAY", "Impossibile inviare questo pagamento con PayPal.");
        f37865c.put("PAYER_EMPTY_BILLING_ADDRESS", "L’indirizzo di fatturazione è obbligatorio per le transazioni con carta non effettuate con PayPal.");
        f37865c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossibile accedere ai dati della carta in archivio.");
        f37865c.put("PAYMENT_APPROVAL_EXPIRED", "L’approvazione del pagamento è scaduta.");
        f37865c.put("PAYMENT_EXPIRED", "Il pagamento è scaduto.");
        f37865c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "L’acquirente non ha approvato il pagamento.");
        f37865c.put("PAYMENT_REQUEST_ID_INVALID", "Il codice (ID) di richiesta PayPal non è valido. Riprova più tardi.");
        f37865c.put("PAYMENT_STATE_INVALID", "Richiesta non valida nella provincia di pagamento.");
        f37865c.put("PERMISSION_DENIED", "L’operazione richiesta non è autorizzata.");
        f37865c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Il rimborso richiesto supera l’importo della transazione originale.");
        f37865c.put("REFUND_TIME_LIMIT_EXCEEDED", "Questa transazione è troppo datata per essere rimborsata.");
        f37865c.put("REQUIRED_SCOPE_MISSING", str4);
        f37865c.put("TOO_MANY_REAUTHORIZATIONS", "Per questa autorizzazione non sono più consentite riautorizzazioni.");
        f37865c.put("TRANSACTION_ALREADY_REFUNDED", "La transazione è stata già rimborsata.");
        f37865c.put("TRANSACTION_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
        f37865c.put("TRANSACTION_REFUSED", "La transazione è stata rifiutata.");
        f37865c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transazione è stata rifiutata.");
        f37865c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Le preferenze del commerciante sono impostate per rifiutare automaticamente determinate transazioni.");
        f37865c.put("UNKNOWN_ERROR", str4);
        f37865c.put("UNSUPPORTED_PAYEE_COUNTRY", "Il tuo Paese non è supportato.");
        f37865c.put("VALIDATION_ERROR", "I dati di pagamento non sono validi. Correggi i tuoi dati e riprova.");
        f37865c.put("ORDER_ALREADY_COMPLETED", "L’ordine è stato già annullato, è scaduto o completato.");
        f37865c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Il numero massimo di autorizzazioni consentite per l’ordine è stato raggiunto.");
        f37865c.put("ORDER_VOIDED", "L’ordine è stato annullato.");
        f37865c.put("ORDER_CANNOT_BE_VOIDED", "L’ordine è in uno stato che impedisce l’annullamento.");
        f37865c.put("INVALID_EXPERIENCE_PROFILE_ID", str4);
        f37865c.put("UNAUTHORIZED_PAYMENT", "Il commerciante non accetta questo tipo di pagamenti.");
        f37865c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta non supportata per il tipo di carta.");
        f37865c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo di carta non supportato.");
        f37865c.put("ADDRESS_ADDITION_ERROR", "Si è verificato un errore durante l’aggiunta dell’indirizzo di spedizione al conto PayPal.");
        f37865c.put("DUPLICATE_TRANSACTION", "Transazione doppia");
        f37865c.put("INVALID_SHIPPING_ADDRESS", "L’indirizzo di spedizione non è valido.");
        f37865c.put("PAYMENT_CREATION_ERROR", "Si è verificato un problema nella disposizione del pagamento. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Si è verificato un problema nella disposizione del pagamento: la tua carta è scaduta. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Si è verificato un problema nella disposizione del pagamento: è richiesto un pagamento immediato, ad esempio una carta di credito. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Si è verificato un problema nella disposizione del pagamento: la carta deve essere confermata. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Si è verificato un problema nella disposizione del pagamento: questa applicazione richiede che sul tuo conto sia registrato un numero di telefono. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Si è verificato un problema nella disposizione del pagamento: il conto necessita di un metodo di pagamento valido, ad esempio un conto bancario o una carta di pagamento. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Si è verificato un problema nella disposizione del pagamento: il tuo saldo è negativo. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Si è verificato un problema nella disposizione del pagamento: hai raggiunto il tuo limite di invio. Vai su paypal.it e controlla il tuo conto.");
        f37865c.put("AUTH_RC_RISK_FAILURE", "Rifiutata per motivi di rischio.");
        f37865c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autorizzato.");
        f37865c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autorizzato.");
        f37865c.put("invalid_user", "Email o password non corretta. Riprova.");
        f37865c.put("locked_user", "Il tuo conto PayPal è stato temporaneamente bloccato. Riprova più tardi o accedi a www.paypal.com per sbloccare immediatamente il tuo conto PayPal.");
        f37865c.put("max_attempts_exceeded", "Troppi tentativi di accesso non riusciti. Riprova più tardi.");
        f37865c.put("invalid_request", "Si è verificato un errore.");
        String str15 = "Richiesta non autorizzata.";
        f37865c.put("unauthorized_client", str15);
        f37865c.put("access_denied", str15);
        f37865c.put("unsupported_response_type", "Si è verificato un errore.");
        f37865c.put("invalid_scope", str15);
        f37865c.put("server_error", str4);
        f37865c.put("temporarily_unavailable", str4);
        f37865c.put("stepup_required", "Non è possibile completare l’accesso. Riprova più tardi o accedi a www.paypal.it per risolvere eventuali problema di sicurezza del tuo conto PayPal.");
        f37865c.put("account_locked_generate_challenge_limit_exceeded", "Troppi tentativi di accesso. Riprova più tardi o contatta PayPal per richiedere assistenza.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "it";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37864b.containsKey(sb2) ? f37864b.get(sb2) : f37863a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37865c.get(str);
    }
}
