package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.rc */
public final class C12001rc implements C11857oc {

    /* renamed from: a */
    private static final Map f37684a = new HashMap();

    /* renamed from: b */
    private static final Map f37685b = new HashMap();

    /* renamed from: c */
    private static final Map f37686c = new HashMap();

    public C12001rc() {
        f37684a.put(C11761Rb.AGREE_AND_PAY, "Zustimmen und zahlen");
        f37684a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "und andere");
        f37684a.put(C11761Rb.AUTHENTICATING, "Authentifizierung");
        f37684a.put(C11761Rb.BACK_BUTTON, "Zurück");
        f37684a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Alternative");
        f37684a.put(C11761Rb.CANCEL, "Abbrechen");
        f37684a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37684a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37684a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37684a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37684a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37684a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37684a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37684a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37684a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37684a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37684a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37684a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37684a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37684a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37684a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37684a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37684a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Zahlungsmethode ändern");
        f37684a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Girokonto");
        f37684a.put(C11761Rb.CHECKING_DEVICE, "Gerät wird überprüft…");
        f37684a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Kreditkartendaten löschen");
        f37684a.put(C11761Rb.CONFIRM, "Bestätigen");
        f37684a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Möchten Sie Ihre Kreditkartendaten wirklich löschen?");
        f37684a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Kreditkarte belasten");
        f37684a.put(C11761Rb.CONFIRM_LOG_OUT, "Möchten Sie sich wirklich ausloggen?");
        f37684a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Zahlen");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Zustimmen");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Konto eröffnet am");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotyp");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Altersgruppe");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Geburtsdatum");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-Mail-Adresse");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Vollständiger Name");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Geschlecht");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Sprache");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Ländereinstellung");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zeitzone");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Folgende Informationen weitergeben: %s.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "PayPal Express verwenden.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s bittet um folgende Zustimmung:");
        String str = "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.";
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, str);
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Zahlungsquellen anzeigen, damit Sie bei der Zahlung wählen können.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Sie stimmen zu, dass der Händler seine Kundenkarte Ihrer E-Börse hinzufügt und sie dort verwaltet.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Sie stimmen den <a href='%2$s'>Datenschutzgrundsätzen</a> und den <a href='%3$s'>Nutzungsbedingungen</a> von %1$s zu.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Sie gestatten dem Händler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Sie gestatten dem Händler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        f37684a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Zustimmen");
        f37684a.put(C11761Rb.EMAIL, "E-Mail-Adresse");
        f37684a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Beispieldaten");
        f37684a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37684a.put(C11761Rb.EXPIRES_ON_DATE, "Gültig bis");
        f37684a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsmethoden verfügbar sind.</p>");
        f37684a.put(C11761Rb.FORGOT_PASSWORD, "Passwort vergessen?");
        f37684a.put(C11761Rb.FROM_ACCOUNT, "Von");
        f37684a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "Wie möchten Sie Ihre weiteren Zahlungen an %1$s finanzieren?");
        f37684a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Für zukünftige PayPal-Zahlungen bei diesem Händler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diesen Händler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        f37684a.put(C11761Rb.INTERNAL_ERROR, "Interner Fehler");
        f37684a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Durch Klicken auf den Button unten stimme ich den <a href='%1$s'>PayPal-Nutzungsbedingungen</a> zu und bestätige, dass ich bei dieser Transaktion die japanischen Gesetze und Vorschriften einhalte, einschließlich Sanktionen hinsichtlich Zahlungen nach Nordkorea oder in den Iran gemäß dem <a href='%2$s'>Gesetz über Devisen und internationalen Handel</a>.</p>");
        f37684a.put(C11761Rb.LOG_IN, "Einloggen");
        String str2 = "Login mit PayPal";
        f37684a.put(C11761Rb.LOG_IN_TO_PAYPAL, str2);
        f37684a.put(C11761Rb.LOG_OUT_BUTTON, "Ausloggen");
        f37684a.put(C11761Rb.LOG_OUT, "Ausloggen");
        f37684a.put(C11761Rb.OK, "OK");
        f37684a.put(C11761Rb.PASSWORD, "Passwort");
        f37684a.put(C11761Rb.PAY_AFTER_DELIVERY, "Bezahlung nach 14 Tagen");
        f37684a.put(C11761Rb.PAY_WITH, "Zahlen mit");
        f37684a.put(C11761Rb.PAY_WITH_CARD, "Mit Kreditkarte zahlen");
        f37684a.put(C11761Rb.PAYPAL_BALANCE, "PayPal-Guthaben");
        f37684a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37684a.put(C11761Rb.PHONE, "Handynr.");
        f37684a.put(C11761Rb.PIN, "PIN");
        f37684a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Bevorzugte Zahlungsmethode");
        f37684a.put(C11761Rb.PRIVACY, "PayPal schützt Ihre <a href='%s'>Privatsphäre</a> und Ihre Finanzinformationen.");
        f37684a.put(C11761Rb.PROCESSING, "In Verarbeitung");
        f37684a.put(C11761Rb.REMEMBER_CARD, "Kreditkarte speichern");
        f37684a.put(C11761Rb.REQUEST_MONEY, "Geld anfordern");
        f37684a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f37684a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparkonto");
        f37684a.put(C11761Rb.SEND_MONEY, "Geld senden");
        f37684a.put(C11761Rb.SERVER_PROBLEM, "Beim Datenaustausch mit den PayPal-Servern ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        f37684a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Loggen Sie sich erneut bei PayPal ein.");
        f37684a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Sitzung abgelaufen");
        f37684a.put(C11761Rb.SHIPPING_ADDRESS, "Lieferadresse");
        f37684a.put(C11761Rb.SIGN_UP, "Neu bei PayPal? Neu anmelden");
        f37684a.put(C11761Rb.STAY_LOGGED_IN, "Eingeloggt bleiben");
        f37684a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "Systemfehler (%s). Bitte versuchen Sie es später noch einmal.");
        f37684a.put(C11761Rb.TRY_AGAIN, "Erneut versuchen");
        f37684a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Einloggen nicht möglich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist.");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Sicherheitscode");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Wir senden Ihnen eine SMS auf Ihr Handy. Diese enthält einen 6-stelligen Code, der fünf Minuten lang gültig ist.");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "SMS senden");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "6-stelligen Sicherheitscode eingeben");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ihre Handynummer");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "SMS senden");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "SMS erneut senden");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Einloggen nicht möglich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist. Aktivieren Sie über die PayPal-Website Ihren Sicherheitsschlüssel.");
        f37684a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Mit diesem Gerät sind keine Zahlungen möglich.");
        f37684a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Nicht autorisiertes Gerät");
        f37684a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Zahlungen an diesen Händler sind nicht möglich (ungültige Client-ID).");
        f37684a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Ungültiger Händler");
        f37684a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "Bei der Verarbeitung Ihrer Zahlung ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        f37684a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Nicht erkannte Zahlungsquelle");
        f37684a.put(C11761Rb.WE_ARE_SORRY, "Fehler");
        f37684a.put(C11761Rb.YOUR_ORDER, "Ihre Bestellung");
        f37684a.put(C11761Rb.ANDROID_OS_TOO_OLD, "Dieses Gerät kann nicht mit PayPal kommunizieren, weil seine Android-Version zu alt ist. Aktualisieren Sie Android oder versuchen Sie es mit einem neueren Gerät.");
        f37684a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Kreditkarte löschen?");
        f37684a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Zustimmung fehlgeschlagen");
        f37684a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Keine Verbindung");
        f37684a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Login nicht erfolgreich");
        f37684a.put(C11761Rb.LOGIN_WITH_EMAIL, "Mit Passwort einloggen");
        f37684a.put(C11761Rb.LOGIN_WITH_PHONE, "Mit PIN einloggen");
        f37684a.put(C11761Rb.ONE_MOMENT, "Einen Moment…");
        f37684a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Zahlung fehlgeschlagen.");
        f37684a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Fotografieren");
        f37684a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Sicherheitscode falsch. Bitte versuchen Sie es erneut.");
        f37684a.put(C11761Rb.VIA_LABEL, "über");
        String str3 = "Systemfehler. Bitte versuchen Sie es später noch einmal.";
        f37684a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str3);
        String str4 = "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.";
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str4);
        String str5 = "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen über Ihre <a href='%1$s'>Zahlungsquellen</a>.";
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Sie genehmigen die Weitergabe von Informationen über die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a> an den Händler.");
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str4);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str5);
        f37685b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str5);
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal-Vertrag über Abonnementzahlungen</a>.</p>");
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen für zukünftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Beträge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal-Vertrag über Abonnementzahlungen</a>.</p>");
        String str6 = "Sie <a href='%1$s'>autorisieren Abbuchungen</a> für zukünftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Beträge zu zahlen.";
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37685b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Sie genehmigen Zahlungen aus Abbuchungsaufträgen, die auch dann gesendet werden, wenn Sie nicht bei PayPal eingeloggt sind. <a href='%1$s'>Weitere Bedingungen</a>, einschließlich Informationen zu Zahlungsmethoden und Hinweise zur Stornierung von Abbuchungsaufträgen.");
        String str7 = "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.";
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37685b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.";
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37685b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verfügbar sind.</p>";
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verfügbar sind.</p>";
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37685b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle (PayPal-Guthaben, hinzugefügtes Bankkonto, Debit Card oder Kreditkarte, in dieser Reihenfolge). Wenn Ihre Standardzahlungsquelle nicht ausreichend gedeckt ist, kann Ihre Bank oder Ihr Kreditkartenanbieter eine Gebühr berechnen.</p><p>Wenn Sie diese Vereinbarung kündigen möchten, klicken Sie in Ihrem PayPal-Konto unter <strong>Mein Profil</strong> auf <strong>Einstellungen</strong> und anschließend neben “Login mit PayPal” auf <strong>Ändern</strong>.</p>");
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Für zukünftige PayPal-Zahlungen bei diesem Händler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen Sie diesen Händler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        String str11 = "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>";
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorisierung für zukünftige Zahlungen</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und löschen Sie diesen Händler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> für Zahlungen im Einzugsverfahren.</p>");
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir künftig Zahlungen von Ihrem PayPal-Konto abbuchen können, führt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>Für Einkäufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu kündigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37685b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>PayPal verwendet zuerst Ihr PayPal-Guthaben, um Einkäufe zu bezahlen. Wenn Ihr Guthaben nicht für den gesamten Betrag ausreicht, werden die folgenden Zahlungsquellen in der angegebenen Reihenfolge verwendet: Bankkonto, PayPal Credit, Debit Card, Kreditkarte und/oder Lastschrift mit Sicherheitsprüfung.</p><p>Um diese Vereinbarung zu kündigen, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> und löschen Sie diesen Händler aus der Liste.</p><p>Eventuell ist eine Zahlungsautorisierung erforderlich, damit Zahlungen künftig von Ihrem PayPal-Konto abgebucht werden können. Die Autorisierung wird storniert und es wird nichts abgebucht.</p>");
        f37685b.put("LOG_IN_TO_PAYPAL|AU", str2);
        f37685b.put("LOG_IN_TO_PAYPAL|GB", str2);
        String str12 = "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>";
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und löschen Sie diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>";
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>";
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheits-Center</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler. Im klassischen Design klicken Sie unter <strong>Mein Profil</strong> auf <strong>Kontoeinstellungen</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.it ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.ru ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Partners.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str14);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com.tr ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal übernimmt keine Verantwortung für die Handlungen oder Fehler des Händlers.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Händler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen möchten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf “Einstellungen”. Anschließend klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Händler.</p>");
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37685b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37686c.put("AMOUNT_MISMATCH", "Warenkorbsumme stimmt nicht mit Gesamtbetrag überein.");
        f37686c.put("AUTHORIZATION_ALREADY_COMPLETED", "Diese Autorisierung ist bereits abgeschlossen.");
        f37686c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisierung hat einen Status, der nicht storniert werden kann.");
        f37686c.put("AUTHORIZATION_EXPIRED", "Autorisierung ist abgelaufen.");
        f37686c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Der angeforderte Autorisierungscode existiert nicht.");
        f37686c.put("AUTHORIZATION_VOIDED", "Autorisierung wurde storniert.");
        f37686c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Nur die ursprüngliche Autorisierung kann erneut autorisiert werden. Bereits erneut autorisierte Zahlungen können nicht nochmals autorisiert werden.");
        f37686c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Erneute Autorisierungen während des Anerkennungszeitraums sind nicht möglich.");
        f37686c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Der Betrag übersteigt Ihr Limit.");
        f37686c.put("CARD_TOKEN_PAYER_MISMATCH", "Zugriff auf gespeicherte Kreditkartendaten nicht möglich.");
        f37686c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Die Kreditkartendaten sind ungültig. Bitte korrigieren Sie Ihre Eingabe und versuchen Sie es erneut.");
        f37686c.put("CREDIT_CARD_REFUSED", "Kreditkarte abgelehnt.");
        f37686c.put("CURRENCY_MISMATCH", "Die Währung beim Einzug muss mit der Währung der Autorisierung übereinstimmen.");
        f37686c.put("CURRENCY_NOT_ALLOWED", "Diese Währung wird von PayPal derzeit nicht unterstützt.");
        f37686c.put("DATA_RETRIEVAL", str3);
        String str15 = "Systemfehler. Versuchen Sie es später noch einmal.";
        f37686c.put("DUPLICATE_REQUEST_ID", str15);
        f37686c.put("EXPIRED_CREDIT_CARD", "Kreditkarte abgelaufen");
        f37686c.put("EXPIRED_CREDIT_CARD_TOKEN", "Diese Kreditkarte ist nicht mehr gespeichert.\nBitte erneut senden.");
        f37686c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktion wird für diesen Anbieter nicht unterstützt.");
        f37686c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Für diese Transaktion wurde bereits eine Teilrückzahlung geleistet.");
        f37686c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Sofortzahlung wird für diesen Intent nicht unterstützt.");
        f37686c.put("INSTRUMENT_DECLINED", "Ihre ausgewählte Zahlungsquelle wurde nicht akzeptiert. Wählen Sie eine andere Zahlungsquelle.");
        f37686c.put("INSUFFICIENT_FUNDS", "Käufer kann nicht zahlen – Guthaben nicht ausreichend.");
        f37686c.put("INTERNAL_SERVICE_ERROR", str15);
        f37686c.put("INVALID_ACCOUNT_NUMBER", "Diese Kontonummer existiert nicht.");
        f37686c.put("INVALID_ARGUMENT", "Transaktion wegen eines ungültigen Arguments abgelehnt");
        f37686c.put("INVALID_CITY_STATE_ZIP", "Ungültige Kombination aus Ort/Bundesstaat/PLZ.");
        f37686c.put("INVALID_FACILITATOR_CONFIGURATION", "Diese Transaktion kann aufgrund einer ungültigen Facilitator-Konfiguration nicht verarbeitet werden.");
        f37686c.put("INVALID_PAYER_ID", "Systemfehler (ungültige Absender-ID). Bitte versuchen Sie es später noch einmal.");
        f37686c.put("INVALID_RESOURCE_ID", str15);
        f37686c.put("PAYEE_ACCOUNT_INVALID", "Die E-Mail-Adresse des Anbieters ist nicht bestätigt.");
        f37686c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        f37686c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Die E-Mail-Adresse des Anbieters ist nicht bestätigt.");
        f37686c.put("PAYEE_ACCOUNT_RESTRICTED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        f37686c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ihr Konto ist gesperrt oder geschlossen.");
        f37686c.put("PAYER_ACCOUNT_RESTRICTED", "Der Zugriff auf Ihr Konto ist eingeschränkt.");
        f37686c.put("PAYER_CANNOT_PAY", "Sie können diese Transaktion nicht mit PayPal bezahlen.");
        f37686c.put("PAYER_EMPTY_BILLING_ADDRESS", "Rechnungsadresse ist für Transaktionen mit Nicht-PayPal-Kreditkarten erforderlich.");
        f37686c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Zugriff auf gespeicherte Kreditkartendaten nicht möglich.");
        f37686c.put("PAYMENT_APPROVAL_EXPIRED", "Die Zahlungsgenehmigung ist abgelaufen.");
        f37686c.put("PAYMENT_EXPIRED", "Die Zahlung ist abgelaufen.");
        f37686c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Der Absender hat die Zahlung nicht genehmigt.");
        f37686c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-Anforderungs-ID ist ungültig. Versuchen Sie es später noch einmal.");
        f37686c.put("PAYMENT_STATE_INVALID", "Diese Anforderung ist aufgrund des aktuellen Zahlungsstatus ungültig.");
        f37686c.put("PERMISSION_DENIED", "Keine Genehmigung für die angeforderte Aktion.");
        f37686c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Die angeforderte Rückzahlung übersteigt den Betrag der ursprünglichen Transaktion.");
        f37686c.put("REFUND_TIME_LIMIT_EXCEEDED", "Diese Transaktion ist zu alt für eine Rückzahlung.");
        f37686c.put("REQUIRED_SCOPE_MISSING", str15);
        f37686c.put("TOO_MANY_REAUTHORIZATIONS", "Für diese Autorisierung sind keine weiteren Autorisierungen möglich.");
        f37686c.put("TRANSACTION_ALREADY_REFUNDED", "Für diese Transaktion wurde bereits eine Rückzahlung geleistet.");
        f37686c.put("TRANSACTION_LIMIT_EXCEEDED", "Der Betrag übersteigt Ihr Limit.");
        f37686c.put("TRANSACTION_REFUSED", "Die Transaktion wurde abgelehnt.");
        f37686c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Die Transaktion wurde abgelehnt.");
        f37686c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Einstellung im Händlerprofil: Bestimmte Transaktionen werden automatisch abgelehnt.");
        f37686c.put("UNKNOWN_ERROR", str15);
        f37686c.put("UNSUPPORTED_PAYEE_COUNTRY", "Ihr Land wird nicht unterstützt.");
        f37686c.put("VALIDATION_ERROR", "Die Zahlungsdaten sind ungültig. Bitte korrigieren und Eingabe wiederholen.");
        f37686c.put("ORDER_ALREADY_COMPLETED", "Bestellung ist bereits storniert, abgelaufen oder abgeschlossen.");
        f37686c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Die maximal zulässige Anzahl an Autorisierungen für die Bestellung wurde erreicht.");
        f37686c.put("ORDER_VOIDED", "Bestellung wurde storniert.");
        f37686c.put("ORDER_CANNOT_BE_VOIDED", "Bestellung kann in diesem Status nicht storniert werden.");
        f37686c.put("INVALID_EXPERIENCE_PROFILE_ID", str15);
        f37686c.put("UNAUTHORIZED_PAYMENT", "Der Händler akzeptiert diesen Zahlungstyp nicht.");
        f37686c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Währung wird bei Kartentyp nicht unterstützt.");
        f37686c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kreditkartentyp wird nicht unterstützt.");
        f37686c.put("ADDRESS_ADDITION_ERROR", "Fehler beim Hinzufügen der Lieferadresse zum PayPal-Konto.");
        f37686c.put("DUPLICATE_TRANSACTION", "Doppelte Transaktion.");
        f37686c.put("INVALID_SHIPPING_ADDRESS", "Die angegebene Lieferadresse ist nicht gültig.");
        f37686c.put("PAYMENT_CREATION_ERROR", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Ihre Kreditkarte ist abgelaufen. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sofortzahlung erforderlich, z.B. mit Kreditkarte. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – bestätigte Kreditkarte erforderlich. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – für diese App muss in Ihrem Konto eine Telefonnummer hinterlegt sein. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sie brauchen ein Konto mit einer gültigen Zahlungsquelle (Bankkonto oder Zahlungskarte). Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Ihr Konto ist im Minus. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten – Sie haben Ihr Sendelimit erreicht. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto.");
        f37686c.put("AUTH_RC_RISK_FAILURE", "Aufgrund von Risikomodellen abgelehnt");
        f37686c.put("AUTH_RC_OFAC_BLOCKED_IP", "Nicht autorisierter Client");
        f37686c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Nicht autorisierter Client");
        f37686c.put("invalid_user", "Benutzername/Passwort nicht korrekt. Bitte versuchen Sie es erneut.");
        f37686c.put("locked_user", "Ihr PayPal-Konto wurde vorübergehend gesperrt. Versuchen Sie es später noch einmal oder entsperren Sie Ihr Konto über www.paypal.com.");
        f37686c.put("max_attempts_exceeded", "Zu viele fehlgeschlagene Logins. Versuchen Sie es später noch einmal.");
        f37686c.put("invalid_request", "Es ist ein Fehler aufgetreten.");
        f37686c.put("unauthorized_client", "Anforderung nicht autorisiert.");
        f37686c.put("access_denied", "Anforderung nicht autorisiert.");
        f37686c.put("unsupported_response_type", "Es ist ein Fehler aufgetreten.");
        f37686c.put("invalid_scope", "Anforderung nicht autorisiert.");
        f37686c.put("server_error", str3);
        f37686c.put("temporarily_unavailable", str15);
        f37686c.put("stepup_required", "Wir können Sie zurzeit nicht einloggen. Versuchen Sie es später noch einmal, oder loggen Sie sich aus Sicherheitsgründen über die PayPal-Website ein.");
        f37686c.put("account_locked_generate_challenge_limit_exceeded", "Zu viele fehlgeschlagene Logins. Versuchen Sie es später noch einmal oder wenden Sie sich an PayPal.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "de";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37685b.containsKey(sb2) ? f37685b.get(sb2) : f37684a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37686c.get(str);
    }
}
