package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.tc */
public final class C12009tc implements C11857oc {

    /* renamed from: a */
    private static final Map f37754a = new HashMap();

    /* renamed from: b */
    private static final Map f37755b = new HashMap();

    /* renamed from: c */
    private static final Map f37756c = new HashMap();

    public C12009tc() {
        f37754a.put(C11761Rb.AGREE_AND_PAY, "Agree and Pay");
        f37754a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "& other");
        f37754a.put(C11761Rb.AUTHENTICATING, "Authenticating");
        f37754a.put(C11761Rb.BACK_BUTTON, "Back");
        f37754a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Backup");
        f37754a.put(C11761Rb.CANCEL, "Cancel");
        f37754a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37754a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37754a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37754a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37754a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37754a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37754a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37754a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37754a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37754a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37754a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37754a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37754a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37754a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37754a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37754a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37754a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Change Payment Method");
        f37754a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Cheque");
        f37754a.put(C11761Rb.CHECKING_DEVICE, "Checking this device…");
        f37754a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Clear card information");
        f37754a.put(C11761Rb.CONFIRM, "Confirm");
        f37754a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Are you sure you want to clear your card information?");
        f37754a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Charge Card");
        f37754a.put(C11761Rb.CONFIRM_LOG_OUT, "Are you sure you want to log out of PayPal?");
        f37754a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Pay");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Agree");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Account Creation Date");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Account Status");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Account Type");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Address");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Age Range");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Date of Birth");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Email address");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Full Name");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Gender");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Language");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Phone Number");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Time Zone");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Share the following: %s.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Use Seamless Checkout.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s asks that you:");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Share the <a href='%1$s'>payment methods</a> linked to your PayPal account.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Enable the display of your funding options to allow you to make a choice.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Allow them to link and manage their loyalty card in your PayPal wallet.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Agree to the %1$s <a href='%2$s'>privacy policy</a> and <a href='%3$s'>user agreement</a>.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Permit them to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Permit them to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.");
        f37754a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Consent");
        f37754a.put(C11761Rb.EMAIL, "Email");
        f37754a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Mock Data");
        f37754a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37754a.put(C11761Rb.EXPIRES_ON_DATE, "Expires");
        f37754a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares which of your payment methods are available for use.</p>");
        f37754a.put(C11761Rb.FORGOT_PASSWORD, "Forgotten your password?");
        f37754a.put(C11761Rb.FROM_ACCOUNT, "From");
        f37754a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "How would you like to fund future payments to %1$s?");
        f37754a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Future Payment Agreement</strong></h1><p>Your default payment method will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        f37754a.put(C11761Rb.INTERNAL_ERROR, "Internal Error");
        f37754a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>By clicking the button below, I hereby agree to the terms of the <a href='%1$s'>PayPal User Agreement</a> and declare that I am in compliance with Japanese laws and regulations, including sanctions against payments to North Korea and Iran pursuant to the <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> to complete the transaction.</p>");
        f37754a.put(C11761Rb.LOG_IN, "Log In");
        String str = "Log In with PayPal";
        f37754a.put(C11761Rb.LOG_IN_TO_PAYPAL, str);
        f37754a.put(C11761Rb.LOG_OUT_BUTTON, "Log out");
        f37754a.put(C11761Rb.LOG_OUT, "Log out");
        f37754a.put(C11761Rb.OK, "OK");
        f37754a.put(C11761Rb.PASSWORD, "Password");
        f37754a.put(C11761Rb.PAY_AFTER_DELIVERY, "Pay After Delivery");
        f37754a.put(C11761Rb.PAY_WITH, "Pay with");
        f37754a.put(C11761Rb.PAY_WITH_CARD, "Pay with Card");
        f37754a.put(C11761Rb.PAYPAL_BALANCE, "PayPal Balance");
        f37754a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37754a.put(C11761Rb.PHONE, "Phone");
        f37754a.put(C11761Rb.PIN, "PIN");
        f37754a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Preferred Payment Method");
        f37754a.put(C11761Rb.PRIVACY, "PayPal protects your <a href='%s'>privacy</a> and financial information.");
        f37754a.put(C11761Rb.PROCESSING, "Processing");
        f37754a.put(C11761Rb.REMEMBER_CARD, "Remember card");
        f37754a.put(C11761Rb.REQUEST_MONEY, "Request Money");
        f37754a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37754a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Savings");
        f37754a.put(C11761Rb.SEND_MONEY, "Send Money");
        f37754a.put(C11761Rb.SERVER_PROBLEM, "There was a problem communicating with the PayPal servers. Please try again.");
        f37754a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Please log in to PayPal again.");
        f37754a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Session expired.");
        f37754a.put(C11761Rb.SHIPPING_ADDRESS, "Shipping Address");
        f37754a.put(C11761Rb.SIGN_UP, "New to PayPal? Sign Up");
        f37754a.put(C11761Rb.STAY_LOGGED_IN, "Stay logged in");
        f37754a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "System error (%s). Please try again later.");
        f37754a.put(C11761Rb.TRY_AGAIN, "Try Again");
        f37754a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Unable to log in because two-factor authentication has been enabled for your account.");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Security Code");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Send an SMS to your phone. The 6-digit code you receive will be valid for 5 minutes.");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sending SMS");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Enter the 6-digit security code");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Your mobile number");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Send SMS");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send SMS Again");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Unable to log in because two-factor authentication has been enabled for your account. Please visit the PayPal website to activate your security key.");
        f37754a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Payments from this device are not allowed.");
        f37754a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Unauthorised Device");
        f37754a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Payments to this merchant are not allowed (invalid clientId).");
        f37754a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Invalid merchant");
        f37754a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "There was a problem processing your payment. Please try again.");
        f37754a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Unrecognised Source");
        f37754a.put(C11761Rb.WE_ARE_SORRY, "We’re Sorry");
        f37754a.put(C11761Rb.YOUR_ORDER, "Your Order");
        f37754a.put(C11761Rb.ANDROID_OS_TOO_OLD, "This device cannot communicate with PayPal because this version of Android is too old. Please upgrade Android or try a newer device.");
        f37754a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Clear Card?");
        f37754a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Consent Failed");
        f37754a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Connection Failed");
        f37754a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Login Failed");
        f37754a.put(C11761Rb.LOGIN_WITH_EMAIL, "Log in with password");
        f37754a.put(C11761Rb.LOGIN_WITH_PHONE, "Log in with PIN");
        f37754a.put(C11761Rb.ONE_MOMENT, "One moment…");
        f37754a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Payment Failed");
        f37754a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Scan");
        f37754a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Incorrect Security code. Please try again.");
        f37754a.put(C11761Rb.VIA_LABEL, "Via");
        String str2 = "System error. Please try again later.";
        f37754a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str2);
        String str3 = "Share information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str3);
        String str4 = "Share the information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str4);
        String str5 = "Share the <a href='%1$s'>funding sources</a> on your behalf until you withdraw consent.";
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str3);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str3);
        String str6 = "Share information about the <a href='%1$s'>payment methods</a> linked to your PayPal account.";
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str6);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Share information with them about the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Share the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Share the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str4);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str6);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str4);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str6);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str5);
        f37755b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str5);
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        String str7 = "<a href='%1$s'>Authorise charges</a> for future purchases paid for with PayPal. You authorise and instruct PayPal to pay all amounts.";
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str7);
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str7);
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str7);
        f37755b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Pre-approve future payments made from your PayPal account without logging in to PayPal each time. <a href='%1$s'>See additional terms</a>, including payment methods and how to cancel future payments.");
        String str8 = "Permit %2$s to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.";
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str8);
        f37755b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str8);
        String str9 = "Permit %2$s to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.";
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str9);
        f37755b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str9);
        String str10 = "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares which of your funding sources are available for use.</p>";
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str10);
        String str11 = "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares the information about which of your funding sources are available for use.</p>";
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str11);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str11);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str11);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str10);
        f37755b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str10);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your default payment method (your PayPal balance, linked bank account, credit or debit card, in that order) will be used to pay for PayPal purchases. Please note, if your default payment method doesn’t have enough funds to cover the purchase, your bank or card provider may charge you a fee.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> then click <strong>My settings</strong> and <strong>Change</strong> beside “Log in with PayPal.”</p>");
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal Account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal Account, go to <strong>Profile</strong> &gt; <strong>Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Future Payment Agreement</strong></h1><p>Your default payment method will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        String str12 = "<h1><strong>Future Payment authorisation</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this authorisation, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>Please see the “Pre-approved Payments” section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>";
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str12);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str12);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str12);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str12);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str12);
        f37755b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Future Payment Agreement</strong></h1><p>PayPal will first use your PayPal balance to pay for your purchase. If that doesn’t cover your total, your bank account, PayPal Credit, debit card, credit card, and/or eCheque will be used in that order.</p><p>To cancel this agreement, go to www.paypal.com.au <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>A small payment authorisation may be required to make sure your PayPal account can be charged in the future. The authorisation will be voided and you won’t be charged.</p>");
        f37755b.put("LOG_IN_TO_PAYPAL|AU", str);
        f37755b.put("LOG_IN_TO_PAYPAL|GB", str);
        String str13 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str13);
        String str14 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account and click on the gear icon. Go to <strong>Security</strong>, select <strong>Log In with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>";
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str14);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log in with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str13);
        String str15 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under your <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str15);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str14);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str14);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account, click on the gear icon at the top right corner, choose <strong>Security</strong>, select <strong>Log In with PayPal</strong> and remove the merchant. If you’re still using the classic website, go to <strong>My Profile</strong>, choose <strong>My Account Settings</strong>, select <strong>Log In with PayPal</strong> and remove the merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account, then under <strong>Profile</strong> settings go to <strong>Log in with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.it then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str15);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str15);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in at paypal.ru, click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com.tr click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p>");
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str13);
        f37755b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str13);
        f37756c.put("AMOUNT_MISMATCH", "Cart item amount total does not match sale amount.");
        f37756c.put("AUTHORIZATION_ALREADY_COMPLETED", "This authorisation has already been completed.");
        f37756c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Authorisation is in a state that cannot be voided.");
        f37756c.put("AUTHORIZATION_EXPIRED", "Authorisation has expired.");
        f37756c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "The requested authorisation ID does not exist.");
        f37756c.put("AUTHORIZATION_VOIDED", "authorisation has been voided.");
        f37756c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Can only reauthorise the original authorisation, not a reauthorisation.");
        f37756c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Reauthorisation is not allowed within the honour period.");
        f37756c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37756c.put("CARD_TOKEN_PAYER_MISMATCH", "Cannot access saved card information.");
        f37756c.put("CREDIT_CARD_CVV_CHECK_FAILED", "The card information is invalid. Please correct and submit again.");
        f37756c.put("CREDIT_CARD_REFUSED", "Card declined.");
        f37756c.put("CURRENCY_MISMATCH", "Currency of capture must be the same as currency of authorisation.");
        f37756c.put("CURRENCY_NOT_ALLOWED", "This currency is not currently supported by PayPal.");
        f37756c.put("DATA_RETRIEVAL", str2);
        f37756c.put("DUPLICATE_REQUEST_ID", str2);
        f37756c.put("EXPIRED_CREDIT_CARD", "Card has expired");
        f37756c.put("EXPIRED_CREDIT_CARD_TOKEN", "The information for this card is no longer on file.\nPlease submit again.");
        f37756c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Feature is unsupported for this vendor.");
        f37756c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "This transaction has already been partially refunded.");
        f37756c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Immediate pay is not supported for the Intent passed.");
        f37756c.put("INSTRUMENT_DECLINED", "Your selected payment method was not accepted. Please choose a different method.");
        f37756c.put("INSUFFICIENT_FUNDS", "Buyer cannot pay – insufficient funds.");
        f37756c.put("INTERNAL_SERVICE_ERROR", str2);
        f37756c.put("INVALID_ACCOUNT_NUMBER", "That account number does not exist.");
        f37756c.put("INVALID_ARGUMENT", "Transaction denied because of an invalid argument");
        f37756c.put("INVALID_CITY_STATE_ZIP", "Invalid suburb/state/postcode combination.");
        f37756c.put("INVALID_FACILITATOR_CONFIGURATION", "This transaction cannot be processed due to an invalid facilitator configuration.");
        f37756c.put("INVALID_PAYER_ID", "System error (invalid Payer ID). Please try again later.");
        f37756c.put("INVALID_RESOURCE_ID", str2);
        f37756c.put("PAYEE_ACCOUNT_INVALID", "Vendor account does not have a confirmed email address.");
        f37756c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "This vendor cannot receive payments at this time.");
        f37756c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Vendor account does not have a confirmed email address.");
        f37756c.put("PAYEE_ACCOUNT_RESTRICTED", "This vendor cannot receive payments at this time.");
        f37756c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Your account is locked or closed.");
        f37756c.put("PAYER_ACCOUNT_RESTRICTED", "Your account has been limited.");
        f37756c.put("PAYER_CANNOT_PAY", "You cannot pay for this transaction with PayPal.");
        f37756c.put("PAYER_EMPTY_BILLING_ADDRESS", "Billing address is required for non-PayPal credit card transactions.");
        f37756c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Cannot access saved card information.");
        f37756c.put("PAYMENT_APPROVAL_EXPIRED", "Payment approval has expired.");
        f37756c.put("PAYMENT_EXPIRED", "The payment has expired.");
        f37756c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Payer has not approved payment.");
        f37756c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal request ID is invalid. Please try again later.");
        f37756c.put("PAYMENT_STATE_INVALID", "This request is invalid due to the current state of the payment.");
        f37756c.put("PERMISSION_DENIED", "No permission for the requested operation.");
        f37756c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "The requested refund exceeds the amount of the original transaction.");
        f37756c.put("REFUND_TIME_LIMIT_EXCEEDED", "This transaction is too old to refund.");
        f37756c.put("REQUIRED_SCOPE_MISSING", str2);
        f37756c.put("TOO_MANY_REAUTHORIZATIONS", "No more reauthorisations for this authorisation are allowed.");
        f37756c.put("TRANSACTION_ALREADY_REFUNDED", "This transaction has already been refunded.");
        f37756c.put("TRANSACTION_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37756c.put("TRANSACTION_REFUSED", "The transaction was denied.");
        f37756c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "The transaction was denied.");
        f37756c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Merchant profile preference is set to automatically deny certain transactions.");
        f37756c.put("UNKNOWN_ERROR", str2);
        f37756c.put("UNSUPPORTED_PAYEE_COUNTRY", "Your country is unsupported.");
        f37756c.put("VALIDATION_ERROR", "The payment information is invalid. Please correct and submit again.");
        f37756c.put("ORDER_ALREADY_COMPLETED", "Order has already been voided or completed, or has expired.");
        f37756c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maximum number of allowed authorisations for the order has been reached.");
        f37756c.put("ORDER_VOIDED", "Order has been voided.");
        f37756c.put("ORDER_CANNOT_BE_VOIDED", "Order is in a state which prevents voiding.");
        f37756c.put("INVALID_EXPERIENCE_PROFILE_ID", str2);
        f37756c.put("UNAUTHORIZED_PAYMENT", "The merchant does not accept payments of this type.");
        f37756c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Currency not supported for card type.");
        f37756c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Card type not supported.");
        f37756c.put("ADDRESS_ADDITION_ERROR", "Error encountered while adding shipping address to PayPal account.");
        f37756c.put("DUPLICATE_TRANSACTION", "Duplicate transaction.");
        f37756c.put("INVALID_SHIPPING_ADDRESS", "The shipping address provided is not valid.");
        f37756c.put("PAYMENT_CREATION_ERROR", "There was a problem setting up this payment. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "There was a problem setting up this payment - your card has expired. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "There was a problem setting up this payment - instant payment required, such as a credit card. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "There was a problem setting up this payment - card must be confirmed. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "There was a problem setting up this payment - this app requires that your account include a phone number. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "There was a problem setting up this payment - account needs a valid payment method, such as a bank account or payment card. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "There was a problem setting up this payment - your balance is negative. Please visit the PayPal website to check your account.");
        f37756c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "There was a problem setting up this payment - your sending limit has been reached. Please visit the PayPal website to check your account.");
        f37756c.put("AUTH_RC_RISK_FAILURE", "Declined due to risk.");
        f37756c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client not authorised.");
        f37756c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client not authorised.");
        f37756c.put("invalid_user", "Incorrect username/password. Please try again.");
        f37756c.put("locked_user", "Your PayPal account has been temporarily locked. Please try again later, or go to www.paypal.com to immediately unlock your PayPal account.");
        f37756c.put("max_attempts_exceeded", "Too many failed login attempts. Please try again later.");
        f37756c.put("invalid_request", "An error has occurred.");
        f37756c.put("unauthorized_client", "Request not authorised.");
        f37756c.put("access_denied", "Request not authorised.");
        f37756c.put("unsupported_response_type", "An error has occurred.");
        f37756c.put("invalid_scope", "Request not authorised.");
        f37756c.put("server_error", str2);
        f37756c.put("temporarily_unavailable", str2);
        f37756c.put("stepup_required", "Your login cannot be completed at this time. Please try again later, or go to www.paypal.com to address any security concerns with your PayPal account.");
        f37756c.put("account_locked_generate_challenge_limit_exceeded", "Too many login attempts. Please try again later or contact PayPal for help.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "en_AU";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37755b.containsKey(sb2) ? f37755b.get(sb2) : f37754a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37756c.get(str);
    }
}
