package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.sc */
public final class C12005sc implements C11857oc {

    /* renamed from: a */
    private static final Map f37689a = new HashMap();

    /* renamed from: b */
    private static final Map f37690b = new HashMap();

    /* renamed from: c */
    private static final Map f37691c = new HashMap();

    public C12005sc() {
        f37689a.put(C11761Rb.AGREE_AND_PAY, "Agree and Pay");
        f37689a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "& other");
        f37689a.put(C11761Rb.AUTHENTICATING, "Authenticating");
        f37689a.put(C11761Rb.BACK_BUTTON, "Back");
        f37689a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Backup");
        f37689a.put(C11761Rb.CANCEL, "Cancel");
        f37689a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37689a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37689a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37689a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37689a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37689a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37689a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37689a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37689a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37689a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37689a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37689a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37689a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37689a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37689a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37689a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37689a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Change Payment Method");
        f37689a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Checking");
        f37689a.put(C11761Rb.CHECKING_DEVICE, "Checking this device…");
        f37689a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Clear card information");
        f37689a.put(C11761Rb.CONFIRM, "Confirm");
        f37689a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Are you sure you want to clear your card information?");
        f37689a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Charge Card");
        f37689a.put(C11761Rb.CONFIRM_LOG_OUT, "Are you sure you want to log out of PayPal?");
        f37689a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Pay");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Agree");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Account Creation Date");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Account Status");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Account Type");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Address");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Age Range");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Birth Date");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Email address");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Full Name");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Gender");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Language");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telephone");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Time Zone");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Share the following: %s.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Use Seamless Checkout.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s asks that you:");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Share the <a href='%1$s'>payment methods</a> linked to your PayPal account.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Enable display of your funding options to allow you to make a choice.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Authorize charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Allow them to add and manage their loyalty card in your PayPal wallet.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Agree to the %1$s <a href='%2$s'>privacy policy</a> and <a href='%3$s'>user agreement</a>.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Permit them to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Permit them to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.");
        f37689a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Consent");
        f37689a.put(C11761Rb.EMAIL, "Email");
        f37689a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Mock Data");
        f37689a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37689a.put(C11761Rb.EXPIRES_ON_DATE, "Expires");
        f37689a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares which of your payment methods are available for use.</p>");
        f37689a.put(C11761Rb.FORGOT_PASSWORD, "Forgot password?");
        f37689a.put(C11761Rb.FROM_ACCOUNT, "From");
        f37689a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "How would you like to fund future payments to %1$s?");
        f37689a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Future Payment Agreement</strong></h1><p>Your default funding source will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        f37689a.put(C11761Rb.INTERNAL_ERROR, "Internal Error");
        f37689a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>By clicking the button below, I hereby agree to the terms of the <a href='%1$s'>PayPal User Agreement</a> and declare that I am in compliance with Japanese laws and regulations, including sanctions against payments to North Korea and Iran pursuant to the <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> to complete the transaction.</p>");
        f37689a.put(C11761Rb.LOG_IN, "Log In");
        f37689a.put(C11761Rb.LOG_IN_TO_PAYPAL, "Log In with PayPal");
        f37689a.put(C11761Rb.LOG_OUT_BUTTON, "Log Out");
        f37689a.put(C11761Rb.LOG_OUT, "Log out");
        f37689a.put(C11761Rb.OK, "OK");
        f37689a.put(C11761Rb.PASSWORD, "Password");
        f37689a.put(C11761Rb.PAY_AFTER_DELIVERY, "Pay After Delivery");
        f37689a.put(C11761Rb.PAY_WITH, "Pay with");
        f37689a.put(C11761Rb.PAY_WITH_CARD, "Pay with Card");
        f37689a.put(C11761Rb.PAYPAL_BALANCE, "PayPal Balance");
        f37689a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37689a.put(C11761Rb.PHONE, "Phone");
        f37689a.put(C11761Rb.PIN, "PIN");
        f37689a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Preferred Payment Method");
        f37689a.put(C11761Rb.PRIVACY, "PayPal protects your <a href='%s'>privacy</a> and financial information.");
        f37689a.put(C11761Rb.PROCESSING, "Processing");
        f37689a.put(C11761Rb.REMEMBER_CARD, "Remember card");
        f37689a.put(C11761Rb.REQUEST_MONEY, "Request Money");
        f37689a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37689a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Savings");
        f37689a.put(C11761Rb.SEND_MONEY, "Send Money");
        f37689a.put(C11761Rb.SERVER_PROBLEM, "There was a problem communicating with the PayPal servers. Please try again.");
        f37689a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Please log in again to PayPal.");
        f37689a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Session Expired");
        f37689a.put(C11761Rb.SHIPPING_ADDRESS, "Shipping Address");
        f37689a.put(C11761Rb.SIGN_UP, "New to PayPal? Sign Up");
        f37689a.put(C11761Rb.STAY_LOGGED_IN, "Stay logged in");
        f37689a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "System error (%s). Please try again later.");
        f37689a.put(C11761Rb.TRY_AGAIN, "Try Again");
        f37689a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Unable to log in, because two-factor authentication has been enabled for your account.");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Security Code");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Send a text message to your phone. The 6-digit code you receive will be valid for 5 minutes.");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sending Text");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Enter the 6-digit security code");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Your mobile number");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Send Text");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send Text again");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Unable to log in, because two-factor authentication has been enabled for your account. Please visit the PayPal website to activate your security key.");
        f37689a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Payments from this device are not allowed.");
        f37689a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Unauthorized Device");
        f37689a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Payments to this merchant are not allowed (invalid clientId).");
        f37689a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Invalid merchant");
        f37689a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "There was a problem processing your payment. Please try again.");
        f37689a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Unrecognized Source");
        f37689a.put(C11761Rb.WE_ARE_SORRY, "We’re Sorry");
        f37689a.put(C11761Rb.YOUR_ORDER, "Your Order");
        f37689a.put(C11761Rb.ANDROID_OS_TOO_OLD, "This device cannot communicate with PayPal because this version of Android is too old. Please upgrade Android or try a newer device.");
        f37689a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Clear Card?");
        f37689a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Consent Failed");
        f37689a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Connection Failed");
        f37689a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Login Failed");
        f37689a.put(C11761Rb.LOGIN_WITH_EMAIL, "Log in with password");
        f37689a.put(C11761Rb.LOGIN_WITH_PHONE, "Log in with PIN");
        f37689a.put(C11761Rb.ONE_MOMENT, "One moment…");
        f37689a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Payment Failed");
        f37689a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Scan");
        f37689a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Incorrect Security Code. Please try again.");
        f37689a.put(C11761Rb.VIA_LABEL, "Via");
        String str = "System error. Please try again later.";
        f37689a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str);
        String str2 = "Share information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str2);
        String str3 = "Share the information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str3);
        String str4 = "Share the <a href='%1$s'>funding sources</a> on your behalf until you withdraw consent.";
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str2);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str2);
        String str5 = "Share information about the <a href='%1$s'>payment methods</a> linked to your PayPal account.";
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str5);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Share information with them about the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Share the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Share the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str3);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str5);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str3);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str5);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str4);
        f37690b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str4);
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Authorize charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Authorize charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        String str6 = "<a href='%1$s'>Authorize charges</a> for future purchases paid for with PayPal. You authorize and instruct PayPal to pay all amounts.";
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str6);
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str6);
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str6);
        f37690b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preapprove future payments made from your PayPal account without logging in to PayPal each time. <a href='%1$s'>See additional terms</a>, including payment methods and how to cancel future payments.");
        String str7 = "Permit %2$s to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.";
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str7);
        f37690b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str7);
        String str8 = "Permit %2$s to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.";
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str8);
        f37690b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str8);
        String str9 = "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares which of your funding sources are available for use.</p>";
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str9);
        String str10 = "<h1><strong>Payment Methods</strong></h1><p>PayPal only shares the information about which of your funding sources are available for use.</p>";
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str10);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str10);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str10);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str9);
        f37690b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str9);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your default payment method (your PayPal balance, linked bank account, debit card or credit card, in that order) will be used to pay for PayPal purchases. Please note, if your default payment method doesn’t have enough funds to cover the purchase, your bank or card provider may charge you a fee.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> then click <strong>My settings</strong> and <strong>Change</strong> beside “Log in with PayPal.”</p>");
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal Account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal Account, go to <strong>Profile</strong> &gt; <strong>Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Future Payment Agreement</strong></h1><p>Your default funding source will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        String str11 = "<h1><strong>Future Payment Authorization</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default payment method will be used to pay for PayPal purchases.</p><p>To cancel this authorization, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>Please see the “Preapproved Payments” section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>";
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str11);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str11);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary credit or debit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str11);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str11);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str11);
        f37690b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Future Payment Agreement</strong></h1><p>PayPal will first use your PayPal balance to pay for your purchase. If that doesn’t cover your total, your bank account, PayPal Credit, debit card, credit card, and/or eCheck will be used in that order.</p><p>To cancel this agreement, go to www.paypal.com <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>A small payment authorization may be required to make sure your PayPal account can be charged in the future. The authorization will be voided and you won’t be charged.</p>");
        f37690b.put("LOG_IN_TO_PAYPAL|AU", "Log in with PayPal");
        f37690b.put("LOG_IN_TO_PAYPAL|GB", "Log in with PayPal");
        String str12 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str12);
        String str13 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account and click on the gear icon. Go to <strong>Security</strong>, select <strong>Log In with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>";
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str13);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log in with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str12);
        String str14 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under your <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", str14);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str13);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str13);
        String str15 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", str15);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account, click on the gear icon at the top right corner, choose <strong>Security Center</strong>, select <strong>Log In with PayPal</strong> and remove the merchant. If you’re still using the classic website, go to <strong>My Profile</strong>, choose <strong>My Account Settings</strong>, select <strong>Log In with PayPal</strong> and remove the merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account, then under <strong>Profile</strong> settings go to <strong>Log in with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.it then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", str14);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", str15);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", str14);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in at paypal.ru, click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", str15);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com.tr click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p>");
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str12);
        f37690b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str12);
        f37691c.put("AMOUNT_MISMATCH", "Cart item amounts total does not match sale amount.");
        f37691c.put("AUTHORIZATION_ALREADY_COMPLETED", "This authorization has already been completed.");
        f37691c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Authorization is in a state that cannot be voided.");
        f37691c.put("AUTHORIZATION_EXPIRED", "Authorization has expired.");
        f37691c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "The requested authorization ID does not exist.");
        f37691c.put("AUTHORIZATION_VOIDED", "Authorization has been voided.");
        f37691c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Can only reauthorize the original authorization, not a reauthorization.");
        f37691c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Reauthorization is not allowed within the honor period.");
        f37691c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37691c.put("CARD_TOKEN_PAYER_MISMATCH", "Cannot access saved card information.");
        f37691c.put("CREDIT_CARD_CVV_CHECK_FAILED", "The card information is invalid. Please correct and submit again.");
        f37691c.put("CREDIT_CARD_REFUSED", "Card declined.");
        f37691c.put("CURRENCY_MISMATCH", "Currency of capture must be the same as currency of authorization.");
        f37691c.put("CURRENCY_NOT_ALLOWED", "This currency is not currently supported by PayPal.");
        f37691c.put("DATA_RETRIEVAL", str);
        f37691c.put("DUPLICATE_REQUEST_ID", str);
        f37691c.put("EXPIRED_CREDIT_CARD", "Card has expired");
        f37691c.put("EXPIRED_CREDIT_CARD_TOKEN", "The information for this card is no longer on file.\nPlease submit again.");
        f37691c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Feature is unsupported for this vendor.");
        f37691c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "This transaction has already been partially refunded.");
        f37691c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Immediate pay is not supported for the Intent passed.");
        f37691c.put("INSTRUMENT_DECLINED", "Your selected payment method was not accepted. Please choose a different method.");
        f37691c.put("INSUFFICIENT_FUNDS", "Buyer cannot pay - insufficient funds.");
        f37691c.put("INTERNAL_SERVICE_ERROR", str);
        f37691c.put("INVALID_ACCOUNT_NUMBER", "That account number does not exist.");
        f37691c.put("INVALID_ARGUMENT", "Transaction refused because of an invalid argument");
        f37691c.put("INVALID_CITY_STATE_ZIP", "Invalid city/state/postal-code combination.");
        f37691c.put("INVALID_FACILITATOR_CONFIGURATION", "This transaction cannot be processed due to an invalid facilitator configuration.");
        f37691c.put("INVALID_PAYER_ID", "System error (invalid Payer ID). Please try again later.");
        f37691c.put("INVALID_RESOURCE_ID", str);
        f37691c.put("PAYEE_ACCOUNT_INVALID", "Vendor account does not have a confirmed email.");
        f37691c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "This vendor cannot receive payments at this time.");
        f37691c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Vendor account does not have a confirmed email.");
        f37691c.put("PAYEE_ACCOUNT_RESTRICTED", "This vendor cannot receive payments at this time.");
        f37691c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Your account is locked or closed.");
        f37691c.put("PAYER_ACCOUNT_RESTRICTED", "Your account is restricted.");
        f37691c.put("PAYER_CANNOT_PAY", "You cannot pay for this transaction with Paypal.");
        f37691c.put("PAYER_EMPTY_BILLING_ADDRESS", "Billing address is required for non-PayPal credit card transactions.");
        f37691c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Cannot access saved card information.");
        f37691c.put("PAYMENT_APPROVAL_EXPIRED", "Payment approval has expired.");
        f37691c.put("PAYMENT_EXPIRED", "The payment has expired.");
        f37691c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Payer has not approved payment.");
        f37691c.put("PAYMENT_REQUEST_ID_INVALID", "Paypal request id is invalid. Please try again later.");
        f37691c.put("PAYMENT_STATE_INVALID", "This request is invalid due to the current state of the payment.");
        f37691c.put("PERMISSION_DENIED", "No permission for the requested operation.");
        f37691c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "The requested refund exceeds the amount of the original transaction.");
        f37691c.put("REFUND_TIME_LIMIT_EXCEEDED", "This transaction is too old to refund.");
        f37691c.put("REQUIRED_SCOPE_MISSING", str);
        f37691c.put("TOO_MANY_REAUTHORIZATIONS", "No more reauthorizations for this authorization are allowed.");
        f37691c.put("TRANSACTION_ALREADY_REFUNDED", "This transaction has already been refunded.");
        f37691c.put("TRANSACTION_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37691c.put("TRANSACTION_REFUSED", "The transaction was refused.");
        f37691c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "The transaction was refused.");
        f37691c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Merchant profile preference is set to automatically deny certain transactions.");
        f37691c.put("UNKNOWN_ERROR", str);
        f37691c.put("UNSUPPORTED_PAYEE_COUNTRY", "Your country is unsupported.");
        f37691c.put("VALIDATION_ERROR", "The payment information is invalid. Please correct and submit again.");
        f37691c.put("ORDER_ALREADY_COMPLETED", "Order has already been voided, expired or completed.");
        f37691c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maximum number of allowed authorizations for the order has been reached.");
        f37691c.put("ORDER_VOIDED", "Order has been voided.");
        f37691c.put("ORDER_CANNOT_BE_VOIDED", "Order is in a state which prevents voiding.");
        f37691c.put("INVALID_EXPERIENCE_PROFILE_ID", str);
        f37691c.put("UNAUTHORIZED_PAYMENT", "The merchant does not accept payments of this type.");
        f37691c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Currency not supported for card type.");
        f37691c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Card type not supported.");
        f37691c.put("ADDRESS_ADDITION_ERROR", "Error encountered while adding shipping address to PayPal account.");
        f37691c.put("DUPLICATE_TRANSACTION", "Duplicate transaction.");
        f37691c.put("INVALID_SHIPPING_ADDRESS", "The provided shipping address is not valid.");
        f37691c.put("PAYMENT_CREATION_ERROR", "There was a problem setting up this payment. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "There was a problem setting up this payment - your card is expired. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "There was a problem setting up this payment - instant payment required, such as a credit card. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "There was a problem setting up this payment - card must be confirmed. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "There was a problem setting up this payment - this app requires that your account include a phone number. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "There was a problem setting up this payment - account needs a valid funding source, such as a bank or payment card. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "There was a problem setting up this payment - your balance is negative. Please visit the PayPal website to check your account.");
        f37691c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "There was a problem setting up this payment - your sending limit has been reached. Please visit the PayPal website to check your account.");
        f37691c.put("AUTH_RC_RISK_FAILURE", "Declined due to risk.");
        f37691c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client not authorized.");
        f37691c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client not authorized.");
        f37691c.put("invalid_user", "Incorrect username/password. Please try again.");
        f37691c.put("locked_user", "Your PayPal account has been temporarily locked. Please try again later, or go to www.paypal.com to immediately unlock your PayPal account.");
        f37691c.put("max_attempts_exceeded", "Too many failed login attempts. Please try again later.");
        f37691c.put("invalid_request", "An error has occurred.");
        f37691c.put("unauthorized_client", "Request not authorized.");
        f37691c.put("access_denied", "Request not authorized.");
        f37691c.put("unsupported_response_type", "An error has occurred.");
        f37691c.put("invalid_scope", "Request not authorized.");
        f37691c.put("server_error", str);
        f37691c.put("temporarily_unavailable", str);
        f37691c.put("stepup_required", "Your login cannot complete at this time. Please try again later, or go to www.paypal.com to address any security concerns with your PayPal account.");
        f37691c.put("account_locked_generate_challenge_limit_exceeded", "Too many login attempts. Please try again later, or contact PayPal for help.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "en";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37690b.containsKey(sb2) ? f37690b.get(sb2) : f37689a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37691c.get(str);
    }
}
