package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

/* renamed from: com.paypal.android.sdk.uc */
public final class C12013uc implements C11857oc {

    /* renamed from: a */
    private static final Map f37788a = new HashMap();

    /* renamed from: b */
    private static final Map f37789b = new HashMap();

    /* renamed from: c */
    private static final Map f37790c = new HashMap();

    public C12013uc() {
        f37788a.put(C11761Rb.AGREE_AND_PAY, "Agree and Pay");
        f37788a.put(C11761Rb.AND_OTHER_FUNDING_SOURCES, "& other");
        f37788a.put(C11761Rb.AUTHENTICATING, "Authenticating");
        f37788a.put(C11761Rb.BACK_BUTTON, "Back");
        f37788a.put(C11761Rb.BACKUP_FUNDING_SOURCE, "Backup");
        f37788a.put(C11761Rb.CANCEL, "Cancel");
        f37788a.put(C11761Rb.CARDTYPE_AMERICANEXPRESS, "American Express");
        f37788a.put(C11761Rb.CARDTYPE_CARTAAURA, "Carta Aura");
        f37788a.put(C11761Rb.CARDTYPE_CARTEAURORE, "Carte Aurore");
        f37788a.put(C11761Rb.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        f37788a.put(C11761Rb.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        f37788a.put(C11761Rb.CARDTYPE_COFINOGA, "Cofinoga");
        f37788a.put(C11761Rb.CARDTYPE_DELTA, "Delta");
        f37788a.put(C11761Rb.CARDTYPE_DISCOVER, "Discover");
        f37788a.put(C11761Rb.CARDTYPE_ELECTRON, "Electron");
        f37788a.put(C11761Rb.CARDTYPE_JCB, "JCB");
        f37788a.put(C11761Rb.CARDTYPE_MAESTRO, "Maestro");
        f37788a.put(C11761Rb.CARDTYPE_MASTERCARD, "MasterCard");
        f37788a.put(C11761Rb.CARDTYPE_POSTEPAY, "Postepay");
        f37788a.put(C11761Rb.CARDTYPE_4ETOILES, "4 étoiles");
        f37788a.put(C11761Rb.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        f37788a.put(C11761Rb.CARDTYPE_VISA, "Visa");
        f37788a.put(C11761Rb.CHANGE_PAYMENT_METHOD, "Change Funding Source");
        f37788a.put(C11761Rb.CHECKING_ACCOUNT_FOR_INSTITUTION, "Current");
        f37788a.put(C11761Rb.CHECKING_DEVICE, "Checking this device…");
        f37788a.put(C11761Rb.CLEAR_CREDIT_CARD_INFO, "Clear card details");
        f37788a.put(C11761Rb.CONFIRM, "Confirm");
        f37788a.put(C11761Rb.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Are you sure you want to clear your card details?");
        f37788a.put(C11761Rb.CONFIRM_CHARGE_CREDIT_CARD, "Charge Card");
        f37788a.put(C11761Rb.CONFIRM_LOG_OUT, "Are you sure you want to log out of PayPal?");
        f37788a.put(C11761Rb.CONFIRM_SEND_PAYMENT, "Pay");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_AGREE, "Agree");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Account Creation Date");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Account Status");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Account Type");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Address Line 1");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Age Range");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Date of Birth");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Email Address");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Full Name");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Gender");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Language");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Phone Number");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Time Zone");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_ATTRIBUTES, "Share the following: %s.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Use Seamless Checkout.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_INTRO, "%s asks that you:");
        String str = "Share the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, str);
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Enable the display of your funding options to allow you to make a choice.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_LOYALTY_CARD, "Allow them to add and manage their loyalty card in your PayPal wallet.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Agree to the %1$s <a href='%2$s'>privacy policy</a> and <a href='%3$s'>user agreement</a>");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_REQUEST_MONEY, "Permit them to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_SEND_MONEY, "Permit them to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.");
        f37788a.put(C11761Rb.CONSENT_AGREEMENT_TITLE, "Consent");
        f37788a.put(C11761Rb.EMAIL, "Email");
        f37788a.put(C11761Rb.ENVIRONMENT_MOCK_DATA, "Mock Data");
        f37788a.put(C11761Rb.ENVIRONMENT_SANDBOX, "Sandbox");
        f37788a.put(C11761Rb.EXPIRES_ON_DATE, "Expires");
        String str2 = "<h1><strong>Funding Sources</strong></h1><p>PayPal only shares which of your funding sources are available for use.</p>";
        f37788a.put(C11761Rb.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, str2);
        f37788a.put(C11761Rb.FORGOT_PASSWORD, "Forgotten your password?");
        f37788a.put(C11761Rb.FROM_ACCOUNT, "From");
        f37788a.put(C11761Rb.FUTURE_PAYMENT_METHOD_QUESTION, "How would you like to fund future payments to %1$s?");
        f37788a.put(C11761Rb.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Future Payment Agreement</strong></h1><p>Your default funding source will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        f37788a.put(C11761Rb.INTERNAL_ERROR, "Internal Error");
        f37788a.put(C11761Rb.JAPANESE_COMPLIANCE_AGREEMENT, "<p>By clicking the button below, I hereby agree to the terms of the <a href='%1$s'>PayPal User Agreement</a> and declare that I am in compliance with Japanese laws and regulations, including sanctions against payments to North Korea and Iran pursuant to the <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> to complete the transaction.</p>");
        f37788a.put(C11761Rb.LOG_IN, "Log In");
        String str3 = "Log In with PayPal";
        f37788a.put(C11761Rb.LOG_IN_TO_PAYPAL, str3);
        f37788a.put(C11761Rb.LOG_OUT_BUTTON, "Log Out");
        f37788a.put(C11761Rb.LOG_OUT, "Log out");
        f37788a.put(C11761Rb.OK, "OK");
        f37788a.put(C11761Rb.PASSWORD, "Password");
        f37788a.put(C11761Rb.PAY_AFTER_DELIVERY, "Pay After Delivery");
        f37788a.put(C11761Rb.PAY_WITH, "Pay with");
        f37788a.put(C11761Rb.PAY_WITH_CARD, "Pay with Card");
        f37788a.put(C11761Rb.PAYPAL_BALANCE, "PayPal Balance");
        f37788a.put(C11761Rb.PAYPAL_CREDIT, "PayPal Credit");
        f37788a.put(C11761Rb.PHONE, "Phone");
        f37788a.put(C11761Rb.PIN, "PIN");
        f37788a.put(C11761Rb.PREFERRED_PAYMENT_METHOD, "Preferred Funding Source");
        f37788a.put(C11761Rb.PRIVACY, "PayPal protects your <a href='%s'>privacy</a> and financial information.");
        f37788a.put(C11761Rb.PROCESSING, "Processing");
        f37788a.put(C11761Rb.REMEMBER_CARD, "Remember card");
        f37788a.put(C11761Rb.REQUEST_MONEY, "Request Money");
        f37788a.put(C11761Rb.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37788a.put(C11761Rb.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Savings");
        f37788a.put(C11761Rb.SEND_MONEY, "Send Money");
        f37788a.put(C11761Rb.SERVER_PROBLEM, "There was a problem communicating with the PayPal servers. Please try again.");
        f37788a.put(C11761Rb.SESSION_EXPIRED_MESSAGE, "Please log in to PayPal again.");
        f37788a.put(C11761Rb.SESSION_EXPIRED_TITLE, "Session Expired");
        f37788a.put(C11761Rb.SHIPPING_ADDRESS, "Delivery Address");
        f37788a.put(C11761Rb.SIGN_UP, "New to PayPal? Sign Up");
        f37788a.put(C11761Rb.STAY_LOGGED_IN, "Stay logged in");
        f37788a.put(C11761Rb.SYSTEM_ERROR_WITH_CODE, "System error (%s). Please try again later.");
        f37788a.put(C11761Rb.TRY_AGAIN, "Try Again");
        f37788a.put(C11761Rb.TWO_FA_REQUIRED_ERROR, "Unable to log in because two-factor authentication has been enabled for your account.");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_TITLE, "Verification Code");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_SUBTITLE, "Send a text message to your phone. The 6-digit code you receive will be valid for 5 minutes.");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sending Text");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Enter the 6-digit verification code");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Your mobile number");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS, "Send Text");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send Text Again");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Unable to log in because two-factor authentication has been enabled for your account. Please visit the PayPal website to activate your security key.");
        f37788a.put(C11761Rb.UNAUTHORIZED_DEVICE_MESSAGE, "Payments from this device are not allowed.");
        f37788a.put(C11761Rb.UNAUTHORIZED_DEVICE_TITLE, "Unauthorised Device");
        f37788a.put(C11761Rb.UNAUTHORIZED_MERCHANT_MESSAGE, "Payments to this merchant are not allowed (invalid clientId).");
        f37788a.put(C11761Rb.UNAUTHORIZED_MERCHANT_TITLE, "Invalid merchant");
        f37788a.put(C11761Rb.UNEXPECTED_PAYMENT_FLOW, "There was a problem processing your payment. Please try again.");
        f37788a.put(C11761Rb.UNKNOWN_FUNDING_SOURCE, "Unrecognised Source");
        f37788a.put(C11761Rb.WE_ARE_SORRY, "We’re Sorry");
        f37788a.put(C11761Rb.YOUR_ORDER, "Your Order");
        f37788a.put(C11761Rb.ANDROID_OS_TOO_OLD, "This device cannot communicate with PayPal because this version of Android is too old. Please upgrade Android or try a newer device.");
        f37788a.put(C11761Rb.CLEAR_CC_ALERT_TITLE, "Clear Card?");
        f37788a.put(C11761Rb.CONSENT_FAILED_ALERT_TITLE, "Consent Failed");
        f37788a.put(C11761Rb.CONNECTION_FAILED_TITLE, "Connection Failed");
        f37788a.put(C11761Rb.LOGIN_FAILED_ALERT_TITLE, "Login Failed");
        f37788a.put(C11761Rb.LOGIN_WITH_EMAIL, "Log in with password");
        f37788a.put(C11761Rb.LOGIN_WITH_PHONE, "Log in with PIN");
        f37788a.put(C11761Rb.ONE_MOMENT, "One moment…");
        f37788a.put(C11761Rb.PAY_FAILED_ALERT_TITLE, "Payment Failed");
        f37788a.put(C11761Rb.SCAN_CARD_ICON_DESCRIPTION, "Scan");
        f37788a.put(C11761Rb.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Incorrect Security code. Please try again.");
        f37788a.put(C11761Rb.VIA_LABEL, "Via");
        String str4 = "System error. Please try again later.";
        f37788a.put(C11761Rb.PP_SERVICE_ERROR_JSON_PARSE_ERROR, str4);
        String str5 = "Share information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", str5);
        String str6 = "Share the information about the <a href='%1$s'>funding sources</a> linked to your PayPal account.";
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", str6);
        String str7 = "Share the <a href='%1$s'>funding sources</a> on your behalf until you withdraw consent.";
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", str5);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", str5);
        String str8 = "Share information about the <a href='%1$s'>payment methods</a> linked to your PayPal account.";
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", str8);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Share information with them about the <a href='%1$s'>funding sources</a> linked to your PayPal account.");
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", str);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", str);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", str6);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", str8);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", str6);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", str8);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", str7);
        f37789b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", str7);
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Authorise charges</a> for future %2$s purchases paid for with PayPal. You instruct PayPal to pay all amounts requested by %3$s.</p><p>Please see the <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal Recurring Payments and Billing Agreement</a> for more information.</p>");
        String str9 = "<a href='%1$s'>Authorise charges</a> for future purchases paid for with PayPal. You authorise and instruct PayPal to pay all amounts.";
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", str9);
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", str9);
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", str9);
        f37789b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Pre-approve future payments made from your PayPal account without logging in to PayPal each time. <a href='%1$s'>See additional terms</a>, including funding sources and how to cancel future payments.");
        String str10 = "Permit %2$s to <a href='%1$s'>request money</a> on your behalf until you withdraw consent.";
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", str10);
        f37789b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", str10);
        String str11 = "Permit %2$s to <a href='%1$s'>send money</a> on your behalf until you withdraw consent.";
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", str11);
        f37789b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", str11);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", str2);
        String str12 = "<h1><strong>Funding Sources</strong></h1><p>PayPal only shares the information about which of your funding sources are available for use.</p>";
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", str12);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", str12);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", str12);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", str2);
        f37789b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", str2);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your default funding source (your PayPal balance, linked bank account, debit or credit card, in that order) will be used to pay for PayPal purchases. Please note, if your default funding source doesn’t have enough funds to cover the purchase, your bank or card provider may charge you a fee.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> then click <strong>My Settings</strong> and <strong>Change</strong> beside “Log in with PayPal.”</p>");
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary debit or credit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal Account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default funding source will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal Account, go to <strong>Profile</strong> &gt; <strong>Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Future Payment Agreement</strong></h1><p>Your default funding source will be used to pay for future PayPal payments from this merchant.</p><p>To cancel this agreement, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log in with PayPal</strong> and remove this merchant from the list.</p><p>The Recurring Payment section of the <a href='%s'>PayPal User Agreement</a> shall apply.</p><p>To make sure payments work with your PayPal account, this app may simulate a small test transaction, but no money will be transferred for this.</p>");
        String str13 = "<h1><strong>Future Payment Authorisation</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no payment will be transferred.</p><p>Your default funding source will be used to pay for PayPal purchases.</p><p>To cancel this authorisation, log in to your PayPal account, go to <strong>Profile</strong> &gt; <strong>My account settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>Please see the “Pre-approved Payments” section of the <a href='%s'>PayPal User Agreement</a> for more information.</p>";
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", str13);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", str13);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Future Payment Agreement</strong></h1><p>To make sure your PayPal account can be charged in the future, this app may simulate a small test transaction but no money will be transferred.</p><p>Your PayPal balance or primary debit or credit card will be used to pay for PayPal purchases.</p><p>To cancel this agreement, log in to your PayPal account and go to <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p>");
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", str13);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", str13);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", str13);
        f37789b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Future Payment Agreement</strong></h1><p>PayPal will first use your PayPal balance to pay for your purchase. If that doesn’t cover your total, your bank account, PayPal Credit, debit card, credit card, and/or eCheque will be used in that order.</p><p>To cancel this agreement, go to www.paypal.co.uk <strong>Profile</strong> &gt; <strong>My Settings</strong> &gt; <strong>Log In with PayPal</strong> and remove this merchant from the list.</p><p>A small payment authorisation may be required to make sure your PayPal account can be charged in the future. The authorisation will be voided and you won’t be charged.</p>");
        f37789b.put("LOG_IN_TO_PAYPAL|AU", str3);
        f37789b.put("LOG_IN_TO_PAYPAL|GB", str3);
        String str14 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>";
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", str14);
        String str15 = "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account and click on the gear icon. Go to <strong>Security</strong>, select <strong>Log In with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>";
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", str15);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log in with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under your <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", str15);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", str15);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account, click on the gear icon at the top right corner, choose <strong>Security</strong>, select <strong>Log In with PayPal</strong> and remove the merchant. If you’re still using the classic website, go to <strong>My Profile</strong>, choose <strong>My Account Settings</strong>, select <strong>Log In with PayPal</strong> and remove the merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in to your PayPal account, then under <strong>Profile</strong> settings go to <strong>Log in with PayPal</strong> and remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.it then go to <strong>Profile</strong>, <strong>Security</strong>, find the <strong>Log In with PayPal</strong> and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under your <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under your <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the partner.</p><p>To withdraw consent, log in at paypal.ru, click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the partner.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in to your PayPal account then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com.tr click on the gear icon at the top right corner, choose <strong>Security</strong> tab and in the <strong>Log In with PayPal</strong> option remove this partner.</p><p>PayPal is not responsible for any actions or errors on the part of the merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Any relevant transaction details will be shared with the merchant.</p><p>To withdraw consent, log in at paypal.com then go to <strong>Log In with PayPal</strong> options under <strong>Profile</strong> settings and remove this merchant.</p>");
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", str14);
        f37789b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", str14);
        f37790c.put("AMOUNT_MISMATCH", "Cart item amounts total does not match sale amount.");
        f37790c.put("AUTHORIZATION_ALREADY_COMPLETED", "This authorisation has already been completed.");
        f37790c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Authorisation is in a state that cannot be voided.");
        f37790c.put("AUTHORIZATION_EXPIRED", "Authorisation has expired.");
        f37790c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "The requested authorisation ID does not exist.");
        f37790c.put("AUTHORIZATION_VOIDED", "Authorisation has been voided.");
        f37790c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Can only reauthorise the original authorisation, not a reauthorisation.");
        f37790c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Reauthorisation is not allowed within the honour period.");
        f37790c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37790c.put("CARD_TOKEN_PAYER_MISMATCH", "Cannot access saved card details.");
        f37790c.put("CREDIT_CARD_CVV_CHECK_FAILED", "The card details are invalid. Please correct and submit again.");
        f37790c.put("CREDIT_CARD_REFUSED", "Card declined.");
        f37790c.put("CURRENCY_MISMATCH", "Currency of capture must be the same as currency of authorisation.");
        f37790c.put("CURRENCY_NOT_ALLOWED", "This currency is not currently supported by PayPal.");
        f37790c.put("DATA_RETRIEVAL", str4);
        f37790c.put("DUPLICATE_REQUEST_ID", str4);
        f37790c.put("EXPIRED_CREDIT_CARD", "Card has expired");
        f37790c.put("EXPIRED_CREDIT_CARD_TOKEN", "The information for this card is no longer on file.\nPlease submit again.");
        f37790c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Feature is unsupported for this vendor.");
        f37790c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "This transaction has already been partially refunded.");
        f37790c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Immediate pay is not supported for the Intent passed.");
        f37790c.put("INSTRUMENT_DECLINED", "Your selected funding source was not accepted. Please choose a different source.");
        f37790c.put("INSUFFICIENT_FUNDS", "Buyer cannot pay – insufficient funds.");
        f37790c.put("INTERNAL_SERVICE_ERROR", str4);
        f37790c.put("INVALID_ACCOUNT_NUMBER", "That account number does not exist.");
        f37790c.put("INVALID_ARGUMENT", "Transaction refused because of an invalid argument");
        f37790c.put("INVALID_CITY_STATE_ZIP", "Invalid town/city/postcode combination.");
        f37790c.put("INVALID_FACILITATOR_CONFIGURATION", "This transaction cannot be processed due to an invalid facilitator configuration.");
        f37790c.put("INVALID_PAYER_ID", "System error (invalid Payer ID). Please try again later.");
        f37790c.put("INVALID_RESOURCE_ID", str4);
        f37790c.put("PAYEE_ACCOUNT_INVALID", "Vendor account does not have a confirmed email address.");
        f37790c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "This vendor cannot receive payments at this time.");
        f37790c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Vendor account does not have a confirmed email address.");
        f37790c.put("PAYEE_ACCOUNT_RESTRICTED", "This vendor cannot receive payments at this time.");
        f37790c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Your account is locked or closed.");
        f37790c.put("PAYER_ACCOUNT_RESTRICTED", "Your account has been limited.");
        f37790c.put("PAYER_CANNOT_PAY", "You cannot pay for this transaction with PayPal.");
        f37790c.put("PAYER_EMPTY_BILLING_ADDRESS", "Billing address is required for non-PayPal credit card transactions.");
        f37790c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Cannot access saved card details.");
        f37790c.put("PAYMENT_APPROVAL_EXPIRED", "Payment approval has expired.");
        f37790c.put("PAYMENT_EXPIRED", "The payment has expired.");
        f37790c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Payer has not approved payment.");
        f37790c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal request ID is invalid. Please try again later.");
        f37790c.put("PAYMENT_STATE_INVALID", "This request is invalid due to the current state of the payment.");
        f37790c.put("PERMISSION_DENIED", "No permission for the requested operation.");
        f37790c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "The requested refund exceeds the amount of the original transaction.");
        f37790c.put("REFUND_TIME_LIMIT_EXCEEDED", "This transaction is too old to refund.");
        f37790c.put("REQUIRED_SCOPE_MISSING", str4);
        f37790c.put("TOO_MANY_REAUTHORIZATIONS", "No more reauthorisations for this authorisation are allowed.");
        f37790c.put("TRANSACTION_ALREADY_REFUNDED", "This transaction has already been refunded.");
        f37790c.put("TRANSACTION_LIMIT_EXCEEDED", "The amount exceeds the allowable limit.");
        f37790c.put("TRANSACTION_REFUSED", "The transaction was refused.");
        f37790c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "The transaction was refused.");
        f37790c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Merchant profile preference is set to automatically refuse certain transactions.");
        f37790c.put("UNKNOWN_ERROR", str4);
        f37790c.put("UNSUPPORTED_PAYEE_COUNTRY", "Your country is unsupported.");
        f37790c.put("VALIDATION_ERROR", "The payment information is invalid. Please correct and submit again.");
        f37790c.put("ORDER_ALREADY_COMPLETED", "Order has already been voided or completed, or has expired.");
        f37790c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maximum number of allowed authorisations for the order has been reached.");
        f37790c.put("ORDER_VOIDED", "Order has been voided.");
        f37790c.put("ORDER_CANNOT_BE_VOIDED", "Order is in a state which prevents voiding.");
        f37790c.put("INVALID_EXPERIENCE_PROFILE_ID", str4);
        f37790c.put("UNAUTHORIZED_PAYMENT", "The merchant does not accept payments of this type.");
        f37790c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Currency not supported for card type.");
        f37790c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Card type not supported.");
        f37790c.put("ADDRESS_ADDITION_ERROR", "Error encountered while adding delivery address to PayPal account.");
        f37790c.put("DUPLICATE_TRANSACTION", "Duplicate transaction.");
        f37790c.put("INVALID_SHIPPING_ADDRESS", "The delivery address provided is not valid.");
        f37790c.put("PAYMENT_CREATION_ERROR", "There was a problem setting up this payment. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "There was a problem setting up this payment - your card has expired. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "There was a problem setting up this payment - instant payment required, such as a credit card. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "There was a problem setting up this payment - card must be confirmed. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "There was a problem setting up this payment - this app requires that your account include a phone number. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "There was a problem setting up this payment - account needs a valid funding source, such as a bank account or payment card. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "There was a problem setting up this payment - your balance is negative. Please visit the PayPal website to check your account.");
        f37790c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "There was a problem setting up this payment - your sending limit has been reached. Please visit the PayPal website to check your account.");
        f37790c.put("AUTH_RC_RISK_FAILURE", "Declined due to risk.");
        f37790c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client not authorised.");
        f37790c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client not authorised.");
        f37790c.put("invalid_user", "Incorrect username/password. Please try again.");
        f37790c.put("locked_user", "Your PayPal account has been temporarily locked. Please try again later, or go to www.paypal.com to immediately unlock your PayPal account.");
        f37790c.put("max_attempts_exceeded", "Too many failed login attempts. Please try again later.");
        f37790c.put("invalid_request", "An error has occurred.");
        f37790c.put("unauthorized_client", "Request not authorised.");
        f37790c.put("access_denied", "Request not authorised.");
        f37790c.put("unsupported_response_type", "An error has occurred.");
        f37790c.put("invalid_scope", "Request not authorised.");
        f37790c.put("server_error", str4);
        f37790c.put("temporarily_unavailable", str4);
        f37790c.put("stepup_required", "Your login cannot be completed at this time. Please try again later, or go to www.paypal.com to address any security concerns with your PayPal account.");
        f37790c.put("account_locked_generate_challenge_limit_exceeded", "Too many login attempts. Please try again later or contact PayPal for help.");
    }

    /* renamed from: a */
    public final String mo38522a() {
        return "en_GB";
    }

    /* renamed from: a */
    public final /* synthetic */ String mo38523a(Enum enumR, String str) {
        C11761Rb rb = (C11761Rb) enumR;
        StringBuilder sb = new StringBuilder();
        sb.append(rb.toString());
        sb.append("|");
        sb.append(str);
        String sb2 = sb.toString();
        return (String) (f37789b.containsKey(sb2) ? f37789b.get(sb2) : f37788a.get(rb));
    }

    /* renamed from: a */
    public final String mo38524a(String str) {
        return (String) f37790c.get(str);
    }
}
